# -*- coding: utf-8 -*-
"""Jane Kalshi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liUXIpSNvE7XLnboLhxNgbILtO0nBIgR
"""

# Welcome to the Kalshi REST v2 Starter Code!

# pypi client: recommended for more advanced programmers
# import kalshi_python

# starter client: recommended for all levels of programming experience (what this client is implemented using)
from KalshiClientsBaseV2ApiKey_FIXED import ExchangeClient
import pytz
import time
import json
import uuid
import pandas as pd
import numpy as np
import requests
from datetime import datetime, timedelta


from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

import os
import base64

def load_private_key(b64_key="", file_path=""):
    """Load Kalshi RSA key from file or env var (same as monitoring script)."""
    if file_path and os.path.exists(file_path):
        with open(file_path, "rb") as f: pem = f.read()
    elif b64_key:
        try: pem = base64.b64decode(b64_key)
        except Exception: pem = b64_key.encode()
    else:
        raise FileNotFoundError(f"No private key. Set KALSHI_PRIVATE_KEY or place at '{file_path}'.")
    return serialization.load_pem_private_key(pem, password=None, backend=default_backend())

prod_key_id = os.environ.get("KALSHI_API_KEY_ID", "c3204983-77fc-491b-99f7-136600698178")
prod_private_key = load_private_key(
    b64_key=os.environ.get("KALSHI_PRIVATE_KEY", ""),
    file_path=os.environ.get("KALSHI_PRIVATE_KEY_PATH", "Lisa_Kalshi.txt")
)

# for prod
prod_api_base = "https://api.elections.kalshi.com/trade-api/v2"

## if wanting to test in prod:
exchange_client = ExchangeClient(exchange_api_base=prod_api_base, key_id = prod_key_id, private_key = prod_private_key)

# first we will check on the exchange status to confirm you are properly connected...
print(exchange_client.get_exchange_status())

###### BIGQUERY SETUP

import pandas as pd
from datetime import datetime
import pytz
from google.cloud import bigquery
import smtplib
from email.mime.text import MIMEText

# =========================
# ALERTING
# =========================
_ALERTS = []
ALERT_EMAIL_FROM = os.environ.get("ALERT_EMAIL_FROM", "")
ALERT_EMAIL_PASSWORD = os.environ.get("ALERT_EMAIL_PASSWORD", "")
ALERT_EMAIL_TO = os.environ.get("ALERT_EMAIL_TO", "")


def alert(category: str, message: str, context: dict = None):
    entry = {
        "timestamp": datetime.now(pytz.timezone('US/Central')).strftime('%Y-%m-%d %H:%M:%S'),
        "category": category,
        "message": message,
        **(context or {}),
    }
    _ALERTS.append(entry)
    ctx_str = f" | {context}" if context else ""
    print(f"  ⚡ ALERT [{category}]: {message}{ctx_str}")


def send_alert_notification():
    if not ALERT_EMAIL_FROM or not ALERT_EMAIL_PASSWORD or not ALERT_EMAIL_TO:
        return
    if len(_ALERTS) == 0:
        return
    cats = {}
    for a in _ALERTS:
        c = a["category"]
        cats[c] = cats.get(c, 0) + 1
    lines = [f"KXHIGH Alerts: {len(_ALERTS)} total"]
    for cat, count in sorted(cats.items(), key=lambda x: -x[1]):
        lines.append(f"  {cat}: {count}")
    lines.append("")
    for a in _ALERTS[:8]:
        lines.append(f"[{a['category']}] {a['message']}")
    if len(_ALERTS) > 8:
        lines.append(f"... +{len(_ALERTS) - 8} more")
    body = "\n".join(lines)

    # Carrier SMS gateways silently drop long messages — truncate for SMS recipients
    SMS_GATEWAYS = ("tmomail.net", "vtext.com", "txt.att.net", "messaging.sprintpcs.com", "msg.fi.google.com")
    recipients = [r.strip() for r in ALERT_EMAIL_TO.split(",") if r.strip()]

    for recipient in recipients:
        try:
            is_sms = any(gw in recipient.lower() for gw in SMS_GATEWAYS)
            send_body = body[:300] if is_sms else body

            msg = MIMEText(send_body)
            msg["Subject"] = f"HIGH TEMP Bot: {len(_ALERTS)} alerts" if not is_sms else ""
            msg["From"] = ALERT_EMAIL_FROM
            msg["To"] = recipient

            with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=15) as server:
                server.login(ALERT_EMAIL_FROM, ALERT_EMAIL_PASSWORD)
                server.sendmail(ALERT_EMAIL_FROM, [recipient], msg.as_string())
        except Exception as e:
            print(f"  ⚠️ Alert to {recipient} failed: {e}")

    print(f"  ✓ Alert notification sent to {len(recipients)} recipient(s)")


def upload_alerts_to_bq():
    if bq_client is None or len(_ALERTS) == 0:
        return
    try:
        df_alerts = pd.DataFrame(_ALERTS)
        table_id = f"{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE_PREFIX}alerts"
        job_config = bigquery.LoadJobConfig(write_disposition="WRITE_APPEND", autodetect=True)
        job = bq_client.load_table_from_dataframe(df_alerts, table_id, job_config=job_config)
        job.result()
        print(f"  ✓ Uploaded {len(df_alerts)} alerts to {table_id}")
    except Exception as e:
        print(f"  ⚠️ Alert upload failed: {e}")

BQ_PROJECT = os.environ.get("GCP_PROJECT_ID", "elite-contact-446323-q7")
BQ_DATASET = os.environ.get("GCP_DATASET_ID", "Kalshi")
BQ_TABLE_PREFIX = "KXHIGH_"

# Authenticate
if not os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"):
    # Check for google_credentials.json written by GitHub Actions
    if os.path.exists("google_credentials.json") and os.path.getsize("google_credentials.json") > 10:
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "google_credentials.json"

try:
    bq_client = bigquery.Client(project=BQ_PROJECT)
    print(f"BigQuery connected: {BQ_PROJECT}.{BQ_DATASET}")
except Exception as e:
    alert("BIGQUERY_INIT_FAILED", f"BQ init failed (non-fatal): {e}")
    print(f"BigQuery init failed (non-fatal): {e}")
    bq_client = None

def write_to_bq(df, table_name, write_disposition="WRITE_APPEND"):
    """Upload DataFrame to BigQuery. Non-fatal on failure."""
    if bq_client is None or df is None or len(df) == 0:
        return
    table_id = f"{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE_PREFIX}{table_name}"
    try:
        job_config = bigquery.LoadJobConfig(write_disposition=write_disposition, autodetect=True)
        job = bq_client.load_table_from_dataframe(df, table_id, job_config=job_config)
        job.result()
        print(f"  BQ: {table_id} → {bq_client.get_table(table_id).num_rows} rows")
    except Exception as e:
        print(f"  BQ error (non-fatal): {e}")

# Collector for orders placed during this run
all_order_records = []

# Determine if current time in Central Time is after 2 PM
central_time = datetime.now(pytz.timezone('US/Central'))
variable = 1 if central_time.hour >= 14 and central_time.hour < 23 else 0

# Define the cities and their coordinates for NWS
cities = {
    "Austin": (30.18304, -97.67987),
    "Miami": (25.79056, -80.31639),
    "Houston": (29.64542, -95.27889),
    "Denver": (39.84658, -104.65622),
    "New York City": (40.78333, -73.96667),
    "Philadelphia": (39.87327, -75.22678),
    "Chicago": (41.78417, -87.75528),
    "Los Angeles": (33.94250, -118.40806),
    "Atlanta": (33.64068, -84.42694),
    "Washington DC": (38.85208, -77.03772),
    "Phoenix": (33.43722, -112.00778),
    "Dallas": (32.89681, -97.03781),
    "Las Vegas": (36.08000, -115.15222),
    "Oklahoma City": (35.39306, -97.60056),
    "Seattle": (47.44889, -122.30917),
    "San Francisco": (37.61961, -122.36558),
    "San Antonio": (29.53389, -98.46917),
    "Minneapolis": (44.88306, -93.22889),
    "New Orleans": (29.99333, -90.25806),
}

def get_accuweather_forecast(coords):
    try:
        api_key = "lEl0lfAft6PncVXwatr92Y2YjGJL5YKs"  # Replace with your actual API key
        lat, lon = coords

        # Fetch location key from AccuWeather API using geoposition search
        location_url = f"http://dataservice.accuweather.com/locations/v1/cities/geoposition/search"
        location_params = {
            "apikey": api_key,
            "q": f"{lat},{lon}"  # Format coordinates for the API
        }

        location_response = requests.get(location_url, params=location_params)
        location_response.raise_for_status()  # Raise an exception for bad status codes
        location_key = location_response.json()["Key"]  # Extract location key

        # Fetch 5-day forecast for the location key
        forecast_url = f"http://dataservice.accuweather.com/forecasts/v1/daily/5day/{location_key}"
        forecast_params = {
            "apikey": api_key,
            "metric": "false"  # Use Fahrenheit
        }

        forecast_response = requests.get(forecast_url, params=forecast_params)
        forecast_response.raise_for_status()
        forecast = forecast_response.json()

        # Get today or tomorrow's forecast based on 'variable'
        tomorrow_forecast = forecast["DailyForecasts"][variable]
        high_temp = tomorrow_forecast["Temperature"]["Maximum"]["Value"]

        return int(high_temp)

    except Exception as e:
        alert("FORECAST_FAILED", f"AccuWeather failed for {coords}: {e}",
              {"source": "accuweather"})
        print(f"Error fetching AccuWeather forecast for {coords}: {e}")
        return "N/A"

# Function to get forecast from NWS
def get_nws_forecast(lat, lon):
    try:
        # Construct NWS API URL
        base_url = f"https://api.weather.gov/points/{lat},{lon}"
        grid_response = requests.get(base_url)
        grid_response.raise_for_status()
        forecast_url = grid_response.json()['properties']['forecast']

        forecast_response = requests.get(forecast_url)
        forecast_response.raise_for_status()
        periods = forecast_response.json()['properties']['periods']

        # Get tomorrow's date
        # tomorrow = (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d')
        dayswitch = (central_time + timedelta(days=variable)).strftime('%Y-%m-%d') #pulling tomorrow or today

        for period in periods:
            if dayswitch in period['startTime'] and "day" in period['name'].lower():
                return period['temperature']  # NWS temperatures are already in Fahrenheit

        return "N/A"
    except Exception as e:
        alert("FORECAST_FAILED", f"NWS failed for {lat},{lon}: {e}",
              {"source": "nws"})
        print(f"Error fetching NWS forecast for {lat}, {lon}: {e}")
        return "N/A"

# Iterate through cities and fetch data
# def get_weatherunderground_forecast(lat, lon):
def get_weatherunderground_forecast(city, coords):
    API_KEY = "a828c2a178844147a8c2a17884a147a5"  # Weather Underground API Key
    lat, lon = coords  # Extract latitude and longitude from coords
    URL = f"https://api.weather.com/v3/wx/forecast/daily/5day?apiKey={API_KEY}&geocode={lat},{lon}&format=json&units=e&language=en-US"

    # Send request
    response = requests.get(URL)

    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()

        # Try extracting the correct temperature field
        if "temperatureMax" in data:
            # Use variable to get today or tomorrow's forecast
            today_high = data["temperatureMax"][variable]
            return today_high
        else:
            alert("FORECAST_FAILED", f"WU missing temperatureMax for {city}",
                  {"source": "weather_underground"})
            print(f"Error: 'temperatureMax' field not found in API response for {city}.")
            return "N/A"  # Return "N/A" if temperature data is not found
    else:
        alert("FORECAST_FAILED", f"WU HTTP {response.status_code} for {city}",
              {"source": "weather_underground", "status_code": response.status_code})
        print(f"Failed to fetch data for {city}. Status code: {response.status_code}, Message: {response.text}")
        return "N/A"  # Return "N/A" if request fails

# Get current run date in Central Time
central_tz = pytz.timezone("US/Central")
run_date = datetime.now(central_tz).strftime('%Y-%m-%d %H:%M:%S')

# Create the DataFrame
forecast_data = []

for city, coords in cities.items():
    nws_temp = get_nws_forecast(*coords)
    # AccuWeather removed — API key expired (401 on all cities since March 2026)
    weatherundergroud_temp = get_weatherunderground_forecast(city, coords)

    forecast_data.append({
        "City": city,
        "Forecast Date": (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime('%Y-%m-%d'),
        "Run Date": run_date,
        "Weather Underground": weatherundergroud_temp,
        "NWS": nws_temp
    })

forecast_table = pd.DataFrame(forecast_data)

# Calculate standard deviation and range for each city (2 sources: NWS + Weather Underground)
forecast_table[["Weather Underground", "NWS"]] = forecast_table[["Weather Underground", "NWS"]].apply(pd.to_numeric, errors='coerce')
forecast_table["Average"] = forecast_table[["Weather Underground", "NWS"]].mean(axis=1)
forecast_table["Standard Deviation"] = forecast_table[["Weather Underground", "NWS"]].std(axis=1)
forecast_table["Highest Minus Lowest"] = forecast_table[["Weather Underground", "NWS"]].max(axis=1) - forecast_table[["Weather Underground", "NWS"]].min(axis=1)

# Display the DataFrame
forecast_table

##### GET CONDITIONS FROM NWS

import requests
import pandas as pd
from datetime import datetime, timedelta

# City data with their corresponding location information for NWS API
cities = {
    "Austin": {"lat": 30.18304, "lon": -97.67987},
    "Miami": {"lat": 25.79056, "lon": -80.31639},
    "Houston": {"lat": 29.64542, "lon": -95.27889},
    "Denver": {"lat": 39.84658, "lon": -104.65622},
    "New York City": {"lat": 40.78333, "lon": -73.96667},
    "Philadelphia": {"lat": 39.87327, "lon": -75.22678},
    "Chicago": {"lat": 41.78417, "lon": -87.75528},
    "Los Angeles": {"lat": 33.94250, "lon": -118.40806},
    "Atlanta": {"lat": 33.64068, "lon": -84.42694},
    "Washington DC": {"lat": 38.85208, "lon": -77.03772},
    "Phoenix": {"lat": 33.43722, "lon": -112.00778},
    "Dallas": {"lat": 32.89681, "lon": -97.03781},
    "Las Vegas": {"lat": 36.08000, "lon": -115.15222},
    "Oklahoma City": {"lat": 35.39306, "lon": -97.60056},
    "Seattle": {"lat": 47.44889, "lon": -122.30917},
    "San Francisco": {"lat": 37.61961, "lon": -122.36558},
    "San Antonio": {"lat": 29.53389, "lon": -98.46917},
    "Minneapolis": {"lat": 44.88306, "lon": -93.22889},
    "New Orleans": {"lat": 29.99333, "lon": -90.25806},
}

# Prepare the date for today
today = datetime.now(pytz.timezone('US/Central')).strftime("%Y-%m-%d")

# Function to fetch weather conditions from NWS
def fetch_nws_conditions(city):
    url = f"https://api.weather.gov/points/{city['lat']},{city['lon']}"
    response = requests.get(url)
    if response.status_code == 200:
        grid_data = response.json()
        forecast_url = grid_data['properties']['forecast']
        forecast_response = requests.get(forecast_url)
        if forecast_response.status_code == 200:
            forecast_data = forecast_response.json()
            # print(forecast_data['properties']['periods'])
            target_date = (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d")

            for period in forecast_data['properties']['periods']:
                # print(period)
                if target_date in period['startTime']:
                    return period['detailedForecast'], period['shortForecast']
    return None, None

# Collect forecast conditions
forecast_conditions = []
for city_name, city_coords in cities.items():
    nws_detailed, nws_short = fetch_nws_conditions(city_coords)
    forecast_conditions.append({
        "City": city_name,
        "NWS Detailed Conditions": nws_detailed,
        "NWS Short Conditions": nws_short
    })

# Create a DataFrame
forecast_conditions_table = pd.DataFrame(forecast_conditions)

forecast_table = pd.merge(forecast_table, forecast_conditions_table, on='City', how='inner')
forecast_table

############# GET MIDNIGHT TEMPS FROM NWS

import requests
from datetime import datetime, timedelta, date
import re
import pandas as pd

# Function to fetch the forecast at midnight through NWS
def fetch_midnight_forecast(coords):
    # Get the grid points URL for the location
    url = f"https://api.weather.gov/points/{coords['lat']},{coords['lon']}"
    response = requests.get(url)
    if response.status_code == 200:
        grid_data = response.json()
        forecast_url = grid_data['properties']['forecastHourly']

        # Fetch hourly forecast for midnight
        midnight_temp = None
        hourly_response = requests.get(forecast_url)
        if hourly_response.status_code == 200:
            hourly_data = hourly_response.json()
            for period in hourly_data['properties']['periods']:
                # Fix invalid ISO format by ensuring proper timezone formatting
                start_time = re.sub(r"([-+]\d{2}):(\d{1})$", r"\1:0\2", period['startTime'])
                # forecast_time = datetime.fromisoformat(start_time)
                forecast_time = datetime.fromisoformat(start_time).astimezone(pytz.timezone('US/Central'))  # Or your desired timezone
                # print((datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d"))
                # print('forecast_time.date() =', forecast_time.date())
                if forecast_time.hour == 0 and forecast_time.minute == 0 and forecast_time.date() == datetime.now(pytz.timezone('US/Central')).date() + timedelta(days=variable):
                # if forecast_time.date() == (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d"):
                  # print(datetime.now(pytz.timezone('US/Central')).date() + timedelta(days=variable))
                  # print(forecast_time.date())
                  midnight_temp = period['temperature']
                  break
        return midnight_temp
    else:
        alert("FORECAST_MIDNIGHT_FAILED", f"NWS grid fetch failed: HTTP {response.status_code}",
              {"url": url})
        print(f"Failed to fetch grid data. Status code: {response.status_code}, URL: {url}")
    return None

# Coordinates for cities
cities = {
    "Austin": {"lat": 30.18304, "lon": -97.67987},
    "Miami": {"lat": 25.79056, "lon": -80.31639},
    "Houston": {"lat": 29.64542, "lon": -95.27889},
    "Denver": {"lat": 39.84658, "lon": -104.65622},
    "New York City": {"lat": 40.78333, "lon": -73.96667},
    "Philadelphia": {"lat": 39.87327, "lon": -75.22678},
    "Chicago": {"lat": 41.78417, "lon": -87.75528},
    "Los Angeles": {"lat": 33.94250, "lon": -118.40806},
    "Atlanta": {"lat": 33.64068, "lon": -84.42694},
    "Washington DC": {"lat": 38.85208, "lon": -77.03772},
    "Phoenix": {"lat": 33.43722, "lon": -112.00778},
    "Dallas": {"lat": 32.89681, "lon": -97.03781},
    "Las Vegas": {"lat": 36.08000, "lon": -115.15222},
    "Oklahoma City": {"lat": 35.39306, "lon": -97.60056},
    "Seattle": {"lat": 47.44889, "lon": -122.30917},
    "San Francisco": {"lat": 37.61961, "lon": -122.36558},
    "San Antonio": {"lat": 29.53389, "lon": -98.46917},
    "Minneapolis": {"lat": 44.88306, "lon": -93.22889},
    "New Orleans": {"lat": 29.99333, "lon": -90.25806},
}

# Fetch forecasts for all cities
forecasts = []
for city, coords in cities.items():
    midnight_forecast = fetch_midnight_forecast(coords)
    forecasts.append({
        "City": city,
        "Midnight Temperature": midnight_forecast
    })

# Create a DataFrame
forecast_df = pd.DataFrame(forecasts)

forecast_table = pd.merge(forecast_table, forecast_df, on='City', how='inner')

if variable == 0:
  forecast_table['concat'] = forecast_table['City'] + forecast_table['Forecast Date'] + 'Day'
if variable == 1:
  forecast_table['concat'] = forecast_table['City'] + forecast_table['Forecast Date'] + 'Night'

forecast_table

forecast_table = forecast_table.fillna("")

########## DROP ANY WHERE MIDNIGHT TEMP IS WITHIN 5 DEGREES OF TOMORROW'S HIGH

if variable == 1:
  # Ensure 'Average' and 'Midnight Temperature' columns are numeric
  forecast_table['Average'] = pd.to_numeric(forecast_table['Average'], errors='coerce')
  forecast_table['Midnight Temperature'] = pd.to_numeric(forecast_table['Midnight Temperature'], errors='coerce')

  forecast_table = forecast_table[abs(forecast_table['Average'] - forecast_table['Midnight Temperature']) >= 4.5]
forecast_table

########### INPUT EVENT TICKERS, CITIES, HIGHEST NO PRICES, HISTORICAL VARIANCE

# Determine if current time in Central Time is after 2 PM
central_time = datetime.now(pytz.timezone('US/Central'))
variable = 1 if central_time.hour >= 14 else 0

day = central_time + timedelta(days=variable) #pulling tomorrow or today in central time
month = day.strftime("%b").upper()
day = day.strftime("%d")
# print(day)

event_ticker1 = ['KXHIGHCHI-26' + month + day, 'Chicago', 56, 1.7]
event_ticker2 = ['KXHIGHNY-26' + month + day, 'New York City', 46, 1.5]
event_ticker3 = ['KXHIGHDEN-26' + month + day, 'Denver', 57, 2.4]
event_ticker4 = ['KXHIGHPHIL-26' + month + day, 'Philadelphia', 52, 1.6]
event_ticker5 = ['KXHIGHAUS-26' + month + day, 'Austin', 63, 1.7]
event_ticker6 = ['KXHIGHMIA-26' + month + day, 'Miami', 43, 1.1]
event_ticker7 = ['KXHIGHTHOU-26' + month + day, 'Houston', 59, 2.0]
event_ticker8 = ['KXHIGHLAX-26' + month + day, 'Los Angeles', 58, 2.0]
event_ticker9 = ['KXHIGHTATL-26' + month + day, 'Atlanta', 55, 1.5]
event_ticker10 = ['KXHIGHTDC-26' + month + day, 'Washington DC', 50, 1.5]
event_ticker11 = ['KXHIGHTPHX-26' + month + day, 'Phoenix', 55, 1.5]
event_ticker12 = ['KXHIGHTDAL-26' + month + day, 'Dallas', 55, 1.5]
event_ticker13 = ['KXHIGHTLV-26' + month + day, 'Las Vegas', 55, 1.5]
event_ticker14 = ['KXHIGHTOKC-26' + month + day, 'Oklahoma City', 55, 1.5]
event_ticker15 = ['KXHIGHTSEA-26' + month + day, 'Seattle', 50, 1.5]
event_ticker16 = ['KXHIGHTSFO-26' + month + day, 'San Francisco', 50, 1.5]
event_ticker17 = ['KXHIGHTSATX-26' + month + day, 'San Antonio', 55, 1.5]
event_ticker18 = ['KXHIGHTMIN-26' + month + day, 'Minneapolis', 55, 1.5]
event_ticker19 = ['KXHIGHTNOLA-26' + month + day, 'New Orleans', 55, 1.5]

############ PULL MARKETS
all_event_tickers = [event_ticker1, event_ticker2, event_ticker3, event_ticker4, event_ticker5, event_ticker6, event_ticker7, event_ticker8, event_ticker9, event_ticker10, event_ticker11, event_ticker12, event_ticker13, event_ticker14, event_ticker15, event_ticker16, event_ticker17, event_ticker18, event_ticker19]
event_tickers = pd.DataFrame(all_event_tickers, columns=['Ticker', 'City', 'hi_no_price', 'var'])
event_tickers['var_sqrt'] = np.sqrt(event_tickers['var'])
markets_table = pd.DataFrame(columns=['event_ticker', 'market_ticker', 'market_ticker_prev', 'City', 'low_range', 'high_range', 'hi_no_price'])

for event_ticker in event_tickers['Ticker']:
  event_params = {'event_ticker': event_ticker}
  print(event_ticker)
  event_response = exchange_client.get_event(**event_params)

  for market in event_response['markets']:
      city = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'City'].iloc[0]
      hi_no_price = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'hi_no_price'].iloc[0]
      historical_variance = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'var'].iloc[0]
      historical_variance_sqrt = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'var_sqrt'].iloc[0]
      if "-B" in market['ticker']:
        match = re.search(r"-B(\d+(\.\d+)?)", market['ticker'])
        if match:
          number_after_b = float(match.group(1))
          low_range = number_after_b - 1
          high_range = number_after_b + 1
          markets_table = pd.concat([markets_table, pd.DataFrame([[event_ticker, market['ticker'], city, low_range, high_range, hi_no_price, historical_variance, historical_variance_sqrt]], columns=['event_ticker', 'market_ticker', 'City', 'low_range', 'high_range', 'hi_no_price', 'var', 'var_sqrt'])], ignore_index=True)

      if "-T" in market['ticker']:
        match = re.search(r"-T(\d+(\.\d+)?)", market['ticker'])
        if match:
          number_after_t = float(match.group(1))

          low_range = 0
          high_range = number_after_t - 0.5
          markets_table = pd.concat([markets_table, pd.DataFrame([[event_ticker, market['ticker'], city, low_range, high_range, hi_no_price, historical_variance, historical_variance_sqrt]], columns=['event_ticker', 'market_ticker', 'City', 'low_range', 'high_range', 'hi_no_price', 'var', 'var_sqrt'])], ignore_index=True)

markets_table['market_ticker_prev'] = markets_table['market_ticker'].shift(1)

for index, row in markets_table.iterrows():
  # Skip the first row to avoid the None value in 'market_ticker_prev'
  if index == 0:
    continue
  if "-B" in row['market_ticker_prev'] and "-T" in row['market_ticker']:
    markets_table.loc[index, 'low_range'] = row['high_range'] + 1
    markets_table.loc[index, 'high_range'] = 150

markets_table.drop(columns=['market_ticker_prev'], inplace=True)
markets_table

##### COMBINE FORECAST AND MARKET TABLES, AND CALCULATE PROBABILITIES
from scipy.stats import norm

combined_table = pd.merge(forecast_table, markets_table, on='City', how='inner')

# Convert 'Average' and 'Standard Deviation' columns to numeric, handling errors
combined_table['Average'] = pd.to_numeric(combined_table['Average'], errors='coerce')
combined_table['Standard Deviation'] = pd.to_numeric(combined_table['Standard Deviation'], errors='coerce')

# City-specific floor std dev (from v1 bot calibration, 1816 observations)
# Model uses: max(inter_source_std, city_floor_std)
# This prevents 0 std when all sources agree (which gives 100%/0% extremes)
CITY_FLOOR_STD = {
    "Austin": 1.2, "Miami": 1.0, "Houston": 1.9, "Denver": 1.4,
    "New York City": 1.2, "Philadelphia": 1.3, "Chicago": 1.3, "Los Angeles": 1.2,
    "Atlanta": 1.2, "Washington DC": 1.3, "Phoenix": 1.1, "Dallas": 1.2,
    "Las Vegas": 1.1, "Oklahoma City": 1.4, "Seattle": 1.2, "San Francisco": 1.2,
    "San Antonio": 1.2, "Minneapolis": 1.4, "New Orleans": 1.2,
}
combined_table['City Floor Std'] = combined_table['City'].map(CITY_FLOOR_STD).fillna(1.2)
combined_table['Standard Deviation'] = combined_table[['Standard Deviation', 'City Floor Std']].max(axis=1)
combined_table['Standard Deviation'] = combined_table['Standard Deviation'].replace({0: 1.2, np.nan: 1.2})

# Ensure 'high_range' and 'low_range' are numeric
combined_table['high_range'] = pd.to_numeric(combined_table['high_range'], errors='coerce')
combined_table['low_range'] = pd.to_numeric(combined_table['low_range'], errors='coerce')

combined_table['yes_probability'] = norm.cdf(combined_table['high_range'], loc=combined_table['Average'], scale=combined_table['Standard Deviation']) - norm.cdf(combined_table['low_range'], loc=combined_table['Average'], scale=combined_table['Standard Deviation'])
combined_table['yes_probability'] = combined_table['yes_probability'].round(2)
combined_table['fair_no_price'] = 1 - combined_table['yes_probability']
combined_table

####PULL ORDER BOOK OF MARKETS

combined_table['no_highest_bid'] = ''
combined_table['no_lowest_offer'] = ''
combined_table['no_orderbook'] = ''
combined_table['yes_orderbook'] = ''

for index, row in combined_table.iterrows():
  market_ticker = row['market_ticker']
  market_history_params = {'ticker':market_ticker,
                            'depth': 3
                                }
  try:
    orderbook_response = exchange_client.get_orderbook(**market_history_params)
  except Exception as e:
    alert("ORDERBOOK_ERROR", f"Fetch failed for {market_ticker}: {e}",
          {"ticker": market_ticker})
    continue

  # Parse orderbook — handle both old format (orderbook.no/yes in cents)
  # and new format (orderbook_fp.no_dollars/yes_dollars in dollar strings)
  no_levels = []  # list of [price_cents, quantity]
  yes_levels = []

  if 'orderbook_fp' in orderbook_response:
    ob_fp = orderbook_response['orderbook_fp']
    # no_dollars: [['0.8200', '300.00'], ...] → price in dollars, convert to cents
    for level in ob_fp.get('no_dollars', []):
      no_levels.append([int(round(float(level[0]) * 100)), int(float(level[1]))])
    for level in ob_fp.get('yes_dollars', []):
      yes_levels.append([int(round(float(level[0]) * 100)), int(float(level[1]))])
  elif 'orderbook' in orderbook_response:
    ob = orderbook_response['orderbook']
    no_levels = ob.get('no', [])
    yes_levels = ob.get('yes', [])
  else:
    # Response itself might be the orderbook
    no_levels = orderbook_response.get('no', [])
    yes_levels = orderbook_response.get('yes', [])

  if no_levels and len(no_levels) > 0:
    combined_table.loc[index, 'no_highest_bid'] = str(no_levels[-1][0])

  if yes_levels and len(yes_levels) > 0:
    combined_table.loc[index, 'no_lowest_offer'] = str(100 - yes_levels[-1][0])

  combined_table.loc[index, 'no_orderbook'] = str(no_levels)
  combined_table.loc[index, 'yes_orderbook'] = str(yes_levels)

combined_table

#If you need to access the detailed orderbook data later, you can use eval() or ast.literal_eval() (safer) to convert the string back to a list of lists:
#import ast
    # orderbook_data = ast.literal_eval(markets_table.loc[index, 'orderbook'])

######### ACTUALS VS FORECAST, FOR BETTING THE HIGH END

# Define column names
columns = ["Austin", "Miami", "Denver", "Houston", "Philadelphia", "New York City", "Chicago", "Los Angeles"]

# Define row indices
rows = ["5", "4", "3", "2", "1", "0", "-1", "-2", "-3", "-4", "-5"]

# Define data values (converted from percentages to decimals)
data = [
    [0.0270, 0.0256, 0.1290, 0.0000, 0.0000, 0.0270, 0.0333, 0.0667],
    [0.0270, 0.0000, 0.0000, 0.0000, 0.0263, 0.0000, 0.0333, 0.0000],
    [0.0811, 0.0000, 0.0645, 0.1613, 0.1579, 0.1081, 0.1333, 0.0000],
    [0.2432, 0.2308, 0.1290, 0.1935, 0.1053, 0.1622, 0.2333, 0.0000],
    [0.1892, 0.2051, 0.1935, 0.1935, 0.2895, 0.2162, 0.3333, 0.2667],
    [0.1351, 0.2821, 0.1935, 0.0645, 0.1053, 0.2162, 0.0667, 0.2667],
    [0.1892, 0.1282, 0.0645, 0.2258, 0.1053, 0.0811, 0.1000, 0.1333],
    [0.0270, 0.0769, 0.0645, 0.0968, 0.1053, 0.1622, 0.0000, 0.1333],
    [0.0541, 0.0256, 0.0968, 0.0323, 0.0526, 0.0000, 0.0000, 0.0667],
    [0.0000, 0.0000, 0.0323, 0.0000, 0.0263, 0.0000, 0.0333, 0.0000],
    [0.0270, 0.0256, 0.0323, 0.0323, 0.0263, 0.0270, 0.0333, 0.0667]
]

# Create DataFrame
actuals_vs_forecast_variation = pd.DataFrame(data, columns=columns, index=rows)
actuals_vs_forecast_variation = actuals_vs_forecast_variation.transpose()
actuals_vs_forecast_variation['City'] = actuals_vs_forecast_variation.index
print(actuals_vs_forecast_variation.index)
actuals_vs_forecast_variation

##### CALCULATE HIGH RANGE BIDS

x = combined_table[combined_table['high_range'] == 150]

y = pd.DataFrame(columns=['City', 'low_range', 'Average', 'forecast_variation_vs_high_end', 'bid_price'])
forcast_data = round(x['low_range'] - x['Average'])
y['forecast_variation_vs_high_end'] = forcast_data
y['City'] = x['City']
y['low_range'] = x['low_range']
y['Average'] = x['Average']
y = pd.merge(y, actuals_vs_forecast_variation, on='City', how='inner')
# Rebuild chart_end_index from merged y (only cities with historical data)
chart_end_index = [int(v) for v in y['forecast_variation_vs_high_end'].tolist()]
filtered_data = [y[str(col)].tolist() for col in range(5, -6, -1)]

# calculate bid_price for each city (only cities in actuals table)
percentage_data = list()
for index, value in enumerate(chart_end_index):
  if value > 5:
    value = 5
  if value < -5:
    value = -5
  city_data = [x[index] for x in filtered_data]
  end_index = 5 - value + 1
  # print(value)
  values_to_sum = city_data[0:end_index]
  percentage_data.append(sum(values_to_sum))

y['bid_price'] = [1 - x for x in percentage_data]
y

for index, row in combined_table.iterrows():
  if row['high_range'] == 150:
    # Get the bid_price for the current city from the y DataFrame (if available)
    try:
      bid_price = y.loc[y['City'] == row['City'], 'bid_price'].iloc[0]
      combined_table.loc[index, 'hi_no_price'] = bid_price * 100 - 15 #20 cent buffer
    except (IndexError, KeyError):
      pass  # New cities without historical data keep their default hi_no_price

combined_table

####### WRITE MARKET SNAPSHOT TO BIGQUERY

print("\nWriting market snapshot to BigQuery...")
write_to_bq(combined_table, "market_snapshot", "WRITE_APPEND")

combined_table = combined_table.fillna("")

####### DELETE EXISTING ORDERS

for market_ticker in combined_table['market_ticker']:
  order_params = {'ticker':market_ticker}
  order_response = exchange_client.get_orders(**order_params)

  for i in range(len(order_response['orders'])):
    order_id = order_response['orders'][i]['order_id']
    status = order_response['orders'][i]['status']
    order_id = {'order_id':order_id}
    if order_id is not None and status == 'resting':
      exchange_client.cancel_order(**order_id)

############## PULL CURRENT POSITIONS
for market_ticker in combined_table['market_ticker']:
  positions_params = {'ticker': market_ticker}
  current_position = exchange_client.get_positions(**positions_params)
  # print(current_position)
  if 'market_positions' in current_position and current_position['market_positions']:
    positions = pd.DataFrame(current_position['market_positions'])

    if 'position' in positions.columns:
      live_positions = positions[positions['position'] != 0]
      if not live_positions.empty:
        row_index = combined_table.index[combined_table['market_ticker'] == market_ticker].tolist()[0]
        combined_table.loc[row_index, 'position'] = abs(live_positions['position'].iloc[0])
  if 'position' not in combined_table.columns:
    combined_table['position'] = 0
  combined_table['position'] = combined_table['position'].fillna(0).astype(int)
  combined_table['resting_order_count'] = 0

combined_table

##### PLACE ORDERS

######### BETTING INPUTS
increment = 2
increment1 = 5
price_count = list(range(0, 8))
starting_contracts = 15

max_contracts = 200
max_contracts1 = 200
market_cutoff_probability = .2
# print('hi')
#################################################### CANCEL CONTRACT TIME
from datetime import datetime, timedelta
import pytz

def get_unix_time_for_tomorrow(hour: int, minute: int, timezone: str = 'US/Central') -> int:
    """
    Calculate the Unix time for a specific hour and minute tomorrow in the given timezone.

    :param hour: Hour of the time (24-hour format).
    :param minute: Minute of the time.
    :param timezone: Timezone (default is 'US/Central').
    :return: Unix timestamp for the specified time tomorrow.
    """
    # Define the timezone
    tz = pytz.timezone(timezone)

    # Get the current date and time in the specified timezone
    now = datetime.now(tz)

    # Calculate tomorrow's date at the specified time
    target_time = tz.localize(
        datetime(year=now.year, month=now.month, day=now.day, hour=hour, minute=minute) + timedelta(days=variable)
    )

    # Convert to Unix time
    return int(target_time.timestamp())

########## BUY CALCULATIONS
orders_placed = 0
_diag_printed = False
for index, row in combined_table.iterrows():
  ticker = row['market_ticker']
  is_tail = "-T" in ticker and row['high_range'] == 150
  yes_prob = row['yes_probability']
  no_offer = row['no_lowest_offer']
  no_bid = row['no_highest_bid']
  hi_no = row['hi_no_price']

  # Diagnostic: show every market's state
  print(f"\n  {ticker}: P(yes)={yes_prob:.2f} hi_no={hi_no} no_bid={no_bid} no_offer={no_offer} tail={is_tail}")

  # Filter 0: check if market is still open for trading
  try:
    _mkt_resp = exchange_client.get_market(ticker=ticker)
    _mkt_status = _mkt_resp.get('market', {}).get('status', '')
    if _mkt_status not in ('open', 'active', ''):
      print(f"    SKIP: market status '{_mkt_status}' (closed/settled)")
      continue
  except:
    pass  # If check fails, try to place orders anyway

  # Filter 1: probability cutoff
  if not (yes_prob > market_cutoff_probability or is_tail):
    print(f"    SKIP: P(yes)={yes_prob:.2f} <= {market_cutoff_probability} cutoff")
    continue

  # Filter 2: skip low-end tails
  if "-T" in ticker and not is_tail:
    print(f"    SKIP: low-end tail (not traded)")
    continue

  # Filter 3: need orderbook data
  if no_offer == '' or no_bid == '':
    print(f"    SKIP: no orderbook data")
    continue

  i1 = 0
  level_orders = 0
  for i in price_count:
    if "-T" not in ticker:
      bid_price = max(hi_no - i * increment, 1)
    if is_tail:
      bid_price = max(hi_no - i * increment1, 1)

    # Show first level diagnostics
    if i == 0:
      print(f"    Level 0: bid={bid_price:.0f} vs no_offer={int(no_offer)} no_bid={int(no_bid)} (need bid<offer AND bid<bid-3)")

    if not (bid_price < int(no_offer)):
      if i == 0: print(f"    SKIP level 0: bid {bid_price:.0f} >= no_offer {int(no_offer)}")
      continue
    if not (bid_price < int(no_bid) - 3):
      if i == 0: print(f"    SKIP level 0: bid {bid_price:.0f} >= no_bid-3 ({int(no_bid)-3})")
      continue
    if not (max_contracts >= row['position'] + row['resting_order_count'] + starting_contracts + i * 10):
      if i == 0: print(f"    SKIP level 0: position cap")
      continue

    contracts = starting_contracts
    i1 = i1 + 1

    # Detect city abbreviation and cancel time — check longer abbreviations first
    abv = ''
    cancel_hour = 10
    cancel_minute = 5
    ticker_str = row['market_ticker']
    if 'THOU' in ticker_str: abv = 'THOU'; cancel_hour = 10
    elif 'SATX' in ticker_str: abv = 'SATX'; cancel_hour = 10
    elif 'TMIN' in ticker_str: abv = 'TMIN'; cancel_hour = 10
    elif 'NOLA' in ticker_str: abv = 'NOLA'; cancel_hour = 10
    elif 'CHI' in ticker_str: abv = 'CHI'; cancel_hour = 10
    elif 'AUS' in ticker_str: abv = 'AUS'; cancel_hour = 10
    elif 'HOU' in ticker_str: abv = 'HOU'; cancel_hour = 10
    elif 'DEN' in ticker_str: abv = 'DEN'; cancel_hour = 10
    elif 'NY-' in ticker_str: abv = 'NY-'; cancel_hour = 9
    elif 'PHI' in ticker_str: abv = 'PHI'; cancel_hour = 9
    elif 'MIA' in ticker_str: abv = 'MIA'; cancel_hour = 9
    elif 'LAX' in ticker_str: abv = 'LAX'; cancel_hour = 10
    elif 'ATL' in ticker_str: abv = 'ATL'; cancel_hour = 9
    elif 'TDC' in ticker_str: abv = 'TDC'; cancel_hour = 9
    elif 'PHX' in ticker_str: abv = 'PHX'; cancel_hour = 10
    elif 'DAL' in ticker_str: abv = 'DAL'; cancel_hour = 10
    elif 'TLV' in ticker_str: abv = 'TLV'; cancel_hour = 10
    elif 'OKC' in ticker_str: abv = 'OKC'; cancel_hour = 10
    elif 'SEA' in ticker_str: abv = 'SEA'; cancel_hour = 10
    elif 'SFO' in ticker_str: abv = 'SFO'; cancel_hour = 10

    central_time = datetime.now(pytz.timezone('US/Central'))
    if central_time.hour > 10 or central_time.hour < 6:
      cancel_hour = 1
      cancel_minute = 59

    client_oid = str(uuid.uuid4())
    exp_ts = get_unix_time_for_tomorrow(cancel_hour, cancel_minute)
    order_params = {'ticker':row['market_ticker'],
                      'client_order_id':client_oid,
                      'type':'limit',
                      'action':'buy',
                      'side':'no',
                      'count':contracts,
                      'no_price':int(bid_price),
                      'expiration_ts':exp_ts,
                      'post_only': True}
    try:
      _create_resp = exchange_client.create_order(**order_params)
      # Extract Kalshi's exchange-assigned order_id (needed for fills lineage)
      _kalshi_oid = ''
      if isinstance(_create_resp, dict):
          _kalshi_oid = (_create_resp.get('order') or {}).get('order_id', '') or ''
      time.sleep(0.1)  # Rate limit protection
      all_order_records.append({
          'city': row['City'], 'forecast_date': row['Forecast Date'], 'run_date': row['Run Date'],
          'market_ticker': row['market_ticker'], 'contracts': contracts, 'no_price': int(bid_price),
          'city_abv': abv, 'client_order_id': client_oid,
          'kalshi_order_id': _kalshi_oid,
          'expiration_ts': exp_ts,
          'created_at': central_time.strftime('%Y-%m-%d %H:%M:%S'),
      })
      row['resting_order_count'] = row['resting_order_count'] + contracts
      orders_placed += 1
      level_orders += 1
    except Exception as e:
      # Capture full error body — try multiple approaches for different exception types
      resp_body = ""
      # Approach 1: requests-style .response attribute
      if hasattr(e, 'response') and e.response is not None:
          try: resp_body = e.response.text[:300]
          except: pass
      # Approach 2: Kalshi client may store body in .args
      if not resp_body and hasattr(e, 'args') and len(e.args) > 1:
          resp_body = str(e.args[1])[:300] if e.args[1] else ""
      # Approach 3: some clients store as .body or .detail
      if not resp_body:
          for attr in ('body', 'detail', 'message', 'reason'):
              val = getattr(e, attr, None)
              if val:
                  resp_body = str(val)[:300]
                  break
      # Approach 4: repr() often shows more than str()
      if not resp_body and repr(e) != str(e):
          resp_body = repr(e)[:300]
      _err_str = f"{e} | {resp_body}" if resp_body else str(e)
      # Log exception type + all attributes on FIRST 400 error only (diagnostic)
      if '400' in str(e) and not _diag_printed:
          _diag_printed = True
          print(f"    [DIAG] Exception type: {type(e).__name__}, attrs: {[a for a in dir(e) if not a.startswith('_')]}")
          print(f"    [DIAG] args: {e.args}")
          print(f"    [DIAG] repr: {repr(e)[:500]}")
      if '400' in str(e):
          # Expected for closed/settled markets — log but don't alert (no text)
          print(f"    ⚠️ ORDER_400: {row['market_ticker']} no@{int(bid_price)}c ({_err_str[:150]})")
      elif '429' in str(e):
          alert("ORDER_429", f"Rate limited on {row['market_ticker']}",
                {"error": _err_str[:300]})
      else:
          alert("ORDER_FAILED", f"{row['market_ticker']} @{int(bid_price)}c: {_err_str[:200]}")
      print(f"    ✗ Order failed {row['market_ticker']} @{int(bid_price)}¢: {_err_str}")
      time.sleep(0.2)  # Extra pause after error
    if bid_price <= 1:
      break  # Don't place more orders at the 1¢ floor
  if level_orders > 0:
    print(f"    ✓ Placed {level_orders} orders")

print(f"\n{'='*60}")
print(f"TOTAL ORDERS PLACED: {orders_placed}")
print(f"{'='*60}")

# Write all orders to BigQuery
if all_order_records:
    df_orders = pd.DataFrame(all_order_records)
    df_orders['forecast_date'] = pd.to_datetime(df_orders['forecast_date'])
    df_orders['run_date'] = pd.to_datetime(df_orders['run_date'])
    df_orders['created_at'] = pd.to_datetime(df_orders['created_at'])
    write_to_bq(df_orders, "orders", "WRITE_APPEND")

print("\nTrading run complete.")

# =====================================================================
# END-OF-RUN ALERT SUMMARY
# =====================================================================
if _ALERTS:
    print(f"\n{'='*60}")
    print(f"⚡ ALERT SUMMARY: {len(_ALERTS)} alerts")
    print(f"{'='*60}")
    _cats = {}
    for _a in _ALERTS:
        _c = _a['category']
        _cats[_c] = _cats.get(_c, 0) + 1
    for _cat, _count in sorted(_cats.items(), key=lambda x: -x[1]):
        print(f"  {_cat}: {_count}")
    upload_alerts_to_bq()
    send_alert_notification()
    print(f"{'='*60}\n")
else:
    print("\n✓ No alerts — clean run")
