# -*- coding: utf-8 -*-
"""Jane Kalshi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liUXIpSNvE7XLnboLhxNgbILtO0nBIgR
"""

# Welcome to the Kalshi REST v2 Starter Code!

# pypi client: recommended for more advanced programmers
# import kalshi_python

# starter client: recommended for all levels of programming experience (what this client is implemented using)
from KalshiClientsBaseV2ApiKey_FIXED import ExchangeClient
import pytz
import time
import json
import uuid
import pandas as pd
import numpy as np
import requests
from datetime import datetime, timedelta


from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

import os
import base64

def load_private_key(b64_key="", file_path=""):
    """Load Kalshi RSA key from file or env var (same as monitoring script)."""
    if file_path and os.path.exists(file_path):
        with open(file_path, "rb") as f: pem = f.read()
    elif b64_key:
        try: pem = base64.b64decode(b64_key)
        except Exception: pem = b64_key.encode()
    else:
        raise FileNotFoundError(f"No private key. Set KALSHI_PRIVATE_KEY or place at '{file_path}'.")
    return serialization.load_pem_private_key(pem, password=None, backend=default_backend())

prod_key_id = os.environ.get("KALSHI_API_KEY_ID", "c3204983-77fc-491b-99f7-136600698178")
prod_private_key = load_private_key(
    b64_key=os.environ.get("KALSHI_PRIVATE_KEY", ""),
    file_path=os.environ.get("KALSHI_PRIVATE_KEY_PATH", "Lisa_Kalshi.txt")
)

# for prod
prod_api_base = "https://api.elections.kalshi.com/trade-api/v2"

## if wanting to test in prod:
exchange_client = ExchangeClient(exchange_api_base=prod_api_base, key_id = prod_key_id, private_key = prod_private_key)

# first we will check on the exchange status to confirm you are properly connected...
print(exchange_client.get_exchange_status())

###### PASTE FORECAST_TABLE INTO GSHEET

from google.oauth2 import service_account
from googleapiclient.discovery import build
import pandas as pd
from datetime import datetime
import pytz

def append_to_gsheet(df, spreadsheet_id, range_name):
    """
    Append a DataFrame to a Google Sheet. Non-fatal if credentials are missing.
    """
    try:
        SCOPES = ['https://www.googleapis.com/auth/spreadsheets']
        SERVICE_ACCOUNT_FILE = 'google_credentials.json'

        if not os.path.exists(SERVICE_ACCOUNT_FILE) or os.path.getsize(SERVICE_ACCOUNT_FILE) < 10:
            print(f"GSheet skipped: {SERVICE_ACCOUNT_FILE} missing or empty")
            return False

        creds = service_account.Credentials.from_service_account_file(
            SERVICE_ACCOUNT_FILE, scopes=SCOPES)

        service = build('sheets', 'v4', credentials=creds)
        values = df.values.tolist()
        body = {'values': values}

        result = service.spreadsheets().values().append(
            spreadsheetId=spreadsheet_id,
            range=range_name,
            valueInputOption='RAW',
            insertDataOption='INSERT_ROWS',
            body=body).execute()

        print(f"Append successful")
        print(f"{result.get('updates').get('updatedRows')} rows added")
        return True
    except Exception as e:
        print(f"GSheet error (non-fatal): {e}")
        return False

# Determine if current time in Central Time is after 2 PM
central_time = datetime.now(pytz.timezone('US/Central'))
variable = 1 if central_time.hour >= 14 and central_time.hour < 23 else 0

# Define the cities and their coordinates for NWS
cities = {
    "Austin": (30.18304, -97.67987),
    "Miami": (25.79056, -80.31639),
    "Houston": (29.64542, -95.27889),
    "Denver": (39.84658, -104.65622),
    "New York City": (40.78333, -73.96667),
    "Philadelphia": (39.87327, -75.22678),
    "Chicago": (41.78417, -87.75528),
    "Los Angeles": (33.94250, -118.40806),
    "Atlanta": (33.64068, -84.42694),
    "Washington DC": (38.85208, -77.03772),
    "Phoenix": (33.43722, -112.00778),
    "Dallas": (32.89681, -97.03781),
    "Las Vegas": (36.08000, -115.15222),
    "Oklahoma City": (35.39306, -97.60056),
    "Seattle": (47.44889, -122.30917),
    "San Francisco": (37.61961, -122.36558),
    "San Antonio": (29.53389, -98.46917),
    "Minneapolis": (44.88306, -93.22889),
    "New Orleans": (29.99333, -90.25806),
}

def get_accuweather_forecast(coords):
    try:
        api_key = "lEl0lfAft6PncVXwatr92Y2YjGJL5YKs"  # Replace with your actual API key
        lat, lon = coords

        # Fetch location key from AccuWeather API using geoposition search
        location_url = f"http://dataservice.accuweather.com/locations/v1/cities/geoposition/search"
        location_params = {
            "apikey": api_key,
            "q": f"{lat},{lon}"  # Format coordinates for the API
        }

        location_response = requests.get(location_url, params=location_params)
        location_response.raise_for_status()  # Raise an exception for bad status codes
        location_key = location_response.json()["Key"]  # Extract location key

        # Fetch 5-day forecast for the location key
        forecast_url = f"http://dataservice.accuweather.com/forecasts/v1/daily/5day/{location_key}"
        forecast_params = {
            "apikey": api_key,
            "metric": "false"  # Use Fahrenheit
        }

        forecast_response = requests.get(forecast_url, params=forecast_params)
        forecast_response.raise_for_status()
        forecast = forecast_response.json()

        # Get today or tomorrow's forecast based on 'variable'
        tomorrow_forecast = forecast["DailyForecasts"][variable]
        high_temp = tomorrow_forecast["Temperature"]["Maximum"]["Value"]

        return int(high_temp)

    except Exception as e:
        print(f"Error fetching AccuWeather forecast for {coords}: {e}")
        return "N/A"

# Function to get forecast from NWS
def get_nws_forecast(lat, lon):
    try:
        # Construct NWS API URL
        base_url = f"https://api.weather.gov/points/{lat},{lon}"
        grid_response = requests.get(base_url)
        grid_response.raise_for_status()
        forecast_url = grid_response.json()['properties']['forecast']

        forecast_response = requests.get(forecast_url)
        forecast_response.raise_for_status()
        periods = forecast_response.json()['properties']['periods']

        # Get tomorrow's date
        # tomorrow = (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d')
        dayswitch = (central_time + timedelta(days=variable)).strftime('%Y-%m-%d') #pulling tomorrow or today

        for period in periods:
            if dayswitch in period['startTime'] and "day" in period['name'].lower():
                return period['temperature']  # NWS temperatures are already in Fahrenheit

        return "N/A"
    except Exception as e:
        print(f"Error fetching NWS forecast for {lat}, {lon}: {e}")
        return "N/A"

# Iterate through cities and fetch data
# def get_weatherunderground_forecast(lat, lon):
def get_weatherunderground_forecast(city, coords):
    API_KEY = "a828c2a178844147a8c2a17884a147a5"  # Weather Underground API Key
    lat, lon = coords  # Extract latitude and longitude from coords
    URL = f"https://api.weather.com/v3/wx/forecast/daily/5day?apiKey={API_KEY}&geocode={lat},{lon}&format=json&units=e&language=en-US"

    # Send request
    response = requests.get(URL)

    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()

        # Try extracting the correct temperature field
        if "temperatureMax" in data:
            # Use variable to get today or tomorrow's forecast
            today_high = data["temperatureMax"][variable]
            return today_high
        else:
            print(f"Error: 'temperatureMax' field not found in API response for {city}.")
            return "N/A"  # Return "N/A" if temperature data is not found
    else:
        print(f"Failed to fetch data for {city}. Status code: {response.status_code}, Message: {response.text}")
        return "N/A"  # Return "N/A" if request fails

# Get current run date in Central Time
central_tz = pytz.timezone("US/Central")
run_date = datetime.now(central_tz).strftime('%Y-%m-%d %H:%M:%S')

# Create the DataFrame
forecast_data = []

for city, coords in cities.items():
    nws_temp = get_nws_forecast(*coords)
    accuweather_temp = get_accuweather_forecast(coords)
    weatherundergroud_temp = get_weatherunderground_forecast(city, coords)

    forecast_data.append({
        "City": city,
        "Forecast Date": (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime('%Y-%m-%d'),
        "Run Date": run_date,
        "Weather Underground": weatherundergroud_temp,
        "Accuweather": accuweather_temp,
        "NWS": nws_temp
    })

forecast_table = pd.DataFrame(forecast_data)

# Calculate standard deviation and range for each city
forecast_table[[ "Weather Underground","Accuweather", "NWS"]] = forecast_table[["Weather Underground","Accuweather", "NWS"]].apply(pd.to_numeric, errors='coerce')
forecast_table["Average"] = forecast_table[["Weather Underground", "Accuweather", "NWS"]].mean(axis=1)
forecast_table["Standard Deviation"] = forecast_table[["Weather Underground","Accuweather", "NWS"]].std(axis=1)
forecast_table["Highest Minus Lowest"] = forecast_table[["Weather Underground", "Accuweather", "NWS"]].max(axis=1) - forecast_table[["Weather Underground","Accuweather", "NWS"]].min(axis=1)

# Display the DataFrame
forecast_table

##### GET CONDITIONS FROM NWS

import requests
import pandas as pd
from datetime import datetime, timedelta

# City data with their corresponding location information for NWS API
cities = {
    "Austin": {"lat": 30.18304, "lon": -97.67987},
    "Miami": {"lat": 25.79056, "lon": -80.31639},
    "Houston": {"lat": 29.64542, "lon": -95.27889},
    "Denver": {"lat": 39.84658, "lon": -104.65622},
    "New York City": {"lat": 40.78333, "lon": -73.96667},
    "Philadelphia": {"lat": 39.87327, "lon": -75.22678},
    "Chicago": {"lat": 41.78417, "lon": -87.75528},
    "Los Angeles": {"lat": 33.94250, "lon": -118.40806},
    "Atlanta": {"lat": 33.64068, "lon": -84.42694},
    "Washington DC": {"lat": 38.85208, "lon": -77.03772},
    "Phoenix": {"lat": 33.43722, "lon": -112.00778},
    "Dallas": {"lat": 32.89681, "lon": -97.03781},
    "Las Vegas": {"lat": 36.08000, "lon": -115.15222},
    "Oklahoma City": {"lat": 35.39306, "lon": -97.60056},
    "Seattle": {"lat": 47.44889, "lon": -122.30917},
    "San Francisco": {"lat": 37.61961, "lon": -122.36558},
    "San Antonio": {"lat": 29.53389, "lon": -98.46917},
    "Minneapolis": {"lat": 44.88306, "lon": -93.22889},
    "New Orleans": {"lat": 29.99333, "lon": -90.25806},
}

# Prepare the date for today
today = datetime.now(pytz.timezone('US/Central')).strftime("%Y-%m-%d")

# Function to fetch weather conditions from NWS
def fetch_nws_conditions(city):
    url = f"https://api.weather.gov/points/{city['lat']},{city['lon']}"
    response = requests.get(url)
    if response.status_code == 200:
        grid_data = response.json()
        forecast_url = grid_data['properties']['forecast']
        forecast_response = requests.get(forecast_url)
        if forecast_response.status_code == 200:
            forecast_data = forecast_response.json()
            # print(forecast_data['properties']['periods'])
            target_date = (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d")

            for period in forecast_data['properties']['periods']:
                # print(period)
                if target_date in period['startTime']:
                    return period['detailedForecast'], period['shortForecast']
    return None, None

# Collect forecast conditions
forecast_conditions = []
for city_name, city_coords in cities.items():
    nws_detailed, nws_short = fetch_nws_conditions(city_coords)
    forecast_conditions.append({
        "City": city_name,
        "NWS Detailed Conditions": nws_detailed,
        "NWS Short Conditions": nws_short
    })

# Create a DataFrame
forecast_conditions_table = pd.DataFrame(forecast_conditions)

forecast_table = pd.merge(forecast_table, forecast_conditions_table, on='City', how='inner')
forecast_table

############# GET MIDNIGHT TEMPS FROM NWS

import requests
from datetime import datetime, timedelta, date
import re
import pandas as pd

# Function to fetch the forecast at midnight through NWS
def fetch_midnight_forecast(coords):
    # Get the grid points URL for the location
    url = f"https://api.weather.gov/points/{coords['lat']},{coords['lon']}"
    response = requests.get(url)
    if response.status_code == 200:
        grid_data = response.json()
        forecast_url = grid_data['properties']['forecastHourly']

        # Fetch hourly forecast for midnight
        midnight_temp = None
        hourly_response = requests.get(forecast_url)
        if hourly_response.status_code == 200:
            hourly_data = hourly_response.json()
            for period in hourly_data['properties']['periods']:
                # Fix invalid ISO format by ensuring proper timezone formatting
                start_time = re.sub(r"([-+]\d{2}):(\d{1})$", r"\1:0\2", period['startTime'])
                # forecast_time = datetime.fromisoformat(start_time)
                forecast_time = datetime.fromisoformat(start_time).astimezone(pytz.timezone('US/Central'))  # Or your desired timezone
                # print((datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d"))
                # print('forecast_time.date() =', forecast_time.date())
                if forecast_time.hour == 0 and forecast_time.minute == 0 and forecast_time.date() == datetime.now(pytz.timezone('US/Central')).date() + timedelta(days=variable):
                # if forecast_time.date() == (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d"):
                  # print(datetime.now(pytz.timezone('US/Central')).date() + timedelta(days=variable))
                  # print(forecast_time.date())
                  midnight_temp = period['temperature']
                  break
        return midnight_temp
    else:
        print(f"Failed to fetch grid data. Status code: {response.status_code}, URL: {url}")
    return None

# Coordinates for cities
cities = {
    "Austin": {"lat": 30.18304, "lon": -97.67987},
    "Miami": {"lat": 25.79056, "lon": -80.31639},
    "Houston": {"lat": 29.64542, "lon": -95.27889},
    "Denver": {"lat": 39.84658, "lon": -104.65622},
    "New York City": {"lat": 40.78333, "lon": -73.96667},
    "Philadelphia": {"lat": 39.87327, "lon": -75.22678},
    "Chicago": {"lat": 41.78417, "lon": -87.75528},
    "Los Angeles": {"lat": 33.94250, "lon": -118.40806},
    "Atlanta": {"lat": 33.64068, "lon": -84.42694},
    "Washington DC": {"lat": 38.85208, "lon": -77.03772},
    "Phoenix": {"lat": 33.43722, "lon": -112.00778},
    "Dallas": {"lat": 32.89681, "lon": -97.03781},
    "Las Vegas": {"lat": 36.08000, "lon": -115.15222},
    "Oklahoma City": {"lat": 35.39306, "lon": -97.60056},
    "Seattle": {"lat": 47.44889, "lon": -122.30917},
    "San Francisco": {"lat": 37.61961, "lon": -122.36558},
    "San Antonio": {"lat": 29.53389, "lon": -98.46917},
    "Minneapolis": {"lat": 44.88306, "lon": -93.22889},
    "New Orleans": {"lat": 29.99333, "lon": -90.25806},
}

# Fetch forecasts for all cities
forecasts = []
for city, coords in cities.items():
    midnight_forecast = fetch_midnight_forecast(coords)
    forecasts.append({
        "City": city,
        "Midnight Temperature": midnight_forecast
    })

# Create a DataFrame
forecast_df = pd.DataFrame(forecasts)

forecast_table = pd.merge(forecast_table, forecast_df, on='City', how='inner')

if variable == 0:
  forecast_table['concat'] = forecast_table['City'] + forecast_table['Forecast Date'] + 'Day'
if variable == 1:
  forecast_table['concat'] = forecast_table['City'] + forecast_table['Forecast Date'] + 'Night'

forecast_table

# Example usage:
spreadsheet_id = '1SDwPpdK6H-78sWY5YYlToi043fYjlc2w2TuBvxUKs3Y'  # Get this from the URL
range_name = 'City Summary!A2'  # If this is your first time, include headers in the sheet

# Append your forecast_table
forecast_table = forecast_table.fillna("")
success = append_to_gsheet(forecast_table, spreadsheet_id, range_name)

########## DROP ANY WHERE MIDNIGHT TEMP IS WITHIN 5 DEGREES OF TOMORROW'S HIGH

if variable == 1:
  # Ensure 'Average' and 'Midnight Temperature' columns are numeric
  forecast_table['Average'] = pd.to_numeric(forecast_table['Average'], errors='coerce')
  forecast_table['Midnight Temperature'] = pd.to_numeric(forecast_table['Midnight Temperature'], errors='coerce')

  forecast_table = forecast_table[abs(forecast_table['Average'] - forecast_table['Midnight Temperature']) >= 4.5]
forecast_table

########### INPUT EVENT TICKERS, CITIES, HIGHEST NO PRICES, HISTORICAL VARIANCE

# Determine if current time in Central Time is after 2 PM
central_time = datetime.now(pytz.timezone('US/Central'))
variable = 1 if central_time.hour >= 14 else 0

day = central_time + timedelta(days=variable) #pulling tomorrow or today in central time
month = day.strftime("%b").upper()
day = day.strftime("%d")
# print(day)

event_ticker1 = ['KXHIGHCHI-26' + month + day, 'Chicago', 56, 1.7]
event_ticker2 = ['KXHIGHNY-26' + month + day, 'New York City', 46, 1.5]
event_ticker3 = ['KXHIGHDEN-26' + month + day, 'Denver', 57, 2.4]
event_ticker4 = ['KXHIGHPHIL-26' + month + day, 'Philadelphia', 52, 1.6]
event_ticker5 = ['KXHIGHAUS-26' + month + day, 'Austin', 63, 1.7]
event_ticker6 = ['KXHIGHMIA-26' + month + day, 'Miami', 43, 1.1]
event_ticker7 = ['KXHIGHTHOU-26' + month + day, 'Houston', 59, 2.0]
event_ticker8 = ['KXHIGHLAX-26' + month + day, 'Los Angeles', 58, 2.0]
event_ticker9 = ['KXHIGHTATL-26' + month + day, 'Atlanta', 55, 1.5]
event_ticker10 = ['KXHIGHTDC-26' + month + day, 'Washington DC', 50, 1.5]
event_ticker11 = ['KXHIGHTPHX-26' + month + day, 'Phoenix', 55, 1.5]
event_ticker12 = ['KXHIGHTDAL-26' + month + day, 'Dallas', 55, 1.5]
event_ticker13 = ['KXHIGHTLV-26' + month + day, 'Las Vegas', 55, 1.5]
event_ticker14 = ['KXHIGHTOKC-26' + month + day, 'Oklahoma City', 55, 1.5]
event_ticker15 = ['KXHIGHTSEA-26' + month + day, 'Seattle', 50, 1.5]
event_ticker16 = ['KXHIGHTSFO-26' + month + day, 'San Francisco', 50, 1.5]
event_ticker17 = ['KXHIGHTSATX-26' + month + day, 'San Antonio', 55, 1.5]
event_ticker18 = ['KXHIGHTMIN-26' + month + day, 'Minneapolis', 55, 1.5]
event_ticker19 = ['KXHIGHTNOLA-26' + month + day, 'New Orleans', 55, 1.5]

############ PULL MARKETS
all_event_tickers = [event_ticker1, event_ticker2, event_ticker3, event_ticker4, event_ticker5, event_ticker6, event_ticker7, event_ticker8, event_ticker9, event_ticker10, event_ticker11, event_ticker12, event_ticker13, event_ticker14, event_ticker15, event_ticker16, event_ticker17, event_ticker18, event_ticker19]
event_tickers = pd.DataFrame(all_event_tickers, columns=['Ticker', 'City', 'hi_no_price', 'var'])
event_tickers['var_sqrt'] = np.sqrt(event_tickers['var'])
markets_table = pd.DataFrame(columns=['event_ticker', 'market_ticker', 'market_ticker_prev', 'City', 'low_range', 'high_range', 'hi_no_price'])

for event_ticker in event_tickers['Ticker']:
  event_params = {'event_ticker': event_ticker}
  print(event_ticker)
  event_response = exchange_client.get_event(**event_params)

  for market in event_response['markets']:
      city = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'City'].iloc[0]
      hi_no_price = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'hi_no_price'].iloc[0]
      historical_variance = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'var'].iloc[0]
      historical_variance_sqrt = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'var_sqrt'].iloc[0]
      if "-B" in market['ticker']:
        match = re.search(r"-B(\d+(\.\d+)?)", market['ticker'])
        if match:
          number_after_b = float(match.group(1))
          low_range = number_after_b - 1
          high_range = number_after_b + 1
          markets_table = pd.concat([markets_table, pd.DataFrame([[event_ticker, market['ticker'], city, low_range, high_range, hi_no_price, historical_variance, historical_variance_sqrt]], columns=['event_ticker', 'market_ticker', 'City', 'low_range', 'high_range', 'hi_no_price', 'var', 'var_sqrt'])], ignore_index=True)

      if "-T" in market['ticker']:
        match = re.search(r"-T(\d+(\.\d+)?)", market['ticker'])
        if match:
          number_after_t = float(match.group(1))

          low_range = 0
          high_range = number_after_t - 0.5
          markets_table = pd.concat([markets_table, pd.DataFrame([[event_ticker, market['ticker'], city, low_range, high_range, hi_no_price, historical_variance, historical_variance_sqrt]], columns=['event_ticker', 'market_ticker', 'City', 'low_range', 'high_range', 'hi_no_price', 'var', 'var_sqrt'])], ignore_index=True)

markets_table['market_ticker_prev'] = markets_table['market_ticker'].shift(1)

for index, row in markets_table.iterrows():
  # Skip the first row to avoid the None value in 'market_ticker_prev'
  if index == 0:
    continue
  if "-B" in row['market_ticker_prev'] and "-T" in row['market_ticker']:
    markets_table.loc[index, 'low_range'] = row['high_range'] + 1
    markets_table.loc[index, 'high_range'] = 150

markets_table.drop(columns=['market_ticker_prev'], inplace=True)
markets_table

##### COMBINE FORECAST AND MARKET TABLES, AND CALCULATE PROBABILITIES
from scipy.stats import norm

combined_table = pd.merge(forecast_table, markets_table, on='City', how='inner')

# Convert 'Average' and 'Standard Deviation' columns to numeric, handling errors
combined_table['Average'] = pd.to_numeric(combined_table['Average'], errors='coerce')
combined_table['Standard Deviation'] = pd.to_numeric(combined_table['Standard Deviation'], errors='coerce')

# City-specific floor std dev (from v1 bot calibration, 1816 observations)
# Model uses: max(inter_source_std, city_floor_std)
# This prevents 0 std when all sources agree (which gives 100%/0% extremes)
CITY_FLOOR_STD = {
    "Austin": 1.2, "Miami": 1.0, "Houston": 1.9, "Denver": 1.4,
    "New York City": 1.2, "Philadelphia": 1.3, "Chicago": 1.3, "Los Angeles": 1.2,
    "Atlanta": 1.2, "Washington DC": 1.3, "Phoenix": 1.1, "Dallas": 1.2,
    "Las Vegas": 1.1, "Oklahoma City": 1.4, "Seattle": 1.2, "San Francisco": 1.2,
    "San Antonio": 1.2, "Minneapolis": 1.4, "New Orleans": 1.2,
}
combined_table['City Floor Std'] = combined_table['City'].map(CITY_FLOOR_STD).fillna(1.2)
combined_table['Standard Deviation'] = combined_table[['Standard Deviation', 'City Floor Std']].max(axis=1)
combined_table['Standard Deviation'] = combined_table['Standard Deviation'].replace({0: 1.2, np.nan: 1.2})

# Ensure 'high_range' and 'low_range' are numeric
combined_table['high_range'] = pd.to_numeric(combined_table['high_range'], errors='coerce')
combined_table['low_range'] = pd.to_numeric(combined_table['low_range'], errors='coerce')

combined_table['yes_probability'] = norm.cdf(combined_table['high_range'], loc=combined_table['Average'], scale=combined_table['Standard Deviation']) - norm.cdf(combined_table['low_range'], loc=combined_table['Average'], scale=combined_table['Standard Deviation'])
combined_table['yes_probability'] = combined_table['yes_probability'].round(2)
combined_table['fair_no_price'] = 1 - combined_table['yes_probability']
combined_table

####PULL ORDER BOOK OF MARKETS

combined_table['no_highest_bid'] = ''
combined_table['no_lowest_offer'] = ''
combined_table['no_orderbook'] = ''
combined_table['yes_orderbook'] = ''

for index, row in combined_table.iterrows():
  market_ticker = row['market_ticker']
  market_history_params = {'ticker':market_ticker,
                            'depth': 3
                                }
  orderbook_response = exchange_client.get_orderbook(**market_history_params)

  # Parse orderbook — handle both old format (orderbook.no/yes in cents)
  # and new format (orderbook_fp.no_dollars/yes_dollars in dollar strings)
  no_levels = []  # list of [price_cents, quantity]
  yes_levels = []

  if 'orderbook_fp' in orderbook_response:
    ob_fp = orderbook_response['orderbook_fp']
    # no_dollars: [['0.8200', '300.00'], ...] → price in dollars, convert to cents
    for level in ob_fp.get('no_dollars', []):
      no_levels.append([int(round(float(level[0]) * 100)), int(float(level[1]))])
    for level in ob_fp.get('yes_dollars', []):
      yes_levels.append([int(round(float(level[0]) * 100)), int(float(level[1]))])
  elif 'orderbook' in orderbook_response:
    ob = orderbook_response['orderbook']
    no_levels = ob.get('no', [])
    yes_levels = ob.get('yes', [])
  else:
    # Response itself might be the orderbook
    no_levels = orderbook_response.get('no', [])
    yes_levels = orderbook_response.get('yes', [])

  if no_levels and len(no_levels) > 0:
    combined_table.loc[index, 'no_highest_bid'] = str(no_levels[-1][0])

  if yes_levels and len(yes_levels) > 0:
    combined_table.loc[index, 'no_lowest_offer'] = str(100 - yes_levels[-1][0])

  combined_table.loc[index, 'no_orderbook'] = str(no_levels)
  combined_table.loc[index, 'yes_orderbook'] = str(yes_levels)

combined_table

#If you need to access the detailed orderbook data later, you can use eval() or ast.literal_eval() (safer) to convert the string back to a list of lists:
#import ast
    # orderbook_data = ast.literal_eval(markets_table.loc[index, 'orderbook'])

######### ACTUALS VS FORECAST, FOR BETTING THE HIGH END

# Define column names
columns = ["Austin", "Miami", "Denver", "Houston", "Philadelphia", "New York City", "Chicago", "Los Angeles"]

# Define row indices
rows = ["5", "4", "3", "2", "1", "0", "-1", "-2", "-3", "-4", "-5"]

# Define data values (converted from percentages to decimals)
data = [
    [0.0270, 0.0256, 0.1290, 0.0000, 0.0000, 0.0270, 0.0333, 0.0667],
    [0.0270, 0.0000, 0.0000, 0.0000, 0.0263, 0.0000, 0.0333, 0.0000],
    [0.0811, 0.0000, 0.0645, 0.1613, 0.1579, 0.1081, 0.1333, 0.0000],
    [0.2432, 0.2308, 0.1290, 0.1935, 0.1053, 0.1622, 0.2333, 0.0000],
    [0.1892, 0.2051, 0.1935, 0.1935, 0.2895, 0.2162, 0.3333, 0.2667],
    [0.1351, 0.2821, 0.1935, 0.0645, 0.1053, 0.2162, 0.0667, 0.2667],
    [0.1892, 0.1282, 0.0645, 0.2258, 0.1053, 0.0811, 0.1000, 0.1333],
    [0.0270, 0.0769, 0.0645, 0.0968, 0.1053, 0.1622, 0.0000, 0.1333],
    [0.0541, 0.0256, 0.0968, 0.0323, 0.0526, 0.0000, 0.0000, 0.0667],
    [0.0000, 0.0000, 0.0323, 0.0000, 0.0263, 0.0000, 0.0333, 0.0000],
    [0.0270, 0.0256, 0.0323, 0.0323, 0.0263, 0.0270, 0.0333, 0.0667]
]

# Create DataFrame
actuals_vs_forecast_variation = pd.DataFrame(data, columns=columns, index=rows)
actuals_vs_forecast_variation = actuals_vs_forecast_variation.transpose()
actuals_vs_forecast_variation['City'] = actuals_vs_forecast_variation.index
print(actuals_vs_forecast_variation.index)
actuals_vs_forecast_variation

##### CALCULATE HIGH RANGE BIDS

x = combined_table[combined_table['high_range'] == 150]

y = pd.DataFrame(columns=['City', 'low_range', 'Average', 'forecast_variation_vs_high_end', 'bid_price'])
forcast_data = round(x['low_range'] - x['Average'])
y['forecast_variation_vs_high_end'] = forcast_data
y['City'] = x['City']
y['low_range'] = x['low_range']
y['Average'] = x['Average']
y = pd.merge(y, actuals_vs_forecast_variation, on='City', how='inner')
# Rebuild chart_end_index from merged y (only cities with historical data)
chart_end_index = [int(v) for v in y['forecast_variation_vs_high_end'].tolist()]
filtered_data = [y[str(col)].tolist() for col in range(5, -6, -1)]

# calculate bid_price for each city (only cities in actuals table)
percentage_data = list()
for index, value in enumerate(chart_end_index):
  if value > 5:
    value = 5
  if value < -5:
    value = -5
  city_data = [x[index] for x in filtered_data]
  end_index = 5 - value + 1
  # print(value)
  values_to_sum = city_data[0:end_index]
  percentage_data.append(sum(values_to_sum))

y['bid_price'] = [1 - x for x in percentage_data]
y

for index, row in combined_table.iterrows():
  if row['high_range'] == 150:
    # Get the bid_price for the current city from the y DataFrame (if available)
    try:
      bid_price = y.loc[y['City'] == row['City'], 'bid_price'].iloc[0]
      combined_table.loc[index, 'hi_no_price'] = bid_price * 100 - 15 #20 cent buffer
    except (IndexError, KeyError):
      pass  # New cities without historical data keep their default hi_no_price

combined_table

####### PASTE COMBINED_TABLE INTO GSHEET

spreadsheet_id = '1SDwPpdK6H-78sWY5YYlToi043fYjlc2w2TuBvxUKs3Y'
range_name = 'Orderbook'

# Append your forecast_table
combined_table = combined_table.fillna("")
success = append_to_gsheet(combined_table, spreadsheet_id, range_name)

####### DELETE EXISTING ORDERS

for market_ticker in combined_table['market_ticker']:
  order_params = {'ticker':market_ticker}
  order_response = exchange_client.get_orders(**order_params)

  for i in range(len(order_response['orders'])):
    order_id = order_response['orders'][i]['order_id']
    status = order_response['orders'][i]['status']
    order_id = {'order_id':order_id}
    if order_id is not None and status == 'resting':
      exchange_client.cancel_order(**order_id)

############## PULL CURRENT POSITIONS
for market_ticker in combined_table['market_ticker']:
  positions_params = {'ticker': market_ticker}
  current_position = exchange_client.get_positions(**positions_params)
  # print(current_position)
  if 'market_positions' in current_position and current_position['market_positions']:
    positions = pd.DataFrame(current_position['market_positions'])

    if 'position' in positions.columns:
      live_positions = positions[positions['position'] != 0]
      if not live_positions.empty:
        row_index = combined_table.index[combined_table['market_ticker'] == market_ticker].tolist()[0]
        combined_table.loc[row_index, 'position'] = abs(live_positions['position'].iloc[0])
  if 'position' not in combined_table.columns:
    combined_table['position'] = 0
  combined_table['position'] = combined_table['position'].fillna(0).astype(int)
  combined_table['resting_order_count'] = 0

combined_table

##### PLACE ORDERS

######### BETTING INPUTS
increment = 3
increment1 = 6
price_count = list(range(0, 8))
starting_contracts = 1

max_contracts = 500
max_contracts1 = 500
market_cutoff_probability = .2
spreadsheet_id = '1SDwPpdK6H-78sWY5YYlToi043fYjlc2w2TuBvxUKs3Y'
range_name = 'Trades Placed'
# print('hi')
#################################################### CANCEL CONTRACT TIME
from datetime import datetime, timedelta
import pytz

def get_unix_time_for_tomorrow(hour: int, minute: int, timezone: str = 'US/Central') -> int:
    """
    Calculate the Unix time for a specific hour and minute tomorrow in the given timezone.

    :param hour: Hour of the time (24-hour format).
    :param minute: Minute of the time.
    :param timezone: Timezone (default is 'US/Central').
    :return: Unix timestamp for the specified time tomorrow.
    """
    # Define the timezone
    tz = pytz.timezone(timezone)

    # Get the current date and time in the specified timezone
    now = datetime.now(tz)

    # Calculate tomorrow's date at the specified time
    target_time = tz.localize(
        datetime(year=now.year, month=now.month, day=now.day, hour=hour, minute=minute) + timedelta(days=variable)
    )

    # Convert to Unix time
    return int(target_time.timestamp())

########## BUY CALCULATIONS
orders_placed = 0
for index, row in combined_table.iterrows():
  ticker = row['market_ticker']
  is_tail = "-T" in ticker and row['high_range'] == 150
  yes_prob = row['yes_probability']
  no_offer = row['no_lowest_offer']
  no_bid = row['no_highest_bid']
  hi_no = row['hi_no_price']

  # Diagnostic: show every market's state
  print(f"\n  {ticker}: P(yes)={yes_prob:.2f} hi_no={hi_no} no_bid={no_bid} no_offer={no_offer} tail={is_tail}")

  # Filter 1: probability cutoff
  if not (yes_prob > market_cutoff_probability or is_tail):
    print(f"    SKIP: P(yes)={yes_prob:.2f} <= {market_cutoff_probability} cutoff")
    continue

  # Filter 2: skip low-end tails
  if "-T" in ticker and not is_tail:
    print(f"    SKIP: low-end tail (not traded)")
    continue

  # Filter 3: need orderbook data
  if no_offer == '' or no_bid == '':
    print(f"    SKIP: no orderbook data")
    continue

  i1 = 0
  level_orders = 0
  for i in price_count:
    if "-T" not in ticker:
      bid_price = max(hi_no - i * increment, 1)
    if is_tail:
      bid_price = max(hi_no - i * increment1, 1)

    # Show first level diagnostics
    if i == 0:
      print(f"    Level 0: bid={bid_price:.0f} vs no_offer={int(no_offer)} no_bid={int(no_bid)} (need bid<offer AND bid<bid-3)")

    if not (bid_price < int(no_offer)):
      if i == 0: print(f"    SKIP level 0: bid {bid_price:.0f} >= no_offer {int(no_offer)}")
      continue
    if not (bid_price < int(no_bid) - 3):
      if i == 0: print(f"    SKIP level 0: bid {bid_price:.0f} >= no_bid-3 ({int(no_bid)-3})")
      continue
    if not (max_contracts >= row['position'] + row['resting_order_count'] + starting_contracts + i * 10):
      if i == 0: print(f"    SKIP level 0: position cap")
      continue

    trades = pd.DataFrame(columns=['City', 'Forecast Date', 'Run Date', 'Market', 'Contracts', 'Price', 'abv'])
    contracts = starting_contracts
    i1 = i1 + 1

    # Detect city abbreviation and cancel time — check longer abbreviations first
    abv = ''
    cancel_hour = 10
    cancel_minute = 5
    ticker_str = row['market_ticker']
    if 'THOU' in ticker_str: abv = 'THOU'; cancel_hour = 10
    elif 'SATX' in ticker_str: abv = 'SATX'; cancel_hour = 10
    elif 'TMIN' in ticker_str: abv = 'TMIN'; cancel_hour = 10
    elif 'NOLA' in ticker_str: abv = 'NOLA'; cancel_hour = 10
    elif 'CHI' in ticker_str: abv = 'CHI'; cancel_hour = 10
    elif 'AUS' in ticker_str: abv = 'AUS'; cancel_hour = 10
    elif 'HOU' in ticker_str: abv = 'HOU'; cancel_hour = 10
    elif 'DEN' in ticker_str: abv = 'DEN'; cancel_hour = 10
    elif 'NY-' in ticker_str: abv = 'NY-'; cancel_hour = 9
    elif 'PHI' in ticker_str: abv = 'PHI'; cancel_hour = 9
    elif 'MIA' in ticker_str: abv = 'MIA'; cancel_hour = 9
    elif 'LAX' in ticker_str: abv = 'LAX'; cancel_hour = 10
    elif 'ATL' in ticker_str: abv = 'ATL'; cancel_hour = 9
    elif 'TDC' in ticker_str: abv = 'TDC'; cancel_hour = 9
    elif 'PHX' in ticker_str: abv = 'PHX'; cancel_hour = 10
    elif 'DAL' in ticker_str: abv = 'DAL'; cancel_hour = 10
    elif 'TLV' in ticker_str: abv = 'TLV'; cancel_hour = 10
    elif 'OKC' in ticker_str: abv = 'OKC'; cancel_hour = 10
    elif 'SEA' in ticker_str: abv = 'SEA'; cancel_hour = 10
    elif 'SFO' in ticker_str: abv = 'SFO'; cancel_hour = 10

    central_time = datetime.now(pytz.timezone('US/Central'))
    if central_time.hour > 10 or central_time.hour < 6:
      cancel_hour = 1
      cancel_minute = 59

    trades = pd.concat([trades, pd.DataFrame([[row['City'], row['Forecast Date'], row['Run Date'], row['market_ticker'], contracts, bid_price, abv]], columns=['City', 'Forecast Date', 'Run Date', 'Market', 'Contracts', 'Price', 'abv'])], ignore_index=True)
    order_params = {'ticker':row['market_ticker'],
                      'client_order_id':str(uuid.uuid4()),
                      'type':'limit',
                      'action':'buy',
                      'side':'no',
                      'count':contracts,
                      'no_price':int(bid_price),
                      'expiration_ts':get_unix_time_for_tomorrow(cancel_hour, cancel_minute)}
    exchange_client.create_order(**order_params)
    time.sleep(0.1)  # Rate limit protection
    success = append_to_gsheet(trades, spreadsheet_id, range_name)
    row['resting_order_count'] = row['resting_order_count'] + contracts
    orders_placed += 1
    level_orders += 1
    if bid_price <= 1:
      break  # Don't place more orders at the 1¢ floor
  if level_orders > 0:
    print(f"    ✓ Placed {level_orders} orders")

print(f"\n{'='*60}")
print(f"TOTAL ORDERS PLACED: {orders_placed}")
print(f"{'='*60}")

# PASTE YESTERDAY'S P&L INTO GSHEET
# variable = 1
central_tz = pytz.timezone("America/Chicago")
central_now = datetime.now(central_tz)
central_date = central_now.date()

date = central_date - timedelta(days=variable)
month = date.strftime("%b").upper()
day = date.strftime("%d")
# print(date)
# print(month)
# print(day)
settlement_params = {'limit': 1000}

settlements = exchange_client.get_portfolio_settlements(**settlement_params)
# print(settlements)
spreadsheet_id = '1SDwPpdK6H-78sWY5YYlToi043fYjlc2w2TuBvxUKs3Y'  # Get this from the URL
range_name = 'PnL'  # If this is your first time, include headers in the sheet
# settlement_table = []

for settlement in settlements['settlements']:
  if variable == 1:
    if settlement['yes_total_cost'] > 0 or settlement['no_total_cost'] > 0:
      settled_time_dt = datetime.strptime(settlement['settled_time'], '%Y-%m-%dT%H:%M:%S.%fZ')
      trade_date_dt = settled_time_dt - timedelta(days=variable)
      today_date = datetime.now(pytz.timezone('US/Central'))
      # print(settled_time_dt.strftime('%Y-%m-%d'))
      # if settled_time_dt.strftime('%Y-%m-%d') == '2025-02-19':
        # print('hi')
      if 'HIGH' in settlement['ticker'] and day in settlement['ticker'] and month in settlement['ticker']:
        # Detect city abbreviation — longer prefixes first to avoid partial matches
        stk = settlement['ticker']
        if 'THOU' in stk: settlement['abv'] = 'THOU'
        elif 'SATX' in stk: settlement['abv'] = 'SATX'
        elif 'TMIN' in stk: settlement['abv'] = 'TMIN'
        elif 'NOLA' in stk: settlement['abv'] = 'NOLA'
        elif 'CHI' in stk: settlement['abv'] = 'CHI'
        elif 'AUS' in stk: settlement['abv'] = 'AUS'
        elif 'HOU' in stk: settlement['abv'] = 'HOU'
        elif 'DEN' in stk: settlement['abv'] = 'DEN'
        elif 'NY-' in stk: settlement['abv'] = 'NY-'
        elif 'PHI' in stk: settlement['abv'] = 'PHI'
        elif 'MIA' in stk: settlement['abv'] = 'MIA'
        elif 'LAX' in stk: settlement['abv'] = 'LAX'
        elif 'ATL' in stk: settlement['abv'] = 'ATL'
        elif 'TDC' in stk: settlement['abv'] = 'TDC'
        elif 'PHX' in stk: settlement['abv'] = 'PHX'
        elif 'DAL' in stk: settlement['abv'] = 'DAL'
        elif 'TLV' in stk: settlement['abv'] = 'TLV'
        elif 'OKC' in stk: settlement['abv'] = 'OKC'
        elif 'SEA' in stk: settlement['abv'] = 'SEA'
        elif 'SFO' in stk: settlement['abv'] = 'SFO'
        settlement['trade_date'] = trade_date_dt.strftime('%Y-%m-%d')
        settlement['profit'] = settlement['revenue'] - settlement['yes_total_cost'] - settlement['no_total_cost']
        settlement_table = pd.DataFrame(settlement, index=[0])
        print(settlement_table)
        settlement_table = settlement_table.fillna("")
        success = append_to_gsheet(settlement_table, spreadsheet_id, range_name)

# GET FINALIZED MARKET DATA
# variable = 1
central_tz = pytz.timezone("America/Chicago")
central_now = datetime.now(central_tz)
central_date = central_now.date()

date = central_date - timedelta(days=variable)
# date = datetime.strptime('2025-02-18', '%Y-%m-%d') #if you need to fix historicals
month = date.strftime("%b").upper()
day = date.strftime("%d")

event_ticker1 = ['KXHIGHCHI-26' + month + day, 'CHI']
event_ticker2 = ['KXHIGHNY-26' + month + day, 'NY-']
event_ticker3 = ['KXHIGHDEN-26' + month + day, 'DEN']
event_ticker4 = ['KXHIGHPHIL-26' + month + day, 'PHI']
event_ticker5 = ['KXHIGHAUS-26' + month + day, 'AUS']
event_ticker6 = ['KXHIGHMIA-26' + month + day, 'MIA']
event_ticker7 = ['KXHIGHTHOU-26' + month + day, 'THOU']
event_ticker8 = ['KXHIGHLAX-26' + month + day, 'LAX']
event_ticker9 = ['KXHIGHTATL-26' + month + day, 'ATL']
event_ticker10 = ['KXHIGHTDC-26' + month + day, 'TDC']
event_ticker11 = ['KXHIGHTPHX-26' + month + day, 'PHX']
event_ticker12 = ['KXHIGHTDAL-26' + month + day, 'DAL']
event_ticker13 = ['KXHIGHTLV-26' + month + day, 'TLV']
event_ticker14 = ['KXHIGHTOKC-26' + month + day, 'OKC']
event_ticker15 = ['KXHIGHTSEA-26' + month + day, 'SEA']
event_ticker16 = ['KXHIGHTSFO-26' + month + day, 'SFO']
event_ticker17 = ['KXHIGHTSATX-26' + month + day, 'SATX']
event_ticker18 = ['KXHIGHTMIN-26' + month + day, 'TMIN']
event_ticker19 = ['KXHIGHTNOLA-26' + month + day, 'NOLA']
all_event_tickers = [event_ticker1, event_ticker2, event_ticker3, event_ticker4, event_ticker5, event_ticker6, event_ticker7, event_ticker8, event_ticker9, event_ticker10, event_ticker11, event_ticker12, event_ticker13, event_ticker14, event_ticker15, event_ticker16, event_ticker17, event_ticker18, event_ticker19]
event_tickers = pd.DataFrame(all_event_tickers, columns=['Ticker', 'ABV'])
markets_table = pd.DataFrame(columns=['event_ticker', 'market_ticker', 'ABV', 'volume_traded', 'avg_trade_price_yes', 'avg_trade_price_no', 'pct_volume_traded_yes_taker', 'pct_volume_traded_no_taker', 'trade_date', 'winning_temp', 'winner', 'concat'])

if variable == 1:
  trade_date = datetime.now(pytz.timezone('US/Central')) - timedelta(days=variable)
  trade_date = trade_date.strftime('%Y-%m-%d')
  # trade_date = '2025-02-18' #if you need to fix historicals
  for event_ticker in event_tickers['Ticker']:
    event_params = {'event_ticker': event_ticker}
    event_response = exchange_client.get_event(**event_params)
    abv = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'ABV'].iloc[0]
    for market in event_response['markets']:
      winning_temp = None
      winning_ticker = None
      winner = None
      concat = abv + trade_date
      if market['result'] == 'yes':
        winning_temp = market['expiration_value']
        winner = 'yes'
        concat = abv + trade_date + winner
      volume_traded = 0
      pct_volume_traded_yes_taker = 0
      pct_volume_traded_no_taker = 0
      avg_trade_price_yes = 0
      avg_trade_price_no = 0

      try:
        market_params = {'limit':1000,
                            'ticker':market['ticker']}
        trade_response = exchange_client.get_trades(**market_params)

        for trade in trade_response['trades']:
          volume_traded = volume_traded + trade['count']
          avg_trade_price_yes = avg_trade_price_yes + (trade['yes_price'] * trade['count'])
          avg_trade_price_no = avg_trade_price_no + (trade['no_price'] * trade['count'])
          if trade['taker_side'] == 'yes':
            pct_volume_traded_yes_taker = pct_volume_traded_yes_taker + trade['count']
          if trade['taker_side'] == 'no':
            pct_volume_traded_no_taker = pct_volume_traded_no_taker + trade['count']

        # Check if volume_traded is zero before performing division
        if volume_traded != 0:
          avg_trade_price_yes = avg_trade_price_yes / volume_traded
          avg_trade_price_no = avg_trade_price_no / volume_traded
          pct_volume_traded_yes_taker = pct_volume_traded_yes_taker / volume_traded
          pct_volume_traded_no_taker = pct_volume_traded_no_taker / volume_traded
      except Exception as e:
        print(f"Error fetching trades for {market['ticker']}: {e}")

      markets_table = pd.concat([markets_table, pd.DataFrame([[event_ticker, market['ticker'], abv, volume_traded, avg_trade_price_yes, avg_trade_price_no, pct_volume_traded_yes_taker, pct_volume_traded_no_taker, trade_date, winning_temp, winner, concat]], columns=['event_ticker', 'market_ticker', 'ABV', 'volume_traded', 'avg_trade_price_yes', 'avg_trade_price_no', 'pct_volume_traded_yes_taker', 'pct_volume_traded_no_taker','trade_date','winning_temp', 'winner', 'concat'])], ignore_index=True)

  markets_table

  spreadsheet_id = '1SDwPpdK6H-78sWY5YYlToi043fYjlc2w2TuBvxUKs3Y'
  range_name = 'Finalized Market Data'
  append_to_gsheet(markets_table, spreadsheet_id, range_name)

### GET FILLS
# variable = 1
if variable == 1:
  for event_ticker in event_tickers['Ticker']:
    event_params = {'event_ticker': event_ticker}
    event_response = exchange_client.get_event(**event_params)
    for market in event_response['markets']:

      fill_params = {'limit': 1000,
                    'ticker': market['ticker']
                    }
      fill_response = exchange_client.get_fills(**fill_params) # assign the response to fill_response
      #Check if there are any fills in the response
      if fill_response and fill_response.get('fills'):
          fill_params_df = pd.DataFrame(fill_response['fills'])
          # Check if 'ticker' and 'no_price' columns exist before accessing them
          if 'ticker' in fill_params_df.columns and 'no_price' in fill_params_df.columns:
              fill_params_df['concat'] = fill_params_df['ticker'] + fill_params_df['no_price'].astype(str) # Convert no_price to string before concatenation
              # print(fill_params_df)
          fill_params_df['created_time_central'] = pd.to_datetime(fill_params_df['created_time'], utc=True).dt.tz_convert('US/Central').dt.strftime('%Y-%m-%d %H:%M:%S')
          spreadsheet_id = '1SDwPpdK6H-78sWY5YYlToi043fYjlc2w2TuBvxUKs3Y'
          range_name = 'Fills'
          append_to_gsheet(fill_params_df, spreadsheet_id, range_name)
