# -*- coding: utf-8 -*-
"""Jane_Kalshi (8).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_c72mJJOsd1PhVipAOhnrQYYIfk78Fs
"""

# Welcome to the Kalshi REST v2 Starter Code!

# pypi client: recommended for more advanced programmers
# import kalshi_python

# starter client: recommended for all levels of programming experience (what this client is implemented using)
from KalshiClientsBaseV2ApiKey_FIXED import ExchangeClient
import pytz

import time
import json
import uuid
import pandas as pd
import numpy as np
import requests
from datetime import datetime, timedelta

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

def load_private_key_from_file(file_path):
    with open(file_path, "rb") as key_file:
        private_key = serialization.load_pem_private_key(
            key_file.read(),
            password=None,  # or provide a password if your key is encrypted
            backend=default_backend()
        )
    return private_key

# To start off, you need to have created an account at https://kalshi.com (Production)
# or an account on the Demo https://demo.kalshi.co/

prod_key_id = "c3204983-77fc-491b-99f7-136600698178" # change these to be your personal credentials
prod_private_key = load_private_key_from_file('/content/Lisa_Kalshi.txt')

demo_key_id = "" # change these to be your personal credentials
# demo_private_key = load_private_key_from_file('kalshi-key.key')

# for prod
prod_api_base = "https://api.elections.kalshi.com/trade-api/v2"

# for demo
demo_api_base = "https://demo-api.kalshi.co/trade-api/v2"

## if wanting to test in prod:
exchange_client = ExchangeClient(exchange_api_base=prod_api_base, key_id = prod_key_id, private_key = prod_private_key)

# first we will check on the exchange status to confirm you are properly connected...
print(exchange_client.get_exchange_status())

import os
###### BIGQUERY SETUP
from google.cloud import bigquery
import google.auth
import pandas as pd
from datetime import datetime
import pytz

# ---- BigQuery Configuration ----
BQ_PROJECT = os.environ.get('GCP_PROJECT_ID', 'elite-contact-446323-q7')
BQ_DATASET = os.environ.get('GCP_DATASET_ID', 'Kalshi')

# ---- Authenticate ----
# Colab: use interactive Google account login (no credentials file needed)
# GitHub Actions / CLI: use GOOGLE_APPLICATION_CREDENTIALS env var or service account file
if not os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"):
    try:
        from google.colab import auth
        auth.authenticate_user()
        print("Authenticated via Colab user account")
    except ImportError:
        pass

credentials, _ = google.auth.default(scopes=['https://www.googleapis.com/auth/bigquery'])
bq_client = bigquery.Client(project=BQ_PROJECT, credentials=credentials)

# ---- Create dataset if it doesn't exist ----
dataset_ref = bigquery.DatasetReference(BQ_PROJECT, BQ_DATASET)
try:
    bq_client.get_dataset(dataset_ref)
    print(f"Dataset {BQ_DATASET} already exists")
except Exception:
    dataset = bigquery.Dataset(dataset_ref)
    dataset.location = 'US'
    bq_client.create_dataset(dataset)
    print(f"Created dataset {BQ_DATASET}")

# ---- Table schemas ----
SCHEMAS = {
    'KXHIGH_market_snapshot': [
        bigquery.SchemaField('city', 'STRING'),
        bigquery.SchemaField('forecast_date', 'DATE'),
        bigquery.SchemaField('run_date', 'TIMESTAMP'),
        bigquery.SchemaField('weather_underground', 'FLOAT64'),
        bigquery.SchemaField('accuweather', 'FLOAT64'),
        bigquery.SchemaField('nws', 'FLOAT64'),
        bigquery.SchemaField('forecast_avg', 'FLOAT64'),
        bigquery.SchemaField('forecast_std', 'FLOAT64'),
        bigquery.SchemaField('forecast_range', 'FLOAT64'),
        bigquery.SchemaField('nws_detailed_conditions', 'STRING'),
        bigquery.SchemaField('nws_short_conditions', 'STRING'),
        bigquery.SchemaField('midnight_temperature', 'FLOAT64'),
        bigquery.SchemaField('event_ticker', 'STRING'),
        bigquery.SchemaField('market_ticker', 'STRING'),
        bigquery.SchemaField('low_range', 'FLOAT64'),
        bigquery.SchemaField('high_range', 'FLOAT64'),
        bigquery.SchemaField('hi_no_price', 'FLOAT64'),
        bigquery.SchemaField('historical_var', 'FLOAT64'),
        bigquery.SchemaField('historical_var_sqrt', 'FLOAT64'),
        bigquery.SchemaField('yes_probability', 'FLOAT64'),
        bigquery.SchemaField('fair_no_price', 'FLOAT64'),
        bigquery.SchemaField('no_highest_bid', 'FLOAT64'),
        bigquery.SchemaField('no_lowest_offer', 'FLOAT64'),
        bigquery.SchemaField('no_orderbook', 'STRING'),
        bigquery.SchemaField('yes_orderbook', 'STRING'),
        bigquery.SchemaField('position', 'INT64'),
    ],
    'KXHIGH_orders': [
        bigquery.SchemaField('city', 'STRING'),
        bigquery.SchemaField('forecast_date', 'DATE'),
        bigquery.SchemaField('run_date', 'TIMESTAMP'),
        bigquery.SchemaField('market_ticker', 'STRING'),
        bigquery.SchemaField('contracts', 'INT64'),
        bigquery.SchemaField('no_price', 'INT64'),
        bigquery.SchemaField('city_abv', 'STRING'),
        bigquery.SchemaField('client_order_id', 'STRING'),
        bigquery.SchemaField('expiration_ts', 'INT64'),
        bigquery.SchemaField('created_at', 'TIMESTAMP'),
    ],
    'KXHIGH_fills': [
        bigquery.SchemaField('trade_id', 'STRING'),
        bigquery.SchemaField('ticker', 'STRING'),
        bigquery.SchemaField('event_ticker', 'STRING'),
        bigquery.SchemaField('side', 'STRING'),
        bigquery.SchemaField('action', 'STRING'),
        bigquery.SchemaField('count', 'INT64'),
        bigquery.SchemaField('yes_price', 'INT64'),
        bigquery.SchemaField('no_price', 'INT64'),
        bigquery.SchemaField('taker_side', 'STRING'),
        bigquery.SchemaField('created_time_utc', 'TIMESTAMP'),
        bigquery.SchemaField('created_time_central', 'TIMESTAMP'),
        bigquery.SchemaField('order_id', 'STRING'),
        bigquery.SchemaField('concat_key', 'STRING'),
    ],
    'KXHIGH_settlements': [
        bigquery.SchemaField('ticker', 'STRING'),
        bigquery.SchemaField('market_result', 'STRING'),
        bigquery.SchemaField('city_abv', 'STRING'),
        bigquery.SchemaField('trade_date', 'DATE'),
        bigquery.SchemaField('settled_time', 'TIMESTAMP'),
        bigquery.SchemaField('yes_count', 'INT64'),
        bigquery.SchemaField('no_count', 'INT64'),
        bigquery.SchemaField('yes_total_cost', 'FLOAT64'),
        bigquery.SchemaField('no_total_cost', 'FLOAT64'),
        bigquery.SchemaField('revenue', 'FLOAT64'),
        bigquery.SchemaField('profit', 'FLOAT64'),
    ],
    'KXHIGH_finalized_markets': [
        bigquery.SchemaField('event_ticker', 'STRING'),
        bigquery.SchemaField('market_ticker', 'STRING'),
        bigquery.SchemaField('city_abv', 'STRING'),
        bigquery.SchemaField('volume_traded', 'INT64'),
        bigquery.SchemaField('avg_trade_price_yes', 'FLOAT64'),
        bigquery.SchemaField('avg_trade_price_no', 'FLOAT64'),
        bigquery.SchemaField('pct_volume_yes_taker', 'FLOAT64'),
        bigquery.SchemaField('pct_volume_no_taker', 'FLOAT64'),
        bigquery.SchemaField('trade_date', 'DATE'),
        bigquery.SchemaField('winning_temp', 'STRING'),
        bigquery.SchemaField('winner', 'STRING'),
    ],
}

# ---- Create tables if they don't exist ----
for table_name, schema in SCHEMAS.items():
    table_ref = dataset_ref.table(table_name)
    try:
        bq_client.get_table(table_ref)
        print(f"  Table {table_name} already exists")
    except Exception:
        table = bigquery.Table(table_ref, schema=schema)
        bq_client.create_table(table)
        print(f"  Created table {table_name}")

# ---- Helper: write DataFrame to BigQuery ----
def write_to_bq(df, table_name, write_disposition='WRITE_APPEND'):
    """
    Append a DataFrame to a BigQuery table.
    Columns are auto-matched by name; extras are dropped.
    """
    table_id = f"{BQ_PROJECT}.{BQ_DATASET}.{table_name}"
    job_config = bigquery.LoadJobConfig(
        write_disposition=write_disposition,
        schema=SCHEMAS.get(table_name),
    )
    try:
        job = bq_client.load_table_from_dataframe(df, table_id, job_config=job_config)
        job.result()  # wait for completion
        print(f"  -> {table_name}: {job.output_rows} rows written")
        return True
    except Exception as e:
        print(f"  -> {table_name} ERROR: {e}")
        return False

print("\nBigQuery setup complete.")

# ---- NWS Station Mapping (Kalshi CLI Settlement Stations) ----
# City              ICAO    Station Name                 Lat        Lon
# Austin            KAUS    Austin-Bergstrom Airport     30.18304   -97.67987
# Miami             KMIA    Miami International          25.79056   -80.31639
# Houston           KHOU    William P. Hobby Airport     29.64542   -95.27889
# Denver            KDEN    Denver International         39.84658   -104.65622
# New York City     KNYC    Central Park                 40.78333   -73.96667
# Philadelphia      KPHL    Philadelphia International   39.87327   -75.22678
# Chicago           KMDW    Chicago Midway               41.78417   -87.75528
# Los Angeles       KLAX    Los Angeles International    33.94250   -118.40806
# Atlanta           KATL    Hartsfield-Jackson           33.64068   -84.42694
# Washington DC     KDCA    Reagan National              38.85208   -77.03772
# Phoenix           KPHX    Sky Harbor                   33.43722   -112.00778
# Dallas            KDFW    DFW Airport                  32.89681   -97.03781
# Las Vegas         KLAS    Harry Reid International     36.08000   -115.15222
# Oklahoma City     KOKC    Will Rogers World            35.39306   -97.60056
# Seattle           KSEA    Seattle-Tacoma               47.44889   -122.30917
# San Francisco     KSFO    SFO Airport                  37.61961   -122.36558
# San Antonio       KSAT    San Antonio International    29.53389   -98.46917
# Minneapolis       KMSP    MSP Airport                  44.88306   -93.22889
# New Orleans       KMSY    Louis Armstrong              29.99333   -90.25806
# ---------------------------------------------------------------

# Determine if current time in Central Time is after 2 PM
central_time = datetime.now(pytz.timezone('US/Central'))
variable = 1 if central_time.hour >= 14 and central_time.hour < 23 else 0

# Define the cities and their coordinates for NWS
cities = {
    "Austin": (30.18304, -97.67987),
    "Miami": (25.79056, -80.31639),
    "Houston": (29.63750, -95.28250),
    "Denver": (39.84658, -104.65622),
    "New York City": (40.78333, -73.96667),
    "Philadelphia": (39.87327, -75.22678),
    "Chicago": (41.78417, -87.75528),
    "Los Angeles": (33.942791, -118.410042),
    "Atlanta": (33.64068, -84.42694),
    "Washington DC": (38.85208, -77.03772),
    "Phoenix": (33.43722, -112.00778),
    "Dallas": (32.89681, -97.03781),
    "Las Vegas": (36.08000, -115.15222),
    "Oklahoma City": (35.39306, -97.60056),
    "Seattle": (47.44889, -122.30917),
    "San Francisco": (37.61961, -122.36558),
    "Houston": (29.64542, -95.27889),
    "San Antonio": (29.53389, -98.46917),
    "Minneapolis": (44.88306, -93.22889),
    "New Orleans": (29.99333, -90.25806)
}

def get_accuweather_forecast(coords):
    try:
        api_key = "lEl0lfAft6PncVXwatr92Y2YjGJL5YKs"  # Replace with your actual API key
        lat, lon = coords

        # Fetch location key from AccuWeather API using geoposition search
        location_url = f"http://dataservice.accuweather.com/locations/v1/cities/geoposition/search"
        location_params = {
            "apikey": api_key,
            "q": f"{lat},{lon}"  # Format coordinates for the API
        }

        location_response = requests.get(location_url, params=location_params)
        location_response.raise_for_status()  # Raise an exception for bad status codes
        location_key = location_response.json()["Key"]  # Extract location key

        # Fetch 5-day forecast for the location key
        forecast_url = f"http://dataservice.accuweather.com/forecasts/v1/daily/5day/{location_key}"
        forecast_params = {
            "apikey": api_key,
            "metric": "false"  # Use Fahrenheit
        }

        forecast_response = requests.get(forecast_url, params=forecast_params)
        forecast_response.raise_for_status()
        forecast = forecast_response.json()

        # Get today or tomorrow's forecast based on 'variable'
        tomorrow_forecast = forecast["DailyForecasts"][variable]
        high_temp = tomorrow_forecast["Temperature"]["Maximum"]["Value"]

        return int(high_temp)

    except Exception as e:
        print(f"Error fetching AccuWeather forecast for {coords}: {e}")
        return "N/A"

# Function to get forecast from NWS
def get_nws_forecast(lat, lon):
    try:
        # Construct NWS API URL
        base_url = f"https://api.weather.gov/points/{lat},{lon}"
        grid_response = requests.get(base_url)
        grid_response.raise_for_status()
        forecast_url = grid_response.json()['properties']['forecast']

        forecast_response = requests.get(forecast_url)
        forecast_response.raise_for_status()
        periods = forecast_response.json()['properties']['periods']

        # Get tomorrow's date
        # tomorrow = (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d')
        dayswitch = (central_time + timedelta(days=variable)).strftime('%Y-%m-%d') #pulling tomorrow or today

        for period in periods:
            if dayswitch in period['startTime'] and "day" in period['name'].lower():
                return period['temperature']  # NWS temperatures are already in Fahrenheit

        return "N/A"
    except Exception as e:
        print(f"Error fetching NWS forecast for {lat}, {lon}: {e}")
        return "N/A"

# Iterate through cities and fetch data
# def get_weatherunderground_forecast(lat, lon):
def get_weatherunderground_forecast(city, coords):
    API_KEY = "a828c2a178844147a8c2a17884a147a5"  # Weather Underground API Key
    lat, lon = coords  # Extract latitude and longitude from coords
    URL = f"https://api.weather.com/v3/wx/forecast/daily/5day?apiKey={API_KEY}&geocode={lat},{lon}&format=json&units=e&language=en-US"

    # Send request
    response = requests.get(URL)

    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()

        # Try extracting the correct temperature field
        if "temperatureMax" in data:
            # Use variable to get today or tomorrow's forecast
            today_high = data["temperatureMax"][variable]
            return today_high
        else:
            print(f"Error: 'temperatureMax' field not found in API response for {city}.")
            return "N/A"  # Return "N/A" if temperature data is not found
    else:
        print(f"Failed to fetch data for {city}. Status code: {response.status_code}, Message: {response.text}")
        return "N/A"  # Return "N/A" if request fails

# Get current run date in Central Time
central_tz = pytz.timezone("US/Central")
run_date = datetime.now(central_tz).strftime('%Y-%m-%d %H:%M:%S')

# Create the DataFrame
forecast_data = []

for city, coords in cities.items():
    nws_temp = get_nws_forecast(*coords)
    accuweather_temp = get_accuweather_forecast(coords)
    weatherundergroud_temp = get_weatherunderground_forecast(city, coords)

    forecast_data.append({
        "City": city,
        "Forecast Date": (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime('%Y-%m-%d'),
        "Run Date": run_date,
        "Weather Underground": weatherundergroud_temp,
        "Accuweather": accuweather_temp,
        "NWS": nws_temp
    })

forecast_table = pd.DataFrame(forecast_data)

# Calculate standard deviation and range for each city
forecast_table[[ "Weather Underground","Accuweather", "NWS"]] = forecast_table[["Weather Underground","Accuweather", "NWS"]].apply(pd.to_numeric, errors='coerce')
forecast_table["Average"] = forecast_table[["Weather Underground", "Accuweather", "NWS"]].mean(axis=1)
forecast_table["Standard Deviation"] = forecast_table[["Weather Underground","Accuweather", "NWS"]].std(axis=1)
forecast_table["Highest Minus Lowest"] = forecast_table[["Weather Underground", "Accuweather", "NWS"]].max(axis=1) - forecast_table[["Weather Underground","Accuweather", "NWS"]].min(axis=1)

# Display the DataFrame
forecast_table

##### GET CONDITIONS FROM NWS

import requests
import pandas as pd
from datetime import datetime, timedelta

# City data with their corresponding location information for NWS API
cities = {
    "Austin": {"lat": 30.2672, "lon": -97.7431},
    "Miami": {"lat": 25.7617, "lon": -80.1918},
    "Houston": {"lat": 29.7604, "lon": -95.3698},
    "Denver": {"lat": 39.7392, "lon": -104.9903},
    "New York City": {"lat": 40.7128, "lon": -74.0060},
    "Philadelphia": {"lat": 39.9526, "lon": -75.1652},
    "Chicago": {"lat": 41.8781, "lon": -87.6298},
    "Los Angeles": {"lat": 33.942791, "lon": -118.410042},
    "Atlanta": {"lat": 33.64068, "lon": -84.42694},
    "Washington DC": {"lat": 38.85208, "lon": -77.03772},
    "Phoenix": {"lat": 33.43722, "lon": -112.00778},
    "Dallas": {"lat": 32.89681, "lon": -97.03781},
    "Las Vegas": {"lat": 36.08000, "lon": -115.15222},
    "Oklahoma City": {"lat": 35.39306, "lon": -97.60056},
    "Seattle": {"lat": 47.44889, "lon": -122.30917},
    "San Francisco": {"lat": 37.61961, "lon": -122.36558},
    "Houston": {"lat": 29.64542, "lon": -95.27889},
    "San Antonio": {"lat": 29.53389, "lon": -98.46917},
    "Minneapolis": {"lat": 44.88306, "lon": -93.22889},
    "New Orleans": {"lat": 29.99333, "lon": -90.25806},
}

# Prepare the date for today
today = datetime.now(pytz.timezone('US/Central')).strftime("%Y-%m-%d")

# Function to fetch weather conditions from NWS
def fetch_nws_conditions(city):
    url = f"https://api.weather.gov/points/{city['lat']},{city['lon']}"
    response = requests.get(url)
    if response.status_code == 200:
        grid_data = response.json()
        forecast_url = grid_data['properties']['forecast']
        forecast_response = requests.get(forecast_url)
        if forecast_response.status_code == 200:
            forecast_data = forecast_response.json()
            # print(forecast_data['properties']['periods'])
            target_date = (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d")

            for period in forecast_data['properties']['periods']:
                # print(period)
                if target_date in period['startTime']:
                    return period['detailedForecast'], period['shortForecast']
    return None, None

# Collect forecast conditions
forecast_conditions = []
for city_name, city_coords in cities.items():
    nws_detailed, nws_short = fetch_nws_conditions(city_coords)
    forecast_conditions.append({
        "City": city_name,
        "NWS Detailed Conditions": nws_detailed,
        "NWS Short Conditions": nws_short
    })

# Create a DataFrame
forecast_conditions_table = pd.DataFrame(forecast_conditions)

forecast_table = pd.merge(forecast_table, forecast_conditions_table, on='City', how='inner')
forecast_table

############# GET MIDNIGHT TEMPS FROM NWS

import requests
from datetime import datetime, timedelta, date
import re
import pandas as pd

# Function to fetch the forecast at midnight through NWS
def fetch_midnight_forecast(coords):
    # Get the grid points URL for the location
    url = f"https://api.weather.gov/points/{coords['lat']},{coords['lon']}"
    response = requests.get(url)
    if response.status_code == 200:
        grid_data = response.json()
        forecast_url = grid_data['properties']['forecastHourly']

        # Fetch hourly forecast for midnight
        midnight_temp = None
        hourly_response = requests.get(forecast_url)
        if hourly_response.status_code == 200:
            hourly_data = hourly_response.json()
            for period in hourly_data['properties']['periods']:
                # Fix invalid ISO format by ensuring proper timezone formatting
                start_time = re.sub(r"([-+]\d{2}):(\d{1})$", r"\1:0\2", period['startTime'])
                # forecast_time = datetime.fromisoformat(start_time)
                forecast_time = datetime.fromisoformat(start_time).astimezone(pytz.timezone('US/Central'))  # Or your desired timezone
                # print((datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d"))
                # print('forecast_time.date() =', forecast_time.date())
                if forecast_time.hour == 0 and forecast_time.minute == 0 and forecast_time.date() == datetime.now(pytz.timezone('US/Central')).date() + timedelta(days=variable):
                # if forecast_time.date() == (datetime.now(pytz.timezone('US/Central')) + timedelta(days=variable)).strftime("%Y-%m-%d"):
                  # print(datetime.now(pytz.timezone('US/Central')).date() + timedelta(days=variable))
                  # print(forecast_time.date())
                  midnight_temp = period['temperature']
                  break
        return midnight_temp
    else:
        print(f"Failed to fetch grid data. Status code: {response.status_code}, URL: {url}")
    return None

# Coordinates for cities
cities = {
    "Austin": {"lat": 30.2672, "lon": -97.7431},
    "Miami": {"lat": 25.7617, "lon": -80.1918},
    "Houston": {"lat": 29.7604, "lon": -95.3698},
    "Denver": {"lat": 39.7392, "lon": -104.9903},
    "New York City": {"lat": 40.7128, "lon": -74.0060},
    "Philadelphia": {"lat": 39.9526, "lon": -75.1652},
    "Chicago": {"lat": 41.8781, "lon": -87.6298},
    "Los Angeles": {"lat": 33.942791, "lon": -118.410042},
    "Atlanta": {"lat": 33.64068, "lon": -84.42694},
    "Washington DC": {"lat": 38.85208, "lon": -77.03772},
    "Phoenix": {"lat": 33.43722, "lon": -112.00778},
    "Dallas": {"lat": 32.89681, "lon": -97.03781},
    "Las Vegas": {"lat": 36.08000, "lon": -115.15222},
    "Oklahoma City": {"lat": 35.39306, "lon": -97.60056},
    "Seattle": {"lat": 47.44889, "lon": -122.30917},
    "San Francisco": {"lat": 37.61961, "lon": -122.36558},
    "Houston": {"lat": 29.64542, "lon": -95.27889},
    "San Antonio": {"lat": 29.53389, "lon": -98.46917},
    "Minneapolis": {"lat": 44.88306, "lon": -93.22889},
    "New Orleans": {"lat": 29.99333, "lon": -90.25806},
}

# Fetch forecasts for all cities
forecasts = []
for city, coords in cities.items():
    midnight_forecast = fetch_midnight_forecast(coords)
    forecasts.append({
        "City": city,
        "Midnight Temperature": midnight_forecast
    })

# Create a DataFrame
forecast_df = pd.DataFrame(forecasts)

forecast_table = pd.merge(forecast_table, forecast_df, on='City', how='inner')

if variable == 0:
  forecast_table['concat'] = forecast_table['City'] + forecast_table['Forecast Date'] + 'Day'
if variable == 1:
  forecast_table['concat'] = forecast_table['City'] + forecast_table['Forecast Date'] + 'Night'

forecast_table

###### WRITE FORECAST DATA TO BIGQUERY (market_snapshot - forecast portion)

# Build a clean DataFrame for the forecast snapshot
forecast_bq = forecast_table.copy()
forecast_bq.columns = [c.lower().replace(' ', '_') for c in forecast_bq.columns]
forecast_bq = forecast_bq.rename(columns={
    'weather_underground': 'weather_underground',
    'accuweather': 'accuweather',
    'nws': 'nws',
    'average': 'forecast_avg',
    'standard_deviation': 'forecast_std',
    'highest_minus_lowest': 'forecast_range',
})

# Convert types for BQ
forecast_bq['forecast_date'] = pd.to_datetime(forecast_bq['forecast_date'])
forecast_bq['run_date'] = pd.to_datetime(forecast_bq['run_date'])
for col in ['weather_underground', 'accuweather', 'nws', 'forecast_avg', 'forecast_std', 'forecast_range', 'midnight_temperature']:
    if col in forecast_bq.columns:
        forecast_bq[col] = pd.to_numeric(forecast_bq[col], errors='coerce')

print(f"Forecast data: {len(forecast_bq)} rows")
forecast_bq

########## DROP ANY WHERE MIDNIGHT TEMP IS WITHIN 5 DEGREES OF TOMORROW'S HIGH

if variable == 1:
  # Ensure 'Average' and 'Midnight Temperature' columns are numeric
  forecast_table['Average'] = pd.to_numeric(forecast_table['Average'], errors='coerce')
  forecast_table['Midnight Temperature'] = pd.to_numeric(forecast_table['Midnight Temperature'], errors='coerce')

  forecast_table = forecast_table[abs(forecast_table['Average'] - forecast_table['Midnight Temperature']) >= 4.5]
forecast_table

########### INPUT EVENT TICKERS, CITIES, HIGHEST NO PRICES, HISTORICAL VARIANCE

# Determine if current time in Central Time is after 2 PM
central_time = datetime.now(pytz.timezone('US/Central'))
variable = 1 if central_time.hour >= 14 else 0

day = central_time + timedelta(days=variable) #pulling tomorrow or today in central time
month = day.strftime("%b").upper()
day = day.strftime("%d")
# print(day)

event_ticker1 = ['KXHIGHCHI-26' + month + day, 'Chicago', 56, 1.7]
event_ticker2 = ['KXHIGHNY-26' + month + day, 'New York City', 41, 1.5]
event_ticker3 = ['KXHIGHDEN-26' + month + day, 'Denver', 60, 2.4]
event_ticker4 = ['KXHIGHPHIL-26' + month + day, 'Philadelphia', 47, 1.6]
event_ticker5 = ['KXHIGHAUS-26' + month + day, 'Austin', 60, 1.7]
event_ticker6 = ['KXHIGHMIA-26' + month + day, 'Miami', 46, 1.1]
# event_ticker7 = ['KXHIGHHOU-26' + month + day, 'Houston', 59, 2.0]
event_ticker8 = ['KXHIGHLAX-26' + month + day, 'Los Angeles', 55, 2.0]
event_ticker9 = ['KXHIGHTATL-26' + month + day, 'Atlanta', 55, 1.8]
event_ticker10 = ['KXHIGHTDC-26' + month + day, 'Washington DC', 50, 1.6]
event_ticker11 = ['KXHIGHTPHX-26' + month + day, 'Phoenix', 55, 1.5]
event_ticker12 = ['KXHIGHTDAL-26' + month + day, 'Dallas', 55, 1.8]
event_ticker13 = ['KXHIGHTLV-26' + month + day, 'Las Vegas', 55, 1.8]
event_ticker14 = ['KXHIGHTOKC-26' + month + day, 'Oklahoma City', 55, 2.0]
event_ticker15 = ['KXHIGHTSEA-26' + month + day, 'Seattle', 50, 1.5]
event_ticker16 = ['KXHIGHTSFO-26' + month + day, 'San Francisco', 50, 1.5]
event_ticker17 = ['KXHIGHTHOU-26' + month + day, 'Houston', 59, 2.0]
event_ticker18 = ['KXHIGHTSATX-26' + month + day, 'San Antonio', 55, 1.8]
event_ticker19 = ['KXHIGHTMIN-26' + month + day, 'Minneapolis', 55, 2.0]
event_ticker20 = ['KXHIGHTNOLA-26' + month + day, 'New Orleans', 55, 1.8]

############ PULL MARKETS
all_event_tickers = [event_ticker1, event_ticker2, event_ticker3, event_ticker4, event_ticker5, event_ticker6, event_ticker8, event_ticker9, event_ticker10, event_ticker11, event_ticker12, event_ticker13, event_ticker14, event_ticker15, event_ticker16, event_ticker17, event_ticker18, event_ticker19, event_ticker20]
event_tickers = pd.DataFrame(all_event_tickers, columns=['Ticker', 'City', 'hi_no_price', 'var'])
event_tickers['var_sqrt'] = np.sqrt(event_tickers['var'])
markets_table = pd.DataFrame(columns=['event_ticker', 'market_ticker', 'market_ticker_prev', 'City', 'low_range', 'high_range', 'hi_no_price'])

for event_ticker in event_tickers['Ticker']:
  event_params = {'event_ticker': event_ticker}
  print(event_ticker)
  event_response = exchange_client.get_event(**event_params)

  for market in event_response['markets']:
      city = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'City'].iloc[0]
      hi_no_price = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'hi_no_price'].iloc[0]
      historical_variance = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'var'].iloc[0]
      historical_variance_sqrt = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'var_sqrt'].iloc[0]
      if "-B" in market['ticker']:
        match = re.search(r"-B(\d+(\.\d+)?)", market['ticker'])
        if match:
          number_after_b = float(match.group(1))
          low_range = number_after_b - 1
          high_range = number_after_b + 1
          markets_table = pd.concat([markets_table, pd.DataFrame([[event_ticker, market['ticker'], city, low_range, high_range, hi_no_price, historical_variance, historical_variance_sqrt]], columns=['event_ticker', 'market_ticker', 'City', 'low_range', 'high_range', 'hi_no_price', 'var', 'var_sqrt'])], ignore_index=True)

      if "-T" in market['ticker']:
        match = re.search(r"-T(\d+(\.\d+)?)", market['ticker'])
        if match:
          number_after_t = float(match.group(1))

          low_range = 0
          high_range = number_after_t - 0.5
          markets_table = pd.concat([markets_table, pd.DataFrame([[event_ticker, market['ticker'], city, low_range, high_range, hi_no_price, historical_variance, historical_variance_sqrt]], columns=['event_ticker', 'market_ticker', 'City', 'low_range', 'high_range', 'hi_no_price', 'var', 'var_sqrt'])], ignore_index=True)

markets_table['market_ticker_prev'] = markets_table['market_ticker'].shift(1)

for index, row in markets_table.iterrows():
  # Skip the first row to avoid the None value in 'market_ticker_prev'
  if index == 0:
    continue
  if "-B" in row['market_ticker_prev'] and "-T" in row['market_ticker']:
    markets_table.loc[index, 'low_range'] = row['high_range'] + 1
    markets_table.loc[index, 'high_range'] = 150

markets_table.drop(columns=['market_ticker_prev'], inplace=True)
markets_table

##### COMBINE FORECAST AND MARKET TABLES, AND CALCULATE PROBABILITIES
from scipy.stats import norm

combined_table = pd.merge(forecast_table, markets_table, on='City', how='inner')

# Convert 'Average' and 'Standard Deviation' columns to numeric, handling errors
combined_table['Average'] = pd.to_numeric(combined_table['Average'], errors='coerce')
combined_table['Standard Deviation'] = pd.to_numeric(combined_table['Standard Deviation'], errors='coerce')

# Replace zeros and NaNs in 'Standard Deviation' with a small positive value
combined_table['Standard Deviation'] = combined_table['Standard Deviation'].replace({0: 1e-6, np.nan: 1e-6})

# Ensure 'high_range' and 'low_range' are numeric
combined_table['high_range'] = pd.to_numeric(combined_table['high_range'], errors='coerce')
combined_table['low_range'] = pd.to_numeric(combined_table['low_range'], errors='coerce')

combined_table['yes_probability'] = norm.cdf(combined_table['high_range'], loc=combined_table['Average'], scale=combined_table['Standard Deviation']) - norm.cdf(combined_table['low_range'], loc=combined_table['Average'], scale=combined_table['Standard Deviation'])
combined_table['yes_probability'] = combined_table['yes_probability'].round(2)
combined_table['fair_no_price'] = 1 - combined_table['yes_probability']
combined_table

####PULL ORDER BOOK OF MARKETS

combined_table['no_highest_bid'] = ''
combined_table['no_lowest_offer'] = ''
combined_table['no_orderbook'] = ''
combined_table['yes_orderbook'] = ''

for index, row in combined_table.iterrows():
  market_ticker = row['market_ticker']
  market_history_params = {'ticker':market_ticker,
                            'depth': 3
                                }
  orderbook_response = exchange_client.get_orderbook(**market_history_params)
  # print(orderbook_response)
  if orderbook_response['orderbook']['no'] and len(orderbook_response['orderbook']['no']) > 0:
    combined_table.loc[index, 'no_highest_bid'] = orderbook_response['orderbook']['no'][-1][0]
  if orderbook_response['orderbook']['yes'] and len(orderbook_response['orderbook']['yes']) > 0:
    combined_table.loc[index, 'no_lowest_offer'] = 100 - orderbook_response['orderbook']['yes'][-1][0]

  # Use .loc to access and modify the DataFrame using the index
  combined_table.loc[index, 'no_orderbook'] = str(orderbook_response['orderbook']['no'])
  combined_table.loc[index, 'yes_orderbook'] = str(orderbook_response['orderbook']['yes'])

combined_table

#If you need to access the detailed orderbook data later, you can use eval() or ast.literal_eval() (safer) to convert the string back to a list of lists:
#import ast
    # orderbook_data = ast.literal_eval(markets_table.loc[index, 'orderbook'])

######### ACTUALS VS FORECAST, FOR BETTING THE HIGH END

# Define column names
columns = ["Austin", "Miami", "Denver", "Houston", "Philadelphia", "New York City", "Chicago", "Los Angeles", "Atlanta", "Washington DC", "Phoenix", "Dallas", "Las Vegas", "Oklahoma City", "Seattle", "San Francisco", "San Antonio", "Minneapolis", "New Orleans"]

# Define row indices
rows = ["5", "4", "3", "2", "1", "0", "-1", "-2", "-3", "-4", "-5"]

# Define data values (converted from percentages to decimals)
data = [
    [0.0270, 0.0256, 0.1290, 0.0000, 0.0000, 0.0270, 0.0333, 0.0667, 0.0300, 0.0270, 0.0300, 0.0270, 0.0300, 0.0400, 0.0300, 0.0300, 0.0270, 0.0400, 0.0300],
    [0.0270, 0.0000, 0.0000, 0.0000, 0.0263, 0.0000, 0.0333, 0.0000, 0.0300, 0.0263, 0.0300, 0.0270, 0.0300, 0.0300, 0.0300, 0.0300, 0.0270, 0.0300, 0.0300],
    [0.0811, 0.0000, 0.0645, 0.1613, 0.1579, 0.1081, 0.1333, 0.0000, 0.0800, 0.1081, 0.0600, 0.0811, 0.0600, 0.1000, 0.0600, 0.0600, 0.0811, 0.1000, 0.0800],
    [0.2432, 0.2308, 0.1290, 0.1935, 0.1053, 0.1622, 0.2333, 0.0000, 0.2000, 0.1622, 0.1500, 0.2432, 0.1500, 0.1800, 0.1500, 0.1500, 0.2432, 0.1800, 0.2000],
    [0.1892, 0.2051, 0.1935, 0.1935, 0.2895, 0.2162, 0.3333, 0.2667, 0.2200, 0.2162, 0.2500, 0.1892, 0.2500, 0.2200, 0.2500, 0.2500, 0.1892, 0.2200, 0.2200],
    [0.1351, 0.2821, 0.1935, 0.0645, 0.1053, 0.2162, 0.0667, 0.2667, 0.1800, 0.2162, 0.2200, 0.1351, 0.2200, 0.1500, 0.2200, 0.2200, 0.1351, 0.1500, 0.1800],
    [0.1892, 0.1282, 0.0645, 0.2258, 0.1053, 0.0811, 0.1000, 0.1333, 0.1200, 0.1053, 0.1200, 0.1892, 0.1200, 0.1000, 0.1200, 0.1200, 0.1892, 0.1000, 0.1200],
    [0.0270, 0.0769, 0.0645, 0.0968, 0.1053, 0.1622, 0.0000, 0.1333, 0.0600, 0.0800, 0.0600, 0.0270, 0.0600, 0.0500, 0.0600, 0.0600, 0.0270, 0.0500, 0.0600],
    [0.0541, 0.0256, 0.0968, 0.0323, 0.0526, 0.0000, 0.0000, 0.0667, 0.0400, 0.0300, 0.0400, 0.0541, 0.0400, 0.0300, 0.0400, 0.0400, 0.0541, 0.0300, 0.0400],
    [0.0000, 0.0000, 0.0323, 0.0000, 0.0263, 0.0000, 0.0333, 0.0000, 0.0100, 0.0263, 0.0100, 0.0000, 0.0100, 0.0200, 0.0100, 0.0100, 0.0000, 0.0200, 0.0100],
    [0.0270, 0.0256, 0.0323, 0.0323, 0.0263, 0.0270, 0.0333, 0.0667, 0.0300, 0.0263, 0.0300, 0.0270, 0.0300, 0.0300, 0.0300, 0.0300, 0.0270, 0.0300, 0.0300]
]

# Create DataFrame
actuals_vs_forecast_variation = pd.DataFrame(data, columns=columns, index=rows)
actuals_vs_forecast_variation = actuals_vs_forecast_variation.transpose()
actuals_vs_forecast_variation['City'] = actuals_vs_forecast_variation.index
print(actuals_vs_forecast_variation.index)
actuals_vs_forecast_variation

##### CALCULATE HIGH RANGE BIDS

x = combined_table[combined_table['high_range'] == 150]

y = pd.DataFrame(columns=['City', 'low_range', 'Average', 'forecast_variation_vs_high_end', 'bid_price'])
forcast_data = round(x['low_range'] - x['Average'])
chart_end_index = [int(chart_index) for chart_index in forcast_data.tolist()]
y['forecast_variation_vs_high_end'] = forcast_data
y['City'] = x['City']
y['low_range'] = x['low_range']
y['Average'] = x['Average']
y = pd.merge(y, actuals_vs_forecast_variation, on='City', how='inner')
filtered_data = [y[str(col)].tolist() for col in range(5, -6, -1)]

# calculate bid_price for each city
percentage_data = list()
for index, value in enumerate(chart_end_index):
  if value > 5:
    value = 5
  if value < -5:
    value = -5
  city_data = [x[index] for x in filtered_data]
  end_index = 5 - value + 1
  # print(value)
  values_to_sum = city_data[0:end_index]
  percentage_data.append(sum(values_to_sum))

y['bid_price'] = [1 - x for x in percentage_data]
y

for index, row in combined_table.iterrows():
  if row['high_range'] == 150:
    # Get the bid_price for the current city from the y DataFrame
    bid_price = y.loc[y['City'] == row['City'], 'bid_price'].iloc[0]
    # Assign the bid_price to the fair_no_price column of the current row
    combined_table.loc[index, 'hi_no_price'] = bid_price * 100 - 15 #20 cent buffer

combined_table

###### WRITE MARKET SNAPSHOT TO BIGQUERY

snapshot_bq = combined_table.copy()

# Standardize column names
col_map = {
    'City': 'city',
    'Forecast Date': 'forecast_date',
    'Run Date': 'run_date',
    'Weather Underground': 'weather_underground',
    'Accuweather': 'accuweather',
    'NWS': 'nws',
    'Average': 'forecast_avg',
    'Standard Deviation': 'forecast_std',
    'Highest Minus Lowest': 'forecast_range',
    'NWS Detailed Conditions': 'nws_detailed_conditions',
    'NWS Short Conditions': 'nws_short_conditions',
    'Midnight Temperature': 'midnight_temperature',
    'event_ticker': 'event_ticker',
    'market_ticker': 'market_ticker',
    'low_range': 'low_range',
    'high_range': 'high_range',
    'hi_no_price': 'hi_no_price',
    'var': 'historical_var',
    'var_sqrt': 'historical_var_sqrt',
    'yes_probability': 'yes_probability',
    'fair_no_price': 'fair_no_price',
    'no_highest_bid': 'no_highest_bid',
    'no_lowest_offer': 'no_lowest_offer',
    'no_orderbook': 'no_orderbook',
    'yes_orderbook': 'yes_orderbook',
    'position': 'position',
}
snapshot_bq = snapshot_bq.rename(columns=col_map)

# Keep only the columns that match the BQ schema
bq_cols = [f.name for f in SCHEMAS['KXHIGH_market_snapshot']]
snapshot_bq = snapshot_bq[[c for c in bq_cols if c in snapshot_bq.columns]]

# Convert types
snapshot_bq['forecast_date'] = pd.to_datetime(snapshot_bq['forecast_date'])
snapshot_bq['run_date'] = pd.to_datetime(snapshot_bq['run_date'])
for col in ['weather_underground', 'accuweather', 'nws', 'forecast_avg', 'forecast_std',
            'forecast_range', 'midnight_temperature', 'low_range', 'high_range',
            'hi_no_price', 'historical_var', 'historical_var_sqrt',
            'yes_probability', 'fair_no_price', 'no_highest_bid', 'no_lowest_offer']:
    if col in snapshot_bq.columns:
        snapshot_bq[col] = pd.to_numeric(snapshot_bq[col], errors='coerce')
if 'position' in snapshot_bq.columns:
    snapshot_bq['position'] = pd.to_numeric(snapshot_bq['position'], errors='coerce').fillna(0).astype('Int64')

# Ensure string columns
for col in ['no_orderbook', 'yes_orderbook', 'nws_detailed_conditions', 'nws_short_conditions']:
    if col in snapshot_bq.columns:
        snapshot_bq[col] = snapshot_bq[col].astype(str)

write_to_bq(snapshot_bq, 'KXHIGH_market_snapshot')
print(f"Market snapshot: {len(snapshot_bq)} rows written to BigQuery")

####### DELETE EXISTING ORDERS

for market_ticker in combined_table['market_ticker']:
  order_params = {'ticker':market_ticker}
  order_response = exchange_client.get_orders(**order_params)

  for i in range(len(order_response['orders'])):
    order_id = order_response['orders'][i]['order_id']
    status = order_response['orders'][i]['status']
    order_id = {'order_id':order_id}
    if order_id is not None and status == 'resting':
      exchange_client.cancel_order(**order_id)

############## PULL CURRENT POSITIONS
for market_ticker in combined_table['market_ticker']:
  positions_params = {'limit': None,
                          'cursor': None,
                          'settlement_status': None,
                          'ticker': market_ticker,
                          'event_ticker': None}
  current_position = exchange_client.get_positions(**positions_params)
  # print(current_position)
  if 'market_positions' in current_position and current_position['market_positions']:
    positions = pd.DataFrame(current_position['market_positions'])

    if 'position' in positions.columns:
      live_positions = positions[positions['position'] != 0]
      if not live_positions.empty:
        row_index = combined_table.index[combined_table['market_ticker'] == market_ticker].tolist()[0]
        combined_table.loc[row_index, 'position'] = abs(live_positions['position'].iloc[0])
  if 'position' not in combined_table.columns:
    combined_table['position'] = 0
  combined_table['position'] = combined_table['position'].fillna(0).astype(int)
  combined_table['resting_order_count'] = 0

combined_table

##### PLACE ORDERS WITH MARKET DIAGNOSTICS

######### BETTING INPUTS
increment = 3
increment1 = 6
price_count = list(range(0, 25))
if central_time.hour > 10 or central_time.hour < 6:
  starting_contracts = 75
else:
  starting_contracts = 50

max_contracts = 1000
max_contracts1 = 1260
market_cutoff_probability = .2
all_orders_placed = []

#################################################### CANCEL CONTRACT TIME
from datetime import datetime, timedelta
import pytz

def get_unix_time_for_tomorrow(hour: int, minute: int, timezone: str = 'US/Central') -> int:
    tz = pytz.timezone(timezone)
    now = datetime.now(tz)
    target_time = tz.localize(
        datetime(year=now.year, month=now.month, day=now.day, hour=hour, minute=minute) + timedelta(days=variable)
    )
    return int(target_time.timestamp())

#################################################### HELPER FUNCTIONS
def format_temp_range(low, high):
    if high == 150: return f"≥{int(low)}°F (high tail)"
    elif low == 0: return f"≤{int(high)}°F (low tail)"
    else: return f"{int(low)}–{int(high)}°F"

def classify_spread(spread):
    if spread <= 7: return "tight"
    elif spread <= 15: return "medium"
    elif spread <= 25: return "wide"
    else: return "very wide"

def print_market_diagnostic(row, market_orders, is_tail):
    ticker = row['market_ticker']
    city = row['City']
    avg_temp = row['Average']
    std_dev = row['Standard Deviation']
    yes_prob = row['yes_probability']
    hi_no = row['hi_no_price']
    position = row.get('position', 0)
    rng = format_temp_range(row['low_range'], row['high_range'])

    no_bid = row.get('no_highest_bid', '')
    no_offer = row.get('no_lowest_offer', '')
    yes_bid = (100 - int(no_offer)) if no_offer != '' else '—'
    no_bid_str = f"{int(no_bid)}¢" if no_bid != '' else '—'
    no_offer_str = f"{int(no_offer)}¢" if no_offer != '' else '—'
    yes_bid_str = f"{yes_bid}¢" if yes_bid != '—' else '—'

    if no_bid != '' and no_offer != '':
        mid_no = (int(no_bid) + int(no_offer)) / 2
        mid_yes = 100 - mid_no
        mid_str = f"(yes_bid={yes_bid_str} + no_bid={no_bid_str}) / 2 → mid_yes={mid_yes:.0f}¢"
        spread = int(no_offer) - int(no_bid)
        book_sum = int(no_bid) + (100 - int(no_offer))
        spread_str = f"{spread}¢ (no_bid={no_bid_str} + yes_bid={yes_bid_str} = {book_sum}¢)"
        spread_class = classify_spread(spread)
    else:
        mid_str = "insufficient book"
        spread_str = "no book"
        spread_class = "no book"

    wu = row.get('Weather Underground', '—')
    accu = row.get('Accuweather', '—')
    nws = row.get('NWS', '—')

    print(f"\n{'─'*80}")
    print(f"  {ticker}:  {city}  {rng}")
    print(f"    Forecast: WU={wu}  AccuW={accu}  NWS={nws}  → Avg={avg_temp:.1f}°F ± {std_dev:.1f}°F")

    if is_tail:
        print(f"    Strategy [Historical Tail]: P(temp in range)={yes_prob*100:.1f}%  hi_no_price={hi_no:.0f}¢ (incl 15¢ buffer)")
    else:
        print(f"    Strategy [Normal CDF]: P(temp in range)={yes_prob*100:.1f}%  hi_no_price={hi_no:.0f}¢")

    fair_yes = int(round(yes_prob * 100))
    fair_no_c = int(round((1 - yes_prob) * 100))
    print(f"    → Fair value: YES={fair_yes}¢, NO={fair_no_c}¢ (sum=100¢)")
    print(f"    Orderbook: Yes={yes_bid_str}, No bid={no_bid_str}, No offer={no_offer_str}")
    print(f"    Mid-price: {mid_str}")
    print(f"    Spread: {spread_str}  [{spread_class}]")

    if position > 0:
        print(f"    Position: {int(position)} contracts")

    if len(market_orders) == 0:
        if yes_prob <= market_cutoff_probability and not is_tail:
            print(f"    → SKIP: P(yes)={yes_prob*100:.1f}% ≤ {market_cutoff_probability*100:.0f}% cutoff")
        elif '-T' in ticker and not is_tail:
            print(f"    → SKIP: low-end tail market (not traded)")
        elif no_offer == '' or no_bid == '':
            print(f"    → SKIP: no orderbook data")
        else:
            print(f"    → NO ORDERS: all bids failed price/position filters")
    else:
        order_strs = []
        total_contracts = 0
        for o in market_orders:
            ev_pct = abs(fair_no_c - o['no_price'])
            order_strs.append(f"{o['no_price']}¢({o['contracts']}c,ev={ev_pct}%)")
            total_contracts += o['contracts']
        if len(order_strs) > 6:
            shown = order_strs[:5] + [f"... +{len(order_strs)-5} more"]
        else:
            shown = order_strs
        print(f"    → NO orders: [{', '.join(shown)}] (placed: {total_contracts}c across {len(market_orders)} tiers)")


#################################################### MAIN ORDER LOOP
print(f"\n{'═'*80}")
print(f"  MARKET DIAGNOSTICS  |  {len(combined_table)} markets  |  starting={starting_contracts}c  |  cutoff={market_cutoff_probability*100:.0f}%")
print(f"{'═'*80}")

for index, row in combined_table.iterrows():
  is_tail = "-T" in row['market_ticker'] and row['high_range'] == 150
  market_orders = []

  qualifies = (row['yes_probability'] > market_cutoff_probability or is_tail) and (
      "-T" not in row['market_ticker'] or is_tail)

  if qualifies:
    i1 = 0
    for i in price_count:
      if "-T" not in row['market_ticker']:
        bid_price = max(row['hi_no_price'] - i * increment, 1)
      if "-T" in row['market_ticker'] and row['high_range'] == 150:
        bid_price = max(row['hi_no_price'] - i * increment1, 1)

      if row['no_lowest_offer'] != '' and bid_price < int(row['no_lowest_offer']) and bid_price < int(row['no_highest_bid']) - 3 and (max_contracts >= row['position'] + row['resting_order_count'] + starting_contracts + i * 10):
        contracts = starting_contracts + i1 * 10
        i1 = i1 + 1

        if 'CHI' in row['market_ticker']:
          abv = 'CHI'; cancel_hour = 10; cancel_minute = 5
        if 'AUS' in row['market_ticker']:
          abv = 'AUS'; cancel_hour = 10; cancel_minute = 5
        if 'HOU' in row['market_ticker']:
          abv = 'HOU'; cancel_hour = 10; cancel_minute = 5
        if 'DEN' in row['market_ticker']:
          abv = 'DEN'; cancel_hour = 10; cancel_minute = 5
        if 'NY-' in row['market_ticker']:
          abv = 'NY-'; cancel_hour = 9; cancel_minute = 5
        if 'PHI' in row['market_ticker']:
          abv = 'PHI'; cancel_hour = 9; cancel_minute = 5
        if 'MIA' in row['market_ticker']:
          abv = 'MIA'; cancel_hour = 9; cancel_minute = 5
        if 'LAX' in row['market_ticker']:
          abv = 'LAX'; cancel_hour = 10; cancel_minute = 5
        if 'ATL' in row['market_ticker']:
          abv = 'ATL'; cancel_hour = 9; cancel_minute = 5
        if 'TDC' in row['market_ticker']:
          abv = 'TDC'; cancel_hour = 9; cancel_minute = 5
        if 'PHX' in row['market_ticker']:
          abv = 'PHX'; cancel_hour = 10; cancel_minute = 5
        if 'DAL' in row['market_ticker']:
          abv = 'DAL'; cancel_hour = 10; cancel_minute = 5
        if 'TLV' in row['market_ticker']:
          abv = 'TLV'; cancel_hour = 10; cancel_minute = 5
        if 'OKC' in row['market_ticker']:
          abv = 'OKC'; cancel_hour = 10; cancel_minute = 5
        if 'SEA' in row['market_ticker']:
          abv = 'SEA'; cancel_hour = 10; cancel_minute = 5
        if 'SFO' in row['market_ticker']:
          abv = 'SFO'; cancel_hour = 10; cancel_minute = 5
        if 'THOU' in row['market_ticker']:
          abv = 'THOU'; cancel_hour = 10; cancel_minute = 5
        if 'SATX' in row['market_ticker']:
          abv = 'SATX'; cancel_hour = 10; cancel_minute = 5
        if 'TMIN' in row['market_ticker']:
          abv = 'TMIN'; cancel_hour = 10; cancel_minute = 5
        if 'NOLA' in row['market_ticker']:
          abv = 'NOLA'; cancel_hour = 10; cancel_minute = 5

        central_time = datetime.now(pytz.timezone('US/Central'))
        if central_time.hour > 10 or central_time.hour < 6:
          cancel_hour = 1; cancel_minute = 59

        client_oid = str(uuid.uuid4())
        exp_ts = get_unix_time_for_tomorrow(cancel_hour, cancel_minute)

        order_params = {'ticker':row['market_ticker'],
                          'client_order_id':client_oid, 'type':'limit',
                          'action':'buy', 'side':'no', 'count':contracts,
                          'yes_price':None, 'no_price':int(bid_price),
                          'expiration_ts':exp_ts, 'sell_position_floor':None,
                          'buy_max_cost':None}
        exchange_client.create_order(**order_params)

        order_rec = {'city': row['City'], 'forecast_date': row['Forecast Date'],
            'run_date': row['Run Date'], 'market_ticker': row['market_ticker'],
            'contracts': contracts, 'no_price': int(bid_price), 'city_abv': abv,
            'client_order_id': client_oid, 'expiration_ts': exp_ts,
            'created_at': datetime.now(pytz.timezone('US/Central')).strftime('%Y-%m-%d %H:%M:%S')}
        market_orders.append(order_rec)
        all_orders_placed.append(order_rec)
        row['resting_order_count'] = row['resting_order_count'] + contracts

  # Print diagnostic for every market
  print_market_diagnostic(row, market_orders, is_tail)

print(f"\n{'═'*80}")
print(f"  SUMMARY: {len(all_orders_placed)} orders placed across {len(combined_table)} markets")
print(f"{'═'*80}\n")

# ---- Write all orders to BigQuery ----
if all_orders_placed:
    orders_df = pd.DataFrame(all_orders_placed)
    orders_df['forecast_date'] = pd.to_datetime(orders_df['forecast_date'])
    orders_df['run_date'] = pd.to_datetime(orders_df['run_date'])
    orders_df['created_at'] = pd.to_datetime(orders_df['created_at'])
    write_to_bq(orders_df, 'KXHIGH_orders')
    print(f"Orders: {len(orders_df)} rows written to BigQuery")
else:
    print("No orders placed this run.")

###### WRITE SETTLEMENTS TO BIGQUERY
# variable = 1
central_tz = pytz.timezone("America/Chicago")
central_now = datetime.now(central_tz)
central_date = central_now.date()

date = central_date - timedelta(days=variable)
month = date.strftime("%b").upper()
day = date.strftime("%d")

settlement_params = {'limit': 1000, 'cursor': None}
settlements = exchange_client.get_portfolio_settlements(**settlement_params)

all_settlements = []

for settlement in settlements['settlements']:
  if variable == 1:
    if settlement['yes_total_cost'] > 0 or settlement['no_total_cost'] > 0:
      settled_time_dt = datetime.strptime(settlement['settled_time'], '%Y-%m-%dT%H:%M:%S.%fZ')
      trade_date_dt = settled_time_dt - timedelta(days=variable)

      if 'HIGH' in settlement['ticker'] and day in settlement['ticker'] and month in settlement['ticker']:
        # Determine city abbreviation
        abv = ''
        for key in ['CHI','AUS','HOU','DEN','NY-','PHI','MIA','LAX','ATL','TDC','PHX','DAL','TLV','OKC','SEA','SFO','THOU','SATX','TMIN','NOLA']:
          if key in settlement['ticker']:
            abv = key
            break

        profit = settlement['revenue'] - settlement['yes_total_cost'] - settlement['no_total_cost']

        all_settlements.append({
            'ticker': settlement['ticker'],
            'market_result': settlement.get('market_result', ''),
            'city_abv': abv,
            'trade_date': trade_date_dt.strftime('%Y-%m-%d'),
            'settled_time': settlement['settled_time'],
            'yes_count': settlement.get('yes_count', 0),
            'no_count': settlement.get('no_count', 0),
            'yes_total_cost': settlement['yes_total_cost'],
            'no_total_cost': settlement['no_total_cost'],
            'revenue': settlement['revenue'],
            'profit': profit,
        })

if all_settlements:
    settlements_df = pd.DataFrame(all_settlements)
    settlements_df['trade_date'] = pd.to_datetime(settlements_df['trade_date'])
    settlements_df['settled_time'] = pd.to_datetime(settlements_df['settled_time'])
    write_to_bq(settlements_df, 'KXHIGH_settlements')
    print(f"Settlements: {len(settlements_df)} rows written to BigQuery")
else:
    print("No settlements to write (variable != 1 or no matching settlements).")

from KalshiClientsBaseV2ApiKey_FIXED import HttpError # Added import for HttpError

# GET FINALIZED MARKET DATA
# variable = 1
central_tz = pytz.timezone("America/Chicago")
central_now = datetime.now(central_tz)
central_date = central_now.date()

date = central_date - timedelta(days=variable)
# date = datetime.strptime('2025-02-18', '%Y-%m-%d') #if you need to fix historicals
month = date.strftime("%b").upper()
day = date.strftime("%d")

event_ticker1 = ['KXHIGHCHI-26' + month + day, 'CHI']
event_ticker2 = ['KXHIGHNY-26' + month + day, 'NY-']
event_ticker3 = ['KXHIGHDEN-26' + month + day, 'DEN']
event_ticker4 = ['KXHIGHPHIL-26' + month + day, 'PHI']
event_ticker5 = ['KXHIGHAUS-26' + month  + day, 'AUS']
event_ticker6 = ['KXHIGHMIA-26' + month + day, 'MIA']
# event_ticker7 = ['KXHIGHHOU-26' + month + day, 'HOU']
event_ticker8 = ['KXHIGHLAX-26' + month + day, 'LAX']
event_ticker9 = ['KXHIGHTATL-26' + month + day, 'ATL']
event_ticker10 = ['KXHIGHTDC-26' + month + day, 'TDC']
event_ticker11 = ['KXHIGHTPHX-26' + month + day, 'PHX']
event_ticker12 = ['KXHIGHTDAL-26' + month + day, 'DAL']
event_ticker13 = ['KXHIGHTLV-26' + month + day, 'TLV']
event_ticker14 = ['KXHIGHTOKC-26' + month + day, 'OKC']
event_ticker15 = ['KXHIGHTSEA-26' + month + day, 'SEA']
event_ticker16 = ['KXHIGHTSFO-26' + month + day, 'SFO']
event_ticker17 = ['KXHIGHTHOU-26' + month + day, 'THOU']
event_ticker18 = ['KXHIGHTSATX-26' + month + day, 'SATX']
event_ticker19 = ['KXHIGHTMIN-26' + month + day, 'TMIN']
event_ticker20 = ['KXHIGHTNOLA-26' + month + day, 'NOLA']
all_event_tickers = [event_ticker1, event_ticker2, event_ticker3, event_ticker4, event_ticker5, event_ticker6, event_ticker8, event_ticker9, event_ticker10, event_ticker11, event_ticker12, event_ticker13, event_ticker14, event_ticker15, event_ticker16, event_ticker17, event_ticker18, event_ticker19, event_ticker20]
event_tickers = pd.DataFrame(all_event_tickers, columns=['Ticker', 'ABV'])
markets_table = pd.DataFrame(columns=['event_ticker', 'market_ticker', 'ABV', 'volume_traded', 'avg_trade_price_yes', 'avg_trade_price_no', 'pct_volume_traded_yes_taker', 'pct_volume_traded_no_taker', 'trade_date', 'winning_temp', 'winner', 'concat'])

if variable == 1:
  trade_date = (central_now - timedelta(days=variable)).strftime('%Y-%m-%d') # Align trade_date with the date calculated for the event tickers.
  # trade_date = '2025-02-18' #if you need to fix historicals
  for event_ticker in event_tickers['Ticker']:
    event_params = {'event_ticker': event_ticker}
    try:
      event_response = exchange_client.get_event(**event_params)
    except HttpError as e:
      print(f"Error fetching event {event_ticker}: {e}")
      continue # Skip to the next event_ticker if there's an error

    abv = event_tickers.loc[event_tickers['Ticker'] == event_ticker, 'ABV'].iloc[0]
    for market in event_response['markets']:
      winning_temp = None
      winning_ticker = None
      winner = None
      concat = abv + trade_date
      if market['result'] == 'yes':
        winning_temp = market['expiration_value']
        winner = 'yes'
        concat = abv + trade_date + winner
      market_params = {'limit':None,
                          'cursor':None,
                          'ticker':market['ticker']}
      try:
        trade_response = exchange_client.get_trades(**market_params)
      except HttpError as e:
        print(f"Error fetching trades for market {market['ticker']}: {e}")
        continue # Skip to the next market if there's an error

      volume_traded = 0
      pct_volume_traded_yes_taker = 0
      pct_volume_traded_no_taker = 0
      avg_trade_price_yes = 0
      avg_trade_price_no = 0

      for trade in trade_response['trades']:
        volume_traded = volume_traded + trade['count']
        avg_trade_price_yes = avg_trade_price_yes + (trade['yes_price'] * trade['count'])
        avg_trade_price_no = avg_trade_price_no + (trade['no_price'] * trade['count'])
        if trade['taker_side'] == 'yes':
          pct_volume_traded_yes_taker = pct_volume_traded_yes_taker + trade['count']
        if trade['taker_side'] == 'no':
          pct_volume_traded_no_taker = pct_volume_traded_no_taker + trade['count']

      # Check if volume_traded is zero before performing division
      if volume_traded != 0:
        avg_trade_price_yes = avg_trade_price_yes / volume_traded
        avg_trade_price_no = avg_trade_price_no / volume_traded
        pct_volume_traded_yes_taker = pct_volume_traded_yes_taker / volume_traded
        pct_volume_traded_no_taker = pct_volume_traded_no_taker / volume_traded
      else:
    # Handle the case where volume_traded is zero, e.g., set averages to 0 or NaN
        avg_trade_price_yes = 0
        avg_trade_price_no = 0
        pct_volume_traded_yes_taker = 0
        pct_volume_traded_no_taker = 0

      markets_table = pd.concat([markets_table, pd.DataFrame([[event_ticker, market['ticker'], abv, volume_traded, avg_trade_price_yes, avg_trade_price_no, pct_volume_traded_yes_taker, pct_volume_traded_no_taker, trade_date, winning_temp, winner, concat]], columns=['event_ticker', 'market_ticker', 'ABV', 'volume_traded', 'avg_trade_price_yes', 'avg_trade_price_no', 'pct_volume_traded_yes_taker', 'pct_volume_traded_no_taker','trade_date','winning_temp', 'winner', 'concat'])], ignore_index=True)

  markets_table

  # ---- Write finalized market data to BigQuery ----
  if not markets_table.empty:
      fin_bq = markets_table.copy()
      fin_bq = fin_bq.rename(columns={
          'ABV': 'city_abv',
          'pct_volume_traded_yes_taker': 'pct_volume_yes_taker',
          'pct_volume_traded_no_taker': 'pct_volume_no_taker',
      })
      # Keep only schema columns
      bq_cols = [f.name for f in SCHEMAS['finalized_markets']]
      fin_bq = fin_bq[[c for c in bq_cols if c in fin_bq.columns]]
      fin_bq['trade_date'] = pd.to_datetime(fin_bq['trade_date'])
      for col in ['volume_traded']:
          fin_bq[col] = pd.to_numeric(fin_bq[col], errors='coerce').fillna(0).astype('Int64')
      for col in ['avg_trade_price_yes', 'avg_trade_price_no', 'pct_volume_yes_taker', 'pct_volume_no_taker']:
          if col in fin_bq.columns:
              fin_bq[col] = pd.to_numeric(fin_bq[col], errors='coerce')
      # Drop the concat column if present (not in schema)
      fin_bq = fin_bq.drop(columns=['concat'], errors='ignore')
      write_to_bq(fin_bq, 'KXHIGH_finalized_markets')
      print(f"Finalized markets: {len(fin_bq)} rows written to BigQuery")
  else:
      print("No finalized market data to write.")

### WRITE FILLS TO BIGQUERY
# variable = 1
if variable == 1:
  all_fills = []
  for event_ticker in event_tickers['Ticker']:
    event_params = {'event_ticker': event_ticker}
    try:
      event_response = exchange_client.get_event(**event_params)
    except Exception as e:
      print(f"Error fetching event {event_ticker}: {e}")
      continue

    for market in event_response['markets']:
      fill_params = {'limit': 1000, 'cursor': None, 'ticker': market['ticker']}
      try:
        fill_response = exchange_client.get_fills(**fill_params)
      except Exception as e:
        print(f"Error fetching fills for {market['ticker']}: {e}")
        continue

      if fill_response and fill_response.get('fills'):
        for fill in fill_response['fills']:
          created_utc = pd.to_datetime(fill.get('created_time'), utc=True)
          created_central = created_utc.tz_convert('US/Central')

          all_fills.append({
              'trade_id': fill.get('trade_id', ''),
              'ticker': fill.get('ticker', ''),
              'event_ticker': event_ticker,
              'side': fill.get('side', ''),
              'action': fill.get('action', ''),
              'count': fill.get('count', 0),
              'yes_price': fill.get('yes_price', 0),
              'no_price': fill.get('no_price', 0),
              'taker_side': fill.get('taker_side', ''),
              'created_time_utc': created_utc,
              'created_time_central': created_central,
              'order_id': fill.get('order_id', ''),
              'concat_key': fill.get('ticker', '') + str(fill.get('no_price', '')),
          })

  if all_fills:
      fills_df = pd.DataFrame(all_fills)
      write_to_bq(fills_df, 'KXHIGH_fills')
      print(f"Fills: {len(fills_df)} rows written to BigQuery")
  else:
      print("No fills to write.")