# -*- coding: utf-8 -*-
"""ncaab_order_script_v42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJy8uotn6qgOSeZO6i4s_A2d1r9C66PT

# KXNCAABMENTION Order Script v4.2-NCAAB

**Adapted from NBA KXNBAMENTION v4.2 with analysis-driven changes:**

| Change | Description |
|---|---|
| NCAAB-1 | Ticker → KXNCAABMENTION |
| NCAAB-2 | SIDE_MULTIPLIERS rewritten — DOUB/TRAN/WALK blocked, safe bundle boosted |
| NCAAB-3 | Game caps halved (MAX_NET 300→150, EVENT 2000→800) |
| NCAAB-4 | NO sweet spot shifted to 50-80¢ (61-86% win rate range) |
| NCAAB-5 | YES_PROBABILITY_FLOOR 40→65 (Yes positions ran -7.7% ROI) |
| NCAAB-6 | Position sizing tightened — min floors raised, tiny bets eliminated |
| NCAAB-7 | Team-specific overrides (ALA+ALLE→flip Yes, MIC+RECO→strong No, etc.) |
| NCAAB-8 | Pairing mode harder to trigger (threshold 0.40→0.60) |
| NCAAB-9 | Base contract sizes reduced (15→10, 20→12, 25→15, 30→18) |
| NCAAB-10 | Validation uses dynamic market codes |

## Step 1: Fetch Data
Run this first to create `df_results`, `df_summary`, `df_summary_rolling`, `df_summary_rolling_by_team`
"""

# STEP 1: FETCH DATA
# FIXED: Team-level historical rates now correct (no longer flipping based on team position)
# ADAPTED: Series ticker changed to KXNCAABMENTION for college basketball

from __future__ import annotations
import time

import pandas as pd
from KalshiClientsBaseV2ApiKey_FIXED import ExchangeClient
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend
import os
import uuid
from datetime import datetime, UTC
from typing import Any, Dict, List, Optional, Tuple
import numpy as np
from google.cloud import bigquery

import uuid
from datetime import datetime, UTC
from typing import Any, Dict, List, Optional, Tuple

# =========================
# CONFIG
# =========================

SERIES_TICKER = "KXNCAABMENTION"  # [NCAAB-1]
API_KEY_ID = os.environ.get("KALSHI_API_KEY_ID", "c3204983-77fc-491b-99f7-136600698178")
PRIVATE_KEY_PATH = os.environ.get("KALSHI_PRIVATE_KEY_PATH", "/content/Lisa_Kalshi.txt")
API_BASE = "https://api.elections.kalshi.com/trade-api/v2"

SLEEP_BETWEEN_CALLS_SEC = 0.05

# =========================
# AUTHENTICATION
# =========================
def load_private_key_from_file(file_path: str):
    with open(file_path, "rb") as key_file:
        private_key = serialization.load_pem_private_key(
            key_file.read(),
            password=None,
            backend=default_backend()
        )
    return private_key

PRIVATE_KEY = load_private_key_from_file(PRIVATE_KEY_PATH)

exchange_client = ExchangeClient(
    exchange_api_base=API_BASE,
    key_id=API_KEY_ID,
    private_key=PRIVATE_KEY
)

print("Testing connection...")
try:
    status = exchange_client.get_exchange_status()
    print(f"✓ Connected! Trading active: {status['trading_active']}")
except Exception as e:
    print(f"✗ Connection failed: {e}")
    raise

# =========================
# API CALLS
# =========================
def get_all_markets_for_series(series_ticker: str, status_filter: str = None) -> List[Dict[str, Any]]:
    all_markets = []
    cursor = None
    page = 0
    while True:
        page += 1
        print(f"  Fetching markets page {page}...")
        params = {"series_ticker": series_ticker, "limit": 200}
        if status_filter:
            params["status"] = status_filter
        if cursor:
            params["cursor"] = cursor
        try:
            response = exchange_client.get_markets(**params)
            markets = response.get('markets', [])
            all_markets.extend(markets)
            print(f"    Retrieved {len(markets)} markets (total: {len(all_markets)})")
            cursor = response.get('cursor')
            if not cursor:
                break
            time.sleep(SLEEP_BETWEEN_CALLS_SEC)
        except Exception as e:
            print(f"Error fetching markets: {e}")
            import traceback
            traceback.print_exc()
            break
    return all_markets

# =========================
# PARSING
# =========================
def normalize_yes_no(result: Any) -> str:
    if result in ("yes", "no"):
        return str(result).upper()
    return ""

def parse_event_code(event_code: str) -> Dict[str, str]:
    event_code = event_code or ""
    date_code = event_code[:7] if len(event_code) >= 7 else ""
    teams_code = event_code[7:] if len(event_code) > 7 else ""
    event_date_iso = ""
    if date_code:
        yy = date_code[:2]
        mmm = date_code[2:5]
        dd = date_code[5:7]
        dc = dd + mmm.title() + yy
        try:
            event_date_iso = datetime.strptime(dc, "%d%b%y").date().isoformat()
        except ValueError:
            event_date_iso = ""
    team_1 = teams_code[:3] if len(teams_code) >= 3 else ""
    team_2 = teams_code[3:] if len(teams_code) > 3 else ""
    return {
        "date_code": date_code, "event_date": event_date_iso,
        "teams_code": teams_code, "team_1": team_1, "team_2": team_2,
    }

def split_market_ticker(ticker: str) -> Dict[str, str]:
    parts = (ticker or "").split("-")
    series = parts[0] if len(parts) > 0 else ""
    event_code = parts[1] if len(parts) > 1 else ""
    market_code = parts[2] if len(parts) > 2 else ""
    parsed = parse_event_code(event_code)
    return {"ticker_part_1_series": series, "ticker_part_2_event_code": event_code,
            "ticker_part_3_market_code": market_code, **parsed}

# =========================
# MAIN DATA COLLECTION
# =========================
def main():
    print(f"\n{'='*70}")
    print(f"FETCHING DATA FOR {SERIES_TICKER}")
    print(f"{'='*70}\n")

    print("Fetching ALL markets...")
    all_markets = get_all_markets_for_series(SERIES_TICKER, status_filter=None)
    print(f"\n✓ Fetched {len(all_markets)} total markets")

    if len(all_markets) == 0:
        print("⚠️  No markets found - returning empty dataframes")
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

    rows: List[Dict[str, Any]] = []
    for m in all_markets:
        market_ticker = m.get("ticker") or ""
        split_cols = split_market_ticker(market_ticker)
        row = {
            "series_ticker": m.get("series_ticker"),
            "event_ticker": m.get("event_ticker"),
            "event_title": m.get("title") or m.get("subtitle") or "",
            "market_ticker": market_ticker,
            "market_status": m.get("status"),
            "result_yes_no": normalize_yes_no(m.get("result")),
        }
        row.update(split_cols)
        rows.append(row)

    df_results = pd.DataFrame(rows)
    print(f"\nBuilt df_results: {df_results.shape}")

    status_counts = df_results['market_status'].value_counts()
    print(f"\nMarket status breakdown:")
    for status, count in status_counts.items():
        print(f"  {status}: {count}")

    active_statuses = ['open', 'active']
    settled_statuses = ['settled', 'finalized', 'closed']
    df_results['is_active'] = df_results['market_status'].isin(active_statuses)
    df_results['is_settled'] = df_results['market_status'].isin(settled_statuses) & (df_results['result_yes_no'] != '')
    print(f"\n  Active/tradeable markets: {df_results['is_active'].sum()}")
    print(f"  Settled markets with results: {df_results['is_settled'].sum()}")

    # BUILD ROLLING SUMMARY
    print("\nBuilding rolling summary (from SETTLED markets only)...")
    df_settled = df_results[df_results['is_settled']].copy()
    print(f"  Using {len(df_settled)} settled markets with results")

    if len(df_settled) == 0:
        print("⚠️  No settled markets found")
        return df_results, pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

    df_by_date = (
        df_settled.query("ticker_part_3_market_code != '' and event_date != ''")
        .groupby(['ticker_part_3_market_code', 'event_date'], as_index=False)
        .agg(count_occurrences=('market_ticker', 'size'),
             count_yes=('result_yes_no', lambda s: (s == 'YES').sum()))
        .sort_values(['ticker_part_3_market_code', 'event_date'])
    )
    if len(df_by_date) == 0:
        return df_results, pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

    df_summary_rolling = df_by_date.copy()
    df_summary_rolling['count_occurrences_rolling'] = df_summary_rolling.groupby('ticker_part_3_market_code')['count_occurrences'].cumsum()
    df_summary_rolling['count_yes_rolling'] = df_summary_rolling.groupby('ticker_part_3_market_code')['count_yes'].cumsum()
    df_summary_rolling['yes_rate_rolling'] = df_summary_rolling['count_yes_rolling'] / df_summary_rolling['count_occurrences_rolling']

    df_summary = (
        df_summary_rolling
        .sort_values(['ticker_part_3_market_code', 'event_date'], ascending=[True, False])
        .groupby('ticker_part_3_market_code', as_index=False).first()
        .drop(columns=['count_occurrences', 'count_yes'])
        .rename(columns={'count_occurrences_rolling': 'count_occurrences',
                         'count_yes_rolling': 'count_yes', 'yes_rate_rolling': 'yes_rate'})
    )
    print(f"  df_summary: {df_summary.shape}")

    # TEAM-LEVEL ROLLING
    print("\nBuilding team-level rolling summary...")
    df_filtered = df_settled.query("ticker_part_3_market_code != '' and event_date != '' and team_1 != '' and team_2 != ''").copy()

    if len(df_filtered) == 0:
        df_summary_filtered = df_summary[df_summary['count_occurrences'] > 25][["ticker_part_3_market_code", "yes_rate"]].copy()
        df_results = df_results.merge(df_summary_filtered, on="ticker_part_3_market_code", how="left")
        df_results["yes_rate"] = df_results.apply(lambda row: row["yes_rate"] if row["is_active"] else "", axis=1)
        return df_results, df_summary, df_summary_rolling, pd.DataFrame()

    df_team1 = df_filtered.copy(); df_team1['team'] = df_team1['team_1']; df_team1['is_team_1'] = True
    df_team2 = df_filtered.copy(); df_team2['team'] = df_team2['team_2']; df_team2['is_team_1'] = False
    df_team_exploded = pd.concat([df_team1, df_team2], ignore_index=True)
    df_team_exploded['team_result'] = df_team_exploded['result_yes_no']

    df_team_by_date = (
        df_team_exploded.groupby(['ticker_part_3_market_code', 'team', 'event_date'], as_index=False)
        .agg(count_occurrences=('market_ticker', 'size'),
             count_yes=('team_result', lambda s: (s == 'YES').sum()))
        .sort_values(['ticker_part_3_market_code', 'team', 'event_date'])
    )

    df_summary_rolling_by_team = df_team_by_date.copy()
    df_summary_rolling_by_team['count_occurrences_rolling'] = df_summary_rolling_by_team.groupby(['ticker_part_3_market_code', 'team'])['count_occurrences'].cumsum()
    df_summary_rolling_by_team['count_yes_rolling'] = df_summary_rolling_by_team.groupby(['ticker_part_3_market_code', 'team'])['count_yes'].cumsum()
    df_summary_rolling_by_team['yes_rate_rolling'] = df_summary_rolling_by_team['count_yes_rolling'] / df_summary_rolling_by_team['count_occurrences_rolling']
    print(f"  df_summary_rolling_by_team: {df_summary_rolling_by_team.shape}")

    # ADD yes_rate TO ACTIVE MARKETS
    df_summary_filtered = df_summary[df_summary['count_occurrences'] > 25][["ticker_part_3_market_code", "yes_rate"]].copy()
    df_results = df_results.merge(df_summary_filtered, on="ticker_part_3_market_code", how="left")
    df_results["yes_rate"] = df_results.apply(lambda row: row["yes_rate"] if row["is_active"] else "", axis=1)
    df_results.loc[df_results['is_active'], 'market_status'] = 'active'

    print(f"\nDataframes created:")
    print(f"  df_results: {df_results.shape}")
    print(f"  df_summary: {df_summary.shape}")
    print(f"  df_summary_rolling: {df_summary_rolling.shape}")
    print(f"  df_summary_rolling_by_team: {df_summary_rolling_by_team.shape}")
    return df_results, df_summary, df_summary_rolling, df_summary_rolling_by_team

df_results, df_summary, df_summary_rolling, df_summary_rolling_by_team = main()
print("\n✓ Data collection complete!")


####################################################################################
#
#  Step 2: Order Script v4.2-NCAAB
#
####################################################################################

RUN_ID = str(uuid.uuid4())
MODEL_VERSION = "v4.2-NCAAB"
PRICING_STRATEGY = 'hybrid'

SERIES_TICKER = "KXNCAABMENTION"
API_KEY_ID = os.environ.get("KALSHI_API_KEY_ID", "c3204983-77fc-491b-99f7-136600698178")
PRIVATE_KEY_PATH = os.environ.get("KALSHI_PRIVATE_KEY_PATH", "/content/Lisa_Kalshi.txt")
API_BASE = "https://api.elections.kalshi.com/trade-api/v2"
SLEEP_BETWEEN_CALLS_SEC = 0.05

BAYESIAN_K = 25
BAYESIAN_RECENCY_HALFLIFE_GAMES = 50
BAYESIAN_MARKET_WEIGHT = 0.6
BAYESIAN_HISTORICAL_WEIGHT = 0.4

MAX_NET_PER_MARKET = 150
POSITION_MODERATE_THRESHOLD = 75
POSITION_STOP_THRESHOLD = 150
MAX_ORDERBOOK_LEVELS_ABOVE = 2
MAX_NET_PER_EVENT = 800
MAX_ORDERS_PER_EVENT = 2000
MIN_SPREAD_BOTH_SIDES = 0
MIN_EV_PER_ORDER = 0.02
SAFE_MODE_MULTIPLIER = 0.10

PAIRING_MODE_THRESHOLD = 0.60
PAIRING_MODE_AGGRESSIVE = 0.85
PAIRING_MODE_NET_FLOOR = int(MAX_NET_PER_MARKET * PAIRING_MODE_THRESHOLD)
PAIRING_MODE_NET_AGGRESSIVE = int(MAX_NET_PER_MARKET * PAIRING_MODE_AGGRESSIVE)
HEDGE_MIN_PRICE_YES = 35
HEDGE_MIN_PRICE_NO = 5
HEDGE_YES_MIN_PRICE = 40
MAX_PAIRED_PER_MARKET = 300

SIDE_MULTIPLIERS = {
    "DOUB": {"yes": 0.0, "no": 0.0},
    "TRAN": {"yes": 0.0, "no": 0.0},
    "WALK": {"yes": 0.0, "no": 0.0},
    "AIRB": {"yes": 0.0, "no": 0.3},
    "ALLE": {"yes": 0.0, "no": 2.0},
    "MARC": {"yes": 0.0, "no": 1.8},
    "NIL":  {"yes": 0.0, "no": 1.8},
    "RECO": {"yes": 0.0, "no": 1.5},
    "ALL":  {"yes": 0.0, "no": 1.5},
    "ELBO": {"yes": 0.0, "no": 1.3},
    "DRAF": {"yes": 0.0, "no": 0.8},
    "RECR": {"yes": 0.0, "no": 0.7},
    "ANKL": {"yes": 0.0, "no": 0.7},
    "SCHE": {"yes": 0.0, "no": 0.7},
    "OVER": {"yes": 0.0, "no": 1.0},
}

TEAM_MARKET_OVERRIDES = {
    ("ALA", "ALLE"): {"yes_mult": 1.5, "no_mult": 0.0},
    ("FLA", "ALLE"): {"yes_mult": 1.2, "no_mult": 0.0},
    ("MIC", "RECO"): {"yes_mult": 0.0, "no_mult": 2.5},
    ("BYU", "RECO"): {"yes_mult": 0.0, "no_mult": 0.0},
    ("ARK", "RECO"): {"yes_mult": 0.0, "no_mult": 0.0},
    ("ILL", "RECO"): {"yes_mult": 0.0, "no_mult": 0.0},
    ("IND", "MARC"): {"yes_mult": 0.0, "no_mult": 0.5},
    ("VAN", "DRAF"): {"yes_mult": 0.0, "no_mult": 2.0},
    ("ILL", "DRAF"): {"yes_mult": 0.0, "no_mult": 2.0},
    ("NEB", "DRAF"): {"yes_mult": 0.0, "no_mult": 2.0},
    ("PUR", "DRAF"): {"yes_mult": 0.0, "no_mult": 1.5},
    ("ALA", "DRAF"): {"yes_mult": 0.0, "no_mult": 0.0},
    ("DUK", "DRAF"): {"yes_mult": 0.0, "no_mult": 0.0},
    ("FLA", "DRAF"): {"yes_mult": 0.0, "no_mult": 0.0},
    ("FLA", "DOUB"): {"yes_mult": 0.0, "no_mult": 0.0},
    ("MSU", "DOUB"): {"yes_mult": 0.0, "no_mult": 0.0},
    ("VAN", "DOUB"): {"yes_mult": 0.0, "no_mult": 1.5},
    ("USC", "DOUB"): {"yes_mult": 0.0, "no_mult": 1.5},
    ("ALA", "TRAN"): {"yes_mult": 0.0, "no_mult": 1.5},
    ("NEB", "TRAN"): {"yes_mult": 0.0, "no_mult": 1.2},
}

MIN_PRICE_YES = 25
MIN_PRICE_NO = 12
MAX_PRICE = 75
YES_MIN_PRICE = 50
NO_MAX_YES_PRICE = 80
NO_MIN_YES_PRICE = 20
YES_PROBABILITY_FLOOR = 65

NO_SWEET_SPOT_MIN = 50
NO_SWEET_SPOT_MAX = 80
NO_SWEET_SPOT_MULTIPLIER = 1.8
MAX_COMBINED_SWEET_BOOST = 2.0

def generate_base_contracts(num_levels: int) -> List[int]:
    contracts = []
    for i in range(num_levels):
        if i < 3: contracts.append(10)
        elif i < 5: contracts.append(12)
        elif i < 8: contracts.append(15)
        else: contracts.append(18)
    return contracts

NUM_OFFSET_LEVELS = 10
BASE_YES_CONTRACTS = generate_base_contracts(NUM_OFFSET_LEVELS)
BASE_NO_CONTRACTS = generate_base_contracts(NUM_OFFSET_LEVELS)
MAX_CONTRACTS_PER_ORDER = 500

TIME_MULTIPLIERS = [(1, 1.8), (3, 1.5), (6, 1.3), (12, 1.1), (24, 1.0), (48, 0.9), (999999, 0.7)]
VOLUME_MULTIPLIERS = [(50000, 1.8), (20000, 1.5), (10000, 1.3), (5000, 1.1), (2000, 1.0), (1000, 0.9), (0, 0.8)]

def generate_offsets(start: int, increment: int, count: int) -> List[int]:
    return [start + i * increment for i in range(count)]

SPREAD_CONFIGS = {
    (0, 2): {'yes': generate_offsets(4, 3, NUM_OFFSET_LEVELS), 'no': generate_offsets(3, 2, NUM_OFFSET_LEVELS), 'name': 'very_tight'},
    (2, 5): {'yes': generate_offsets(3, 3, NUM_OFFSET_LEVELS), 'no': generate_offsets(2, 2, NUM_OFFSET_LEVELS), 'name': 'tight'},
    (5, 15): {'yes': generate_offsets(2, 2, NUM_OFFSET_LEVELS), 'no': generate_offsets(1, 2, NUM_OFFSET_LEVELS), 'name': 'medium'},
    (15, 100): {'yes': generate_offsets(1, 2, NUM_OFFSET_LEVELS), 'no': generate_offsets(1, 1, NUM_OFFSET_LEVELS), 'name': 'wide'},
}
PAIRING_OFFSETS = {'yes': generate_offsets(1, 1, NUM_OFFSET_LEVELS), 'no': generate_offsets(1, 1, NUM_OFFSET_LEVELS), 'name': 'pairing'}
EXPIRATION_HOURS_BEFORE_CLOSE = 5
SLEEP_BETWEEN_ORDERS = 0.05
FALLBACK_OFFSET = 15

def apply_team_overrides(market_code, team_1, team_2, base_yes_mult, base_no_mult):
    override_1 = TEAM_MARKET_OVERRIDES.get((team_1, market_code))
    override_2 = TEAM_MARKET_OVERRIDES.get((team_2, market_code))
    if override_1 is None and override_2 is None:
        return base_yes_mult, base_no_mult, False, "no_override"
    yes_mult, no_mult = base_yes_mult, base_no_mult
    reasons = []
    if override_1 is not None:
        yes_mult = override_1["yes_mult"]; no_mult = override_1["no_mult"]
        reasons.append(f"{team_1}->Y={yes_mult}x,N={no_mult}x")
    if override_2 is not None:
        if override_1 is not None:
            yes_mult = min(yes_mult, override_2["yes_mult"]); no_mult = min(no_mult, override_2["no_mult"])
        else:
            yes_mult = override_2["yes_mult"]; no_mult = override_2["no_mult"]
        reasons.append(f"{team_2}->Y={yes_mult}x,N={no_mult}x")
    return yes_mult, no_mult, True, "; ".join(reasons)

PRIVATE_KEY = load_private_key_from_file(PRIVATE_KEY_PATH)
exchange_client = ExchangeClient(exchange_api_base=API_BASE, key_id=API_KEY_ID, private_key=PRIVATE_KEY)

print("Testing connection...")
try:
    status = exchange_client.get_exchange_status()
    print(f"✓ Connected! Trading active: {status['trading_active']}")
except Exception as e:
    print(f"✗ Connection failed: {e}")
    raise

print(f"\n{'='*70}")
print(f"CONFIGURATION — {MODEL_VERSION}")
print(f"{'='*70}")
print(f"Run ID: {RUN_ID}")
print(f"Series: {SERIES_TICKER}")
print(f"Pricing: {PRICING_STRATEGY} | Bayesian K={BAYESIAN_K}")
print(f"Position caps: market={MAX_NET_PER_MARKET} event={MAX_NET_PER_EVENT}")
print(f"  Moderate at {POSITION_MODERATE_THRESHOLD}, stop at {POSITION_STOP_THRESHOLD}")
print(f"Pairing: threshold={PAIRING_MODE_NET_FLOOR} aggressive={PAIRING_MODE_NET_AGGRESSIVE}")
print(f"Price filters:")
print(f"  YES: {MIN_PRICE_YES}-{MAX_PRICE}c floor={YES_MIN_PRICE}c prob_floor={YES_PROBABILITY_FLOOR}%")
print(f"  NO:  {MIN_PRICE_NO}-{MAX_PRICE}c sweet={NO_SWEET_SPOT_MIN}-{NO_SWEET_SPOT_MAX}c @{NO_SWEET_SPOT_MULTIPLIER}x")
print(f"  EV gate: {MIN_EV_PER_ORDER:.0%}")
blocked = [k for k, v in SIDE_MULTIPLIERS.items() if v['yes'] == 0 and v['no'] == 0]
safe = [k for k, v in SIDE_MULTIPLIERS.items() if v['no'] >= 1.5]
secondary = [k for k, v in SIDE_MULTIPLIERS.items() if 0 < v['no'] < 1.5]
print(f"BLOCKED: {blocked}")
print(f"SAFE BUNDLE (>=1.5x No): {safe}")
print(f"SECONDARY: {secondary}")
print(f"Team overrides: {len(TEAM_MARKET_OVERRIDES)} combos")
print(f"Base contracts: {BASE_YES_CONTRACTS[:5]}...")
print(f"{'='*70}\n")

# =====================================================================
# FILLS-BASED POSITION LEDGER
# =====================================================================

def fetch_fills_from_api(exchange_client_ref, series_ticker=SERIES_TICKER):
    print(f"  Fetching fills from Kalshi API for {series_ticker}...")
    all_fills = []
    cursor = None
    page = 0
    while True:
        page += 1
        params = {"limit": 1000}
        if cursor: params["cursor"] = cursor
        try:
            response = exchange_client_ref.get_fills(**params)
        except Exception as e:
            print(f"  ✗ Error on page {page}: {e}"); break
        batch = response.get("fills", [])
        if not batch: break
        series_fills = [f for f in batch if f.get("ticker", "").startswith(series_ticker)]
        all_fills.extend(series_fills)
        cursor = response.get("cursor")
        if not cursor: break
        if page % 10 == 0: print(f"    Page {page}: {len(all_fills)} fills so far")

    if not all_fills:
        print(f"  No fills found for {series_ticker}")
        return pd.DataFrame()

    df = pd.DataFrame(all_fills)
    print(f"  ✓ Loaded {len(df)} fills across {df['ticker'].nunique()} markets from API")

    # Normalize column names — Kalshi API field names change periodically
    # Old API: yes_price, no_price, count
    # New API: yes_price_dollars, yes_price_fixed, no_price_dollars, no_price_fixed, count_fp
    if 'count_fp' in df.columns and 'contracts' not in df.columns:
        df['contracts'] = pd.to_numeric(df['count_fp'], errors='coerce').astype(int)
        print(f"  Mapped 'count_fp' → 'contracts'")
    elif 'count' in df.columns and 'contracts' not in df.columns:
        df = df.rename(columns={'count': 'contracts'})
        print(f"  Mapped 'count' → 'contracts'")

    if 'yes_price' not in df.columns:
        if 'yes_price_dollars' in df.columns:
            df['yes_price'] = pd.to_numeric(df['yes_price_dollars'], errors='coerce')
            print(f"  Mapped 'yes_price_dollars' → 'yes_price'")
        elif 'yes_price_fixed' in df.columns:
            df['yes_price'] = pd.to_numeric(df['yes_price_fixed'], errors='coerce')
            print(f"  Mapped 'yes_price_fixed' → 'yes_price'")

    if 'yes_price' in df.columns:
        yes_prices = pd.to_numeric(df['yes_price'], errors='coerce')
        max_val = yes_prices.max()
        if max_val <= 1.0:
            df['price'] = df.apply(
                lambda row: float(row['yes_price']) if row.get('side') == 'yes'
                            else (1.0 - float(row['yes_price'])), axis=1)
        else:
            df['price'] = df.apply(
                lambda row: float(row['yes_price']) if row.get('side') == 'yes'
                            else (100.0 - float(row['yes_price'])), axis=1)
    return df


def fetch_fills_from_bq(bq_client, project_id, dataset_id, series_ticker=SERIES_TICKER, lookback_days=30):
    table_id = f"{project_id}.{dataset_id}.{series_ticker}_orders"
    query = f"""
    SELECT ticker, side, price, contracts, order_id, client_order_id, created_at,
           ev, p_hat, total_multiplier, spread_config, spread_cents,
           sweet_spot_applied, pricing_strategy, model_version, run_id
    FROM `{table_id}`
    WHERE ok = TRUE AND created_at >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL {lookback_days} DAY)
    ORDER BY ticker, created_at
    """
    try:
        df = bq_client.query(query).to_dataframe()
        print(f"  ✓ Loaded {len(df)} fills from BQ")
        return df
    except Exception as e:
        print(f"  ✗ BQ error: {e}")
        return pd.DataFrame()


def build_position_ledger(fills_df, price_col="price", contracts_col="contracts"):
    if fills_df is None or len(fills_df) == 0: return {}
    ledger = {}
    df = fills_df.copy()
    df[price_col] = pd.to_numeric(df[price_col], errors="coerce")
    df[contracts_col] = pd.to_numeric(df[contracts_col], errors="coerce")
    df = df.dropna(subset=[price_col, contracts_col])
    max_price_val = df[price_col].max()
    if max_price_val <= 1.0: df[price_col] = df[price_col] * 100
    for ticker, group in df.groupby("ticker"):
        yes_fills = group[group["side"] == "yes"]
        no_fills = group[group["side"] == "no"]
        yes_qty = int(yes_fills[contracts_col].sum())
        no_qty = int(no_fills[contracts_col].sum())
        yes_avg = (yes_fills[price_col] * yes_fills[contracts_col]).sum() / yes_fills[contracts_col].sum() if yes_qty > 0 else 0.0
        no_avg = (no_fills[price_col] * no_fills[contracts_col]).sum() / no_fills[contracts_col].sum() if no_qty > 0 else 0.0
        paired_qty = min(yes_qty, no_qty)
        net_qty = abs(yes_qty - no_qty)
        net_side = "yes" if yes_qty > no_qty else ("no" if no_qty > yes_qty else "flat")
        paired_cost = yes_avg + no_avg if paired_qty > 0 else 0.0
        paired_edge = 100.0 - paired_cost if paired_qty > 0 else 0.0
        yes_total_cost = yes_avg * yes_qty; no_total_cost = no_avg * no_qty
        profit_if_yes = (yes_qty * 100) - yes_total_cost - no_total_cost
        profit_if_no = (no_qty * 100) - yes_total_cost - no_total_cost
        worst_case = min(profit_if_yes, profit_if_no)
        ledger[ticker] = {
            "yes_qty": yes_qty, "no_qty": no_qty,
            "yes_avg_price": round(yes_avg, 2), "no_avg_price": round(no_avg, 2),
            "paired_qty": paired_qty, "net_qty": net_qty, "net_side": net_side,
            "paired_cost": round(paired_cost, 2), "paired_edge": round(paired_edge, 2),
            "yes_total_cost": round(yes_total_cost, 2), "no_total_cost": round(no_total_cost, 2),
            "profit_if_yes_cents": round(profit_if_yes, 2), "profit_if_no_cents": round(profit_if_no, 2),
            "worst_case_cents": round(worst_case, 2),
            "profit_if_yes": round(profit_if_yes / 100, 2), "profit_if_no": round(profit_if_no / 100, 2),
            "worst_case": round(worst_case / 100, 2),
            "paired_profit": round(paired_edge * paired_qty / 100, 2),
        }
    print(f"  ✓ Built ledger for {len(ledger)} markets")
    return ledger


def print_ledger_summary(ledger):
    if not ledger: print("  Ledger is empty"); return
    print(f"\n{'='*70}\nPOSITION LEDGER SUMMARY\n{'='*70}")
    total_paired = sum(v["paired_qty"] for v in ledger.values())
    total_net = sum(v["net_qty"] for v in ledger.values())
    total_paired_profit = sum(v["paired_profit"] for v in ledger.values())
    total_worst_case = sum(v["worst_case"] for v in ledger.values())
    print(f"  Markets: {len(ledger)} | Paired: {total_paired} | Net: {total_net}")
    if (total_paired + total_net) > 0: print(f"  Paired ratio: {total_paired/(total_paired+total_net)*100:.1f}%")
    print(f"  Guaranteed paired profit: ${total_paired_profit:.2f}")
    print(f"  Worst-case total P&L: ${total_worst_case:.2f}")
    sorted_by_profit = sorted(ledger.items(), key=lambda x: x[1]["paired_profit"], reverse=True)
    print(f"\n  TOP 5 BY PAIRED PROFIT:")
    for ticker, data in sorted_by_profit[:5]:
        print(f"    {ticker[-40:]:<45} paired={data['paired_qty']} edge={data['paired_edge']:.1f}c profit=${data['paired_profit']:.2f}")
    print(f"{'='*70}\n")

def ledger_to_dataframe(ledger):
    if not ledger: return pd.DataFrame()
    rows = []
    for ticker, data in ledger.items():
        row = {"ticker": ticker, **data}
        parts = ticker.split("-")
        if len(parts) >= 3: row["market_code"] = parts[-1]; row["event_ticker"] = "-".join(parts[:2])
        rows.append(row)
    return pd.DataFrame(rows).sort_values("paired_profit", ascending=False).reset_index(drop=True)

def integrate_ledger_into_run(exchange_client_ref, bq_client=None, project_id=None,
                               dataset_id=None, series_ticker=SERIES_TICKER,
                               use_api=True, use_bq=True, lookback_days=30):
    print(f"\n{'='*70}\nBUILDING FILLS-BASED POSITION LEDGER\n{'='*70}")
    fills_df = pd.DataFrame()
    if use_api:
        try: fills_df = fetch_fills_from_api(exchange_client_ref, series_ticker)
        except Exception as e: print(f"  ⚠️ API failed: {e}")
    if len(fills_df) == 0 and use_bq and bq_client is not None:
        try: fills_df = fetch_fills_from_bq(bq_client, project_id, dataset_id, series_ticker, lookback_days)
        except Exception as e: print(f"  ⚠️ BQ failed: {e}")
    if len(fills_df) == 0: print("  ⚠️ No fills available"); return {}
    ledger = build_position_ledger(fills_df)
    print_ledger_summary(ledger)
    return ledger

def calculate_hedge_ev(side, bid_price, ledger_data):
    if ledger_data is None: return 0.0, False
    net_side = ledger_data.get("net_side", "flat"); net_qty = ledger_data.get("net_qty", 0)
    if net_qty == 0 or net_side == "flat" or net_side == side: return 0.0, False
    opposite_avg = ledger_data.get("yes_avg_price", 0.0) if side == "no" else ledger_data.get("no_avg_price", 0.0)
    if opposite_avg <= 0: return 0.0, False
    hedge_ev = (100.0 - opposite_avg - bid_price) / 100.0
    if hedge_ev <= 0: return 0.0, True
    return hedge_ev, True

def get_pairing_mode(ticker, ledger, net_position):
    ledger_data = ledger.get(ticker)
    net_qty = ledger_data.get("net_qty", 0) if ledger_data else abs(net_position)
    imbalance_ratio = net_qty / MAX_NET_PER_MARKET if MAX_NET_PER_MARKET > 0 else 0.0
    if net_qty >= PAIRING_MODE_NET_AGGRESSIVE: return "aggressive_pairing", imbalance_ratio
    elif net_qty >= PAIRING_MODE_NET_FLOOR: return "pairing", imbalance_ratio
    return "normal", imbalance_ratio

def get_effective_side_multiplier(base_side_mult, side, pairing_mode, net_side):
    if pairing_mode == "normal" or net_side == side or net_side == "flat": return base_side_mult
    if pairing_mode == "aggressive_pairing": return max(base_side_mult, 1.5)
    elif pairing_mode == "pairing": return max(base_side_mult, 1.0)
    return base_side_mult

def calculate_ledger_position_multiplier(ticker, side, ledger, fallback_net_position):
    data = ledger.get(ticker)
    if data is None: return calculate_position_multiplier(fallback_net_position, side), "no_ledger_data", 0.0
    paired_qty = data["paired_qty"]; net_qty = data["net_qty"]; net_side = data["net_side"]
    side_qty = data["yes_qty"] if side == "yes" else data["no_qty"]
    if side_qty >= MAX_PAIRED_PER_MARKET: return 0.0, f"hard_cap_{side}_qty={side_qty}", 0.0
    if net_side == side and net_qty > 0:
        if net_qty >= MAX_NET_PER_MARKET: return 0.0, f"net_cap_{side}={net_qty}", 0.0
        elif net_qty >= MAX_NET_PER_MARKET * 0.7:
            remaining_frac = (MAX_NET_PER_MARKET - net_qty) / (MAX_NET_PER_MARKET * 0.3)
            return max(0.1, remaining_frac), f"net_rampdown_{side}={net_qty}", 0.0
        return 1.0, f"net_ok_{side}={net_qty}", 0.0
    elif net_side != side and net_side != "flat" and net_qty > 0:
        if net_qty >= PAIRING_MODE_NET_AGGRESSIVE: return 2.0, "aggressive_pair_boost", 1.5
        elif net_qty >= PAIRING_MODE_NET_FLOOR: return 1.5, "pair_boost", 1.0
        elif net_qty >= int(MAX_NET_PER_MARKET * 0.25): return 1.2, "mild_pair_boost", 0.8
        return 1.0, "net_balanced", 0.0
    if paired_qty > MAX_PAIRED_PER_MARKET * 0.6 and data["paired_edge"] > 3:
        return 0.6, "diminishing_returns", 0.0
    return 1.0, "default", 0.0

def calculate_position_multiplier(net_position, side):
    abs_pos = abs(net_position)
    if net_position > 0:
        if side == 'yes':
            if abs_pos >= POSITION_STOP_THRESHOLD: return 0.0
            elif abs_pos >= POSITION_MODERATE_THRESHOLD: return 1.0 - (abs_pos - POSITION_MODERATE_THRESHOLD) / (POSITION_STOP_THRESHOLD - POSITION_MODERATE_THRESHOLD)
            return 1.0
        else:
            if abs_pos >= POSITION_STOP_THRESHOLD: return 2.0
            elif abs_pos >= POSITION_MODERATE_THRESHOLD: return 1.0 + (abs_pos - POSITION_MODERATE_THRESHOLD) / (POSITION_STOP_THRESHOLD - POSITION_MODERATE_THRESHOLD)
            return 1.0
    elif net_position < 0:
        if side == 'no':
            if abs_pos >= POSITION_STOP_THRESHOLD: return 0.0
            elif abs_pos >= POSITION_MODERATE_THRESHOLD: return 1.0 - (abs_pos - POSITION_MODERATE_THRESHOLD) / (POSITION_STOP_THRESHOLD - POSITION_MODERATE_THRESHOLD)
            return 1.0
        else:
            if abs_pos >= POSITION_STOP_THRESHOLD: return 2.0
            elif abs_pos >= POSITION_MODERATE_THRESHOLD: return 1.0 + (abs_pos - POSITION_MODERATE_THRESHOLD) / (POSITION_STOP_THRESHOLD - POSITION_MODERATE_THRESHOLD)
            return 1.0
    return 1.0

def cancel_all_existing_orders_batch():
    print(f"\n{'='*70}\nCANCELING ORDERS FOR {SERIES_TICKER}\n{'='*70}")
    try:
        all_orders = []; cursor = None; page = 0
        while True:
            page += 1; params = {"limit": 500}
            if cursor: params["cursor"] = cursor
            response = exchange_client.get_orders(**params)
            batch = response.get('orders', []); all_orders.extend(batch)
            cursor = response.get('cursor')
            if not cursor: break
        series_orders = [o for o in all_orders if o.get('status') == 'resting' and o.get('ticker', '').startswith(SERIES_TICKER)]
        print(f"Found {len(series_orders)} resting {SERIES_TICKER} orders to cancel")
        if len(series_orders) == 0: return 0
        order_ids = [o['order_id'] for o in series_orders]; canceled = 0
        for i in range(0, len(order_ids), 100):
            chunk = order_ids[i:i+100]
            try:
                if hasattr(exchange_client, 'cancel_orders'): exchange_client.cancel_orders(order_ids=chunk); canceled += len(chunk)
                else:
                    for oid in chunk:
                        try: exchange_client.cancel_order(order_id=oid); canceled += 1
                        except: pass
                time.sleep(0.1)
            except:
                for oid in chunk:
                    try: exchange_client.cancel_order(order_id=oid); canceled += 1
                    except: pass
        print(f"✓ Canceled {canceled}/{len(order_ids)} orders\n"); return canceled
    except Exception as e: print(f"✗ Error: {e}\n"); return 0

def get_existing_positions():
    print(f"\n{'='*70}\nCHECKING EXISTING POSITIONS FOR {SERIES_TICKER}\n{'='*70}")
    try:
        all_positions_raw = []; cursor = None
        while True:
            params = {"limit": 1000}
            if cursor: params["cursor"] = cursor
            response = exchange_client.get_positions(**params)
            batch = response.get('market_positions', []); all_positions_raw.extend(batch)
            cursor = response.get('cursor')
            if not cursor: break
            time.sleep(0.05)
        positions = {}
        for pos in all_positions_raw:
            ticker = pos.get('ticker', '')
            if not ticker.startswith(SERIES_TICKER): continue
            net_position = pos.get('position', 0) or 0
            if net_position == 0: continue
            positions[ticker] = {'net_position': net_position}
        if positions:
            total_net = sum(abs(p['net_position']) for p in positions.values())
            print(f"✓ {len(positions)} markets with positions, {total_net} total net exposure")
        else: print("  No non-zero positions found")
        print(); return positions, True
    except Exception as e:
        print(f"⚠️  Error: {e}\n  ⚠️  SAFE MODE — {SAFE_MODE_MULTIPLIER:.0%} sizing\n"); return {}, False

def cents_from_rate(rate):
    if rate is None or pd.isna(rate): raise ValueError("rate is NaN")
    return int(round(float(rate) * 100))

def get_market_details(market_ticker):
    try:
        resp = exchange_client.get_market(ticker=market_ticker); md = resp.get('market', {})
        close_time = md.get('close_time'); expiration_ts = None
        if close_time:
            ts = close_time
            if ts.endswith('Z'): ts = ts[:-1] + '+00:00'
            dt = datetime.fromisoformat(ts); close_unix = int(dt.timestamp())
            expiration_ts = close_unix - (EXPIRATION_HOURS_BEFORE_CLOSE * 3600)
            if expiration_ts <= time.time(): expiration_ts = None
        return expiration_ts, md.get('open_interest', 0), md.get('volume', 0)
    except: return None, None, None

def get_time_multiplier(hours):
    for threshold, mult in TIME_MULTIPLIERS:
        if hours < threshold: return mult
    return 0.5

def get_volume_multiplier(oi):
    for threshold, mult in VOLUME_MULTIPLIERS:
        if oi >= threshold: return mult
    return 0.4

def get_offsets_for_spread(spread_cents):
    for (mn, mx), config in SPREAD_CONFIGS.items():
        if mn <= spread_cents < mx: return config['yes'], config['no'], config['name']
    wc = SPREAD_CONFIGS[(15, 100)]; return wc['yes'], wc['no'], wc['name']

def calculate_spread(yes_bid, no_bid): return 100 - (yes_bid + no_bid)

def parse_orderbook(orderbook_data):
    if not orderbook_data: return None, None
    best_bid = max(level[0] for level in orderbook_data)
    idx = next(i for i, level in enumerate(orderbook_data) if level[0] == best_bid)
    return best_bid, orderbook_data[idx][1]

def calculate_hybrid_price_bayesian(market_mid, market_yes_rate, market_sample_size,
                                     team_1_yes_rate, team_1_sample_size, team_2_yes_rate, team_2_sample_size):
    intermediates = {}; market_mid_rate = market_mid / 100
    if market_yes_rate is None or pd.isna(market_yes_rate): return market_mid_rate, {"fallback": "no_market_yes_rate"}
    team_rates, team_weights = [], []
    if team_1_sample_size > 0 and team_1_yes_rate is not None and not pd.isna(team_1_yes_rate): team_rates.append(team_1_yes_rate); team_weights.append(team_1_sample_size)
    if team_2_sample_size > 0 and team_2_yes_rate is not None and not pd.isna(team_2_yes_rate): team_rates.append(team_2_yes_rate); team_weights.append(team_2_sample_size)
    if team_rates: ttw = sum(team_weights); avg_team = sum(r*w for r,w in zip(team_rates, team_weights))/ttw; combined_n = ttw
    else: avg_team = market_yes_rate; combined_n = 0
    cred = min(combined_n / BAYESIAN_K, 1.0) if combined_n > 0 else 0.0
    posterior = (1-cred)*market_yes_rate + cred*avg_team if combined_n > 0 else market_yes_rate
    n = max(market_sample_size, 0); recency = 2 ** (-n / BAYESIAN_RECENCY_HALFLIFE_GAMES)
    hw = BAYESIAN_HISTORICAL_WEIGHT * (1.0 - 0.5*(1.0-recency)); mw = BAYESIAN_MARKET_WEIGHT
    tw = mw + hw; mw /= tw; hw /= tw
    return mw * market_mid_rate + hw * posterior, intermediates

def calculate_bid_price(market_mid_yes, market_yes_rate, team_1_yes_rate, team_1_sample_size,
                        team_2_yes_rate, team_2_sample_size, market_sample_size, strategy):
    if strategy == 'hybrid':
        if market_mid_yes is None:
            if market_yes_rate is None or pd.isna(market_yes_rate): return None, None, {}
            yp = cents_from_rate(market_yes_rate); return yp, 100-yp, {"fallback": "no_orderbook"}
        hyb, inter = calculate_hybrid_price_bayesian(market_mid_yes, market_yes_rate, market_sample_size,
            team_1_yes_rate, team_1_sample_size, team_2_yes_rate, team_2_sample_size)
        yp = int(hyb * 100); return yp, 100-yp, inter
    elif strategy == 'market':
        if market_mid_yes is not None: yp = int(round(market_mid_yes)); return yp, 100-yp, {}
        return None, None, {}
    elif strategy == 'historical':
        if market_yes_rate is None or pd.isna(market_yes_rate): return None, None, {}
        yp = cents_from_rate(market_yes_rate); return yp, 100-yp, {}
    raise ValueError(f"Unknown strategy: {strategy}")

market_snapshots = []

def build_order_objects_for_market(market_row, existing_positions, event_net_exposure,
                                    event_orders_placed, safe_mode, ledger):
    ticker = market_row.get("market_ticker"); market_status = market_row.get("market_status")
    market_yes_rate = market_row.get("market_yes_rate"); market_sample_size = market_row.get("market_sample_size", 0)
    team_1_yes_rate = market_row.get("team_1_yes_rate"); team_1_sample_size = market_row.get("team_1_sample_size", 0)
    team_2_yes_rate = market_row.get("team_2_yes_rate"); team_2_sample_size = market_row.get("team_2_sample_size", 0)
    event_ticker = market_row.get("event_ticker"); ticker_part_3_market_code = market_row.get("ticker_part_3_market_code")
    team_1 = market_row.get("team_1"); team_2 = market_row.get("team_2")
    if market_status != "active": return []
    side_config = SIDE_MULTIPLIERS.get(ticker_part_3_market_code, {"yes": 1.0, "no": 1.0})
    yes_side_mult_base = side_config.get("yes", 1.0); no_side_mult_base = side_config.get("no", 1.0)
    team_yes, team_no, override_applied, override_reason = apply_team_overrides(
        ticker_part_3_market_code, team_1 or "", team_2 or "", yes_side_mult_base, no_side_mult_base)
    if override_applied:
        print(f"    [NCAAB-7] Team override: {override_reason}")
        yes_side_mult_base = team_yes; no_side_mult_base = team_no
    if yes_side_mult_base == 0.0 and no_side_mult_base == 0.0:
        reason = f"team override ({override_reason})" if override_applied else "config"
        print(f"    ⛔ BOTH SIDES 0x for {ticker_part_3_market_code} — skipping ({reason})"); return []
    position_data = existing_positions.get(ticker, {'net_position': 0}); net_position = position_data['net_position']
    ledger_data = ledger.get(ticker)
    pairing_mode_str, imbalance_ratio = get_pairing_mode(ticker, ledger, net_position)
    net_side = ledger_data.get("net_side", "flat") if ledger_data else ("yes" if net_position > 0 else ("no" if net_position < 0 else "flat"))
    if pairing_mode_str != "normal": print(f"    PAIRING: {pairing_mode_str.upper()} (imbalance: {imbalance_ratio:.0%}, net: {net_side})")
    yes_side_mult = yes_side_mult_base; no_side_mult = no_side_mult_base
    expiration_ts, open_interest, volume = get_market_details(ticker)
    if expiration_ts is None: print(f"    ✗ No expiration — skipping"); return []
    hours_until_event = (expiration_ts - time.time()) / 3600.0
    if open_interest is None: open_interest = 0
    if volume is None: volume = 0
    yes_side_mult_floor, no_side_mult_floor = 0.0, 0.0
    if ledger:
        yes_position_mult, yes_pos_reason, yes_side_mult_floor = calculate_ledger_position_multiplier(ticker, 'yes', ledger, net_position)
        no_position_mult, no_pos_reason, no_side_mult_floor = calculate_ledger_position_multiplier(ticker, 'no', ledger, net_position)
    else:
        yes_position_mult = calculate_position_multiplier(net_position, 'yes')
        no_position_mult = calculate_position_multiplier(net_position, 'no')
    if yes_side_mult_floor > 0 and yes_side_mult < yes_side_mult_floor: yes_side_mult = yes_side_mult_floor
    if no_side_mult_floor > 0 and no_side_mult < no_side_mult_floor: no_side_mult = no_side_mult_floor
    yes_side_mult = get_effective_side_multiplier(yes_side_mult, "yes", pairing_mode_str, net_side)
    no_side_mult = get_effective_side_multiplier(no_side_mult, "no", pairing_mode_str, net_side)
    net_room_yes = MAX_NET_PER_MARKET - net_position; net_room_no = MAX_NET_PER_MARKET + net_position
    time_mult = get_time_multiplier(hours_until_event); volume_mult = get_volume_multiplier(open_interest)
    base_mult = time_mult * volume_mult; safe_mult = SAFE_MODE_MULTIPLIER if safe_mode else 1.0
    yes_total_mult = base_mult * yes_position_mult * yes_side_mult * safe_mult
    no_total_mult = base_mult * no_position_mult * no_side_mult * safe_mult
    print(f"    Time: {hours_until_event:.1f}h ({time_mult:.2f}x) | OI: {open_interest} ({volume_mult:.2f}x)")
    orderbook_yes_bid, yes_bid_size, orderbook_no_bid, no_bid_size = None, None, None, None
    try:
        ob_resp = exchange_client.get_orderbook(ticker=ticker, depth=10)
        ob = ob_resp.get('orderbook', ob_resp); yes_data, no_data = ob.get('yes', []), ob.get('no', [])
        if yes_data: orderbook_yes_bid, yes_bid_size = parse_orderbook(yes_data)
        if no_data: orderbook_no_bid, no_bid_size = parse_orderbook(no_data)
    except: pass
    market_mid_yes = None
    if orderbook_yes_bid is not None and orderbook_no_bid is not None: market_mid_yes = (orderbook_yes_bid + (100 - orderbook_no_bid)) / 2.0
    elif orderbook_yes_bid is not None: market_mid_yes = float(orderbook_yes_bid)
    elif orderbook_no_bid is not None: market_mid_yes = 100.0 - orderbook_no_bid
    yes_fair, no_fair, bayesian_inter = calculate_bid_price(market_mid_yes, market_yes_rate, team_1_yes_rate, team_1_sample_size,
        team_2_yes_rate, team_2_sample_size, market_sample_size, PRICING_STRATEGY)
    if yes_fair is None and market_yes_rate is not None and not pd.isna(market_yes_rate):
        yes_fair = cents_from_rate(market_yes_rate); no_fair = 100 - yes_fair
    if yes_fair is None or no_fair is None: print(f"    ✗ No data — skipping"); return []
    p_hat = yes_fair / 100.0
    print(f"    Fair: YES={yes_fair}c NO={no_fair}c | Mults: YES={yes_total_mult:.2f}x NO={no_total_mult:.2f}x")
    if pairing_mode_str == "aggressive_pairing": act_min_yes, act_min_no, act_yes_min = HEDGE_MIN_PRICE_YES, HEDGE_MIN_PRICE_NO, HEDGE_YES_MIN_PRICE
    elif pairing_mode_str == "pairing":
        act_min_yes = (MIN_PRICE_YES + HEDGE_MIN_PRICE_YES) // 2; act_min_no = (MIN_PRICE_NO + HEDGE_MIN_PRICE_NO) // 2
        act_yes_min = (YES_MIN_PRICE + HEDGE_YES_MIN_PRICE) // 2
    else: act_min_yes, act_min_no, act_yes_min = MIN_PRICE_YES, MIN_PRICE_NO, YES_MIN_PRICE
    if yes_fair < YES_PROBABILITY_FLOOR and yes_side_mult > 0:
        if pairing_mode_str != "normal" and net_side == "no": pass
        else: yes_side_mult = 0.0; yes_total_mult = 0.0
    spread_cents = calculate_spread(orderbook_yes_bid or yes_fair, orderbook_no_bid or no_fair)
    yes_offsets, no_offsets, spread_config_name = get_offsets_for_spread(spread_cents)
    if pairing_mode_str != "normal" and net_side != "flat":
        if net_side == "yes": no_offsets = PAIRING_OFFSETS['no']; spread_config_name += "+pair_no"
        elif net_side == "no": yes_offsets = PAIRING_OFFSETS['yes']; spread_config_name += "+pair_yes"
    evt = event_ticker or ""; current_event_orders = event_orders_placed.get(evt, 0)
    event_orders_remaining = MAX_ORDERS_PER_EVENT - current_event_orders
    if event_orders_remaining <= 0: print(f"    ⛔ Event cap reached — skipping"); return []
    market_snapshots.append({"market_ticker": ticker, "run_id": RUN_ID, "model_version": MODEL_VERSION,
        "yes_fair": yes_fair, "no_fair": no_fair, "pairing_mode": pairing_mode_str})
    orders = []
    max_yes_price = (orderbook_yes_bid + MAX_ORDERBOOK_LEVELS_ABOVE) if orderbook_yes_bid else MAX_PRICE; yes_placed = 0
    if yes_total_mult > 0:
        for i, offset in enumerate(yes_offsets):
            if i >= len(BASE_YES_CONTRACTS): break
            bid = yes_fair - offset
            if bid > max_yes_price or bid < act_min_yes or bid > MAX_PRICE or bid < act_yes_min: continue
            standalone_ev = p_hat - (bid / 100.0); hedge_ev, is_pairing = calculate_hedge_ev("yes", bid, ledger_data)
            effective_ev = max(standalone_ev, hedge_ev) if is_pairing else standalone_ev
            if effective_ev < MIN_EV_PER_ORDER: continue
            base_c = BASE_YES_CONTRACTS[i]; scaled = int(base_c * yes_total_mult)
            max_here = min(scaled, MAX_CONTRACTS_PER_ORDER, max(0, net_room_yes - yes_placed), max(0, event_orders_remaining - yes_placed))
            if max_here < 1: continue
            yes_placed += max_here
            orders.append({"ticker": ticker, "action": "buy", "side": "yes", "count": max_here,
                "type": "limit", "yes_price": bid, "no_price": None, "expiration_ts": expiration_ts, "post_only": True,
                "client_order_id": str(uuid.uuid4()), "run_id": RUN_ID, "model_version": MODEL_VERSION,
                "spread_config": spread_config_name, "spread_cents": spread_cents,
                "time_multiplier": time_mult, "volume_multiplier": volume_mult,
                "position_multiplier": yes_position_mult, "side_multiplier": yes_side_mult,
                "boost_multiplier": yes_side_mult, "total_multiplier": yes_total_mult,
                "base_contracts": base_c, "hours_until_event": hours_until_event,
                "open_interest": open_interest, "net_position": net_position,
                "ev": round(effective_ev, 4), "standalone_ev": round(standalone_ev, 4),
                "hedge_ev": round(hedge_ev, 4) if is_pairing else None,
                "is_pairing_order": is_pairing, "pairing_mode": pairing_mode_str,
                "p_hat": round(p_hat, 4), "pricing_strategy": PRICING_STRATEGY,
                "safe_mode": safe_mode, "event_ticker": event_ticker})
    max_no_price = (orderbook_no_bid + MAX_ORDERBOOK_LEVELS_ABOVE) if orderbook_no_bid else MAX_PRICE; no_placed = 0
    if no_total_mult > 0:
        for i, offset in enumerate(no_offsets):
            if i >= len(BASE_NO_CONTRACTS): break
            bid = no_fair - offset
            if bid > max_no_price or bid < act_min_no or bid > MAX_PRICE: continue
            implied_yes = 100 - bid
            if implied_yes < NO_MIN_YES_PRICE or implied_yes > NO_MAX_YES_PRICE: continue
            standalone_ev = (1.0 - p_hat) - (bid / 100.0); hedge_ev, is_pairing = calculate_hedge_ev("no", bid, ledger_data)
            effective_ev = max(standalone_ev, hedge_ev) if is_pairing else standalone_ev
            if effective_ev < MIN_EV_PER_ORDER: continue
            base_c = BASE_NO_CONTRACTS[i]; scaled = int(base_c * no_total_mult)
            sweet_applied = False
            if NO_SWEET_SPOT_MIN <= bid <= NO_SWEET_SPOT_MAX:
                effective_sweet = min(NO_SWEET_SPOT_MULTIPLIER, MAX_COMBINED_SWEET_BOOST / max(no_side_mult, 0.1))
                scaled = int(scaled * effective_sweet); sweet_applied = True
            max_here = min(scaled, MAX_CONTRACTS_PER_ORDER, max(0, net_room_no - no_placed),
                          max(0, event_orders_remaining - yes_placed - no_placed))
            if max_here < 1: continue
            no_placed += max_here
            orders.append({"ticker": ticker, "action": "buy", "side": "no", "count": max_here,
                "type": "limit", "yes_price": None, "no_price": bid, "expiration_ts": expiration_ts, "post_only": True,
                "client_order_id": str(uuid.uuid4()), "run_id": RUN_ID, "model_version": MODEL_VERSION,
                "spread_config": spread_config_name, "spread_cents": spread_cents,
                "time_multiplier": time_mult, "volume_multiplier": volume_mult,
                "position_multiplier": no_position_mult, "side_multiplier": no_side_mult,
                "boost_multiplier": no_side_mult, "total_multiplier": no_total_mult,
                "sweet_spot_applied": sweet_applied, "base_contracts": base_c,
                "hours_until_event": hours_until_event, "open_interest": open_interest, "net_position": net_position,
                "ev": round(effective_ev, 4), "standalone_ev": round(standalone_ev, 4),
                "hedge_ev": round(hedge_ev, 4) if is_pairing else None,
                "is_pairing_order": is_pairing, "pairing_mode": pairing_mode_str,
                "p_hat": round(p_hat, 4), "pricing_strategy": PRICING_STRATEGY,
                "safe_mode": safe_mode, "event_ticker": event_ticker})
    if yes_placed > 0: print(f"    → YES: {yes_placed} contracts")
    if no_placed > 0: print(f"    → NO:  {no_placed} contracts")
    if yes_placed == 0 and no_placed == 0: print(f"    → No orders passed filters")
    evt = event_ticker or ""
    event_orders_placed[evt] = event_orders_placed.get(evt, 0) + yes_placed + no_placed
    event_net_exposure[evt] = event_net_exposure.get(evt, 0) + abs(yes_placed - no_placed)
    return orders

def submit_orders_sequential(orders):
    results = []; total = len(orders); print(f"Submitting {total} orders..."); start = time.time()
    for i, op in enumerate(orders):
        if i % 50 == 0 and i > 0: print(f"  Progress: {i}/{total} ({i*100//total}%)")
        metadata = {k: op.pop(k) for k in ["run_id","model_version","spread_config","spread_cents","time_multiplier",
            "volume_multiplier","position_multiplier","side_multiplier","boost_multiplier","total_multiplier",
            "base_contracts","hours_until_event","open_interest","net_position","ev","standalone_ev","hedge_ev",
            "is_pairing_order","pairing_mode","p_hat","pricing_strategy","safe_mode","event_ticker"] if k in op}
        metadata["sweet_spot_applied"] = op.pop("sweet_spot_applied", False)
        ts = datetime.now(UTC).isoformat()
        try:
            response = exchange_client.create_order(**op)
            results.append({"ok": True, "ticker": op["ticker"], "side": op["side"],
                "price": op.get("yes_price") or op.get("no_price"), "contracts": op["count"],
                "order_id": response.get("order",{}).get("order_id"), "error": None, "created_at": ts, **metadata})
        except Exception as e:
            results.append({"ok": False, "ticker": op["ticker"], "side": op["side"],
                "price": op.get("yes_price") or op.get("no_price"), "contracts": op["count"],
                "error": str(e), "order_id": None, "created_at": ts, **metadata})
        time.sleep(SLEEP_BETWEEN_ORDERS)
    elapsed = time.time() - start; print(f"✓ Completed in {elapsed:.1f}s\n"); return results

def place_orders_from_df(df_results):
    cancel_all_existing_orders_batch()
    existing_positions, positions_reliable = get_existing_positions()
    safe_mode = not positions_reliable
    try: bq_ref = client if 'client' in dir() else None; proj_ref = PROJECT_ID; ds_ref = DATASET_ID
    except: bq_ref, proj_ref, ds_ref = None, None, None
    ledger = integrate_ledger_into_run(exchange_client, bq_ref, proj_ref, ds_ref, SERIES_TICKER, True, bq_ref is not None, 30)
    all_orders = []; event_net_exposure = {}
    for ticker, pos_data in existing_positions.items():
        parts = ticker.split("-"); evt = "-".join(parts[:2]) if len(parts) >= 2 else ticker
        event_net_exposure[evt] = event_net_exposure.get(evt, 0) + abs(pos_data['net_position'])
    event_orders_placed = {}
    if 'df_summary' in globals() and len(df_summary) > 0:
        summary_data = df_summary[['ticker_part_3_market_code','yes_rate','count_occurrences']].copy()
        summary_data = summary_data.rename(columns={'yes_rate':'market_yes_rate','count_occurrences':'market_sample_size'})
        df_merged = df_results.merge(summary_data, on='ticker_part_3_market_code', how='left')
    else: df_merged = df_results.copy(); df_merged['market_yes_rate'] = None; df_merged['market_sample_size'] = 0
    if 'df_summary_rolling_by_team' in globals() and len(df_summary_rolling_by_team) > 0:
        team_latest = (df_summary_rolling_by_team.sort_values(['ticker_part_3_market_code','team','event_date'], ascending=[True,True,False])
            .groupby(['ticker_part_3_market_code','team'], as_index=False).first()
            [['ticker_part_3_market_code','team','yes_rate_rolling','count_occurrences_rolling']])
        t1 = team_latest.copy().rename(columns={'team':'team_1','yes_rate_rolling':'team_1_yes_rate','count_occurrences_rolling':'team_1_sample_size'})
        t2 = team_latest.copy().rename(columns={'team':'team_2','yes_rate_rolling':'team_2_yes_rate','count_occurrences_rolling':'team_2_sample_size'})
        df_merged = df_merged.merge(t1, on=['ticker_part_3_market_code','team_1'], how='left')
        df_merged = df_merged.merge(t2, on=['ticker_part_3_market_code','team_2'], how='left')
    else: df_merged['team_1_yes_rate'] = None; df_merged['team_1_sample_size'] = 0; df_merged['team_2_yes_rate'] = None; df_merged['team_2_sample_size'] = 0
    for _, row in df_merged.iterrows():
        if row.get("market_status") != "active": continue
        print(f"\n{row.get('market_ticker')}:")
        orders = build_order_objects_for_market(row.to_dict(), existing_positions, event_net_exposure, event_orders_placed, safe_mode, ledger)
        all_orders.extend(orders)
    print(f"\n{'='*70}\nPREPARED {len(all_orders)} POST-ONLY LIMIT ORDERS ({MODEL_VERSION})\n{'='*70}\n")
    if len(all_orders) == 0: print("No orders to place."); return pd.DataFrame(), pd.DataFrame(), ledger
    results = submit_orders_sequential(all_orders)
    global df_orders, df_market_snapshot_signals
    df_orders = pd.DataFrame(results); df_market_snapshot_signals = pd.DataFrame(market_snapshots)
    success = sum(1 for r in results if r["ok"]); failed = len(results) - success
    print(f"RESULTS: {success} successful, {failed} failed")
    if success > 0:
        ok = df_orders[df_orders['ok']==True]; print(f"  Total contracts: {ok['contracts'].sum()}")
        for side, grp in ok.groupby('side'): print(f"  {side.upper()}: {len(grp)} orders, {grp['contracts'].sum()} contracts, avg {grp['price'].mean():.0f}c")
    return df_orders, df_market_snapshot_signals, ledger

print("\nValidating df_results...")
to_trade = df_results[df_results["market_status"] == "active"]
print(f"Active markets: {len(to_trade)}")
if len(to_trade) == 0: df_orders = pd.DataFrame(); df_market_snapshot_signals = pd.DataFrame(); position_ledger = {}
else: df_orders, df_market_snapshot_signals, position_ledger = place_orders_from_df(df_results)

# =====================================================================
# UPLOAD TO BIGQUERY
# =====================================================================
if not os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"):
    try:
        from google.colab import auth; auth.authenticate_user()
    except ImportError: pass

PROJECT_ID = os.environ.get("GCP_PROJECT_ID", "elite-contact-446323-q7")
DATASET_ID = os.environ.get("GCP_DATASET_ID", "Kalshi")
client = bigquery.Client(project=PROJECT_ID)

df_results["yes_rate"] = pd.to_numeric(df_results["yes_rate"].replace("", np.nan), errors="coerce").infer_objects(copy=False)
for c in df_results.columns:
    if c != "yes_rate": df_results[c] = df_results[c].astype("string")
for col in ["event_date"]:
    if col in df_results.columns: df_results[col] = pd.to_datetime(df_results[col], errors="coerce").dt.date

def get_existing_table_schema(table_name):
    try: table = client.get_table(f"{PROJECT_ID}.{DATASET_ID}.{table_name}"); return {f.name: f.field_type for f in table.schema}
    except: return None

def pandas_dtype_to_bq_type(dtype):
    if pd.api.types.is_integer_dtype(dtype): return "INTEGER"
    elif pd.api.types.is_float_dtype(dtype): return "FLOAT"
    elif pd.api.types.is_bool_dtype(dtype): return "BOOLEAN"
    elif pd.api.types.is_datetime64_any_dtype(dtype): return "TIMESTAMP"
    return "STRING"

def convert_df_to_match_schema(df, schema_dict):
    df_c = df.copy()
    for col, bq_type in schema_dict.items():
        if col not in df_c.columns: continue
        if bq_type == "STRING" and not pd.api.types.is_string_dtype(df_c[col].dtype): df_c[col] = df_c[col].astype(str).replace('nan', None).replace('None', None)
        elif bq_type == "FLOAT": df_c[col] = pd.to_numeric(df_c[col], errors='coerce')
        elif bq_type == "INTEGER": df_c[col] = pd.to_numeric(df_c[col], errors='coerce').astype('Int64')
        elif bq_type == "BOOLEAN": df_c[col] = df_c[col].astype(bool)
    return df_c

def add_missing_columns_to_table(table_name, df, existing_schema):
    table_id = f"{PROJECT_ID}.{DATASET_ID}.{table_name}"; table = client.get_table(table_id)
    new_schema = list(table.schema)
    for col in df.columns:
        if col not in existing_schema: new_schema.append(bigquery.SchemaField(col, pandas_dtype_to_bq_type(df[col].dtype), mode="NULLABLE"))
    if len(new_schema) > len(table.schema): table.schema = new_schema; client.update_table(table, ["schema"])

def df_to_bq(df, table_name, write_disposition="WRITE_TRUNCATE"):
    table_id = f"{PROJECT_ID}.{DATASET_ID}.{table_name}"; df_up = df.copy()
    if write_disposition == "WRITE_APPEND":
        existing = get_existing_table_schema(table_name)
        if existing:
            new_cols = set(df_up.columns) - set(existing.keys())
            if new_cols: add_missing_columns_to_table(table_name, df_up, existing); existing = get_existing_table_schema(table_name)
            df_up = convert_df_to_match_schema(df_up, existing)
    job_config = bigquery.LoadJobConfig(write_disposition=write_disposition, autodetect=True)
    job = client.load_table_from_dataframe(df_up, table_id, job_config=job_config); job.result()
    print(f"✓ Loaded: {table_id} rows: {client.get_table(table_id).num_rows}")

df_to_bq(df_results, f"{SERIES_TICKER}_market_results", "WRITE_TRUNCATE")
df_to_bq(df_summary, f"{SERIES_TICKER}_market_results_summary", "WRITE_TRUNCATE")
if 'df_orders' in dir() and len(df_orders) > 0: df_to_bq(df_orders, f"{SERIES_TICKER}_orders", "WRITE_APPEND")
if 'df_market_snapshot_signals' in dir() and len(df_market_snapshot_signals) > 0:
    df_to_bq(df_market_snapshot_signals, f"{SERIES_TICKER}_market_snapshot_signals", "WRITE_APPEND")
if 'position_ledger' in dir() and position_ledger:
    df_ledger = ledger_to_dataframe(position_ledger)
    if len(df_ledger) > 0: df_to_bq(df_ledger, f"{SERIES_TICKER}_position_ledger", "WRITE_TRUNCATE")

print("\n✓ All tables uploaded successfully!")
